/** 各模块横向互链 · 单一数据源 */
const MAP = {
  soe: [
    { to: '/civilization', label: '文明透视 · 卷十二「盐铁逻辑」', note: '国有资本是盐铁官营在工业文明维度的重装实现。' },
    { to: '/private', label: '民营经济 · 国进民退边界', note: '命脉国有 vs 市场竞争的物理分界线。' },
    { to: '/reform', label: '改革开放 · 混改与抓大放小', note: '国企从普遍存量改革到结构性出清的历史脉络。' },
  ],
  reform: [
    { to: '/private', label: '民营经济 · 56789', note: '改革释放的市场空间与民营活力互为表里。' },
    { to: '/soe', label: '国有资本 · 战略底座', note: '抓大放小后的央企链主格局。' },
    { to: '/foreign-trade', label: '对外贸易 · 入世红利', note: '2001 入世嵌入全球分工的物理后果。' },
  ],
  demographic: [
    { to: '/housing', label: '住房地产 · 周期', note: '人口负增长与库存周期的叠加效应。' },
    { to: '/healthcare', label: '医疗医保 · DRG', note: '老龄化驱动的医保支付改革。' },
    { to: '/education', label: '教育 · 普职分流', note: '人口结构变化下的教育供给再配置。' },
  ],
  ruleoflaw: [
    { to: '/policydocs?tab=legal', label: '政令文库 · 法律条文', note: '可检索的法律/行政法规语料底座，与本模块态势分析互补。' },
    { to: '/governance', label: '治理现代化 · 数字政府', note: '智慧法院与网格治理的法治接口。' },
    { to: '/offshore', label: '港澳离岸 · 普通法窗口', note: '涉外法治与离岸司法管辖的衔接。' },
    { to: '/anticorruption', label: '反腐专题 · 制度约束', note: '法治化反腐与权力运行的边界。' },
  ],
  legalStatutes: [
    { to: '/ruleoflaw', label: '法治建设 · 司法现代化', note: '规范语料与制度红利态势的对照阅读。' },
    { to: '/policydocs', label: '政策文件库', note: '政策话语与立法修法的迭代节奏。' },
    { to: '/socialgov', label: '基层治理 · 枫桥经验', note: '行政规范与网格治理的执行接口。' },
    { to: '/foundation', label: '数据底座 · 条文库', note: '法律条文数据集录入与更新。' },
  ],
  manufacturing: [
    { to: '/techtree', label: '科技树 · 卡脖子清单', note: 'GVC 微笑曲线与国产替代的节点对应。' },
    { to: '/semiconductor', label: '半导体 · 芯片主权', note: '制造业皇冠上的明珠。' },
    { to: '/robotics', label: '机器人 · 密度与人形', note: '智能制造的物理执行层。' },
  ],
  military: [
    { to: '/straits', label: '台海局势 · 地缘重力', note: 'A2/AD 与统一确定性的物理盘面。' },
    { to: '/techtree', label: '科技树 · 军事分支', note: '装备迭代与作战概念的技术底座。' },
    { to: '/deterrence', label: '威慑战略 · 可信承诺', note: '能力 × 决心 × 可信度的威慑平衡。' },
  ],
  straits: [
    { to: '/thucydides', label: '修昔底德陷阱 · 实力窗口', note: '台海是结构高危叠加擦枪走火的最可能燧石。' },
    { to: '/deterrence', label: '威慑战略 · 边缘政策', note: '封控与介入的威慑可信度计算。' },
    { to: '/military', label: '军事力量 · A2/AD', note: '区域拒止能力的装备与部署底座。' },
    { to: '/semiconductor', label: '半导体 · 硅盾', note: '台积电与全球产业链人质的非对称筹码。' },
  ],
  thucydides: [
    { to: '/diplomacy', label: '外交博弈 · 竞合管控', note: '实力转移窗口落到中美矢量盘。' },
    { to: '/straits', label: '台海局势', note: '最可能的结构触发点。' },
    { to: '/talent?tab=diplomatic', label: '外交人才 · 驻外使节', note: '驻美驻欧等关键使节节点与大国博弈执行层。' },
    { to: '/talent?tab=taiwan', label: '港澳台政要', note: '台港澳政治人物队列，与 PRC 中国政要分轨。' },
    { to: '/realism', label: '现实主义 · 进攻性悲观', note: '结构约束 vs 能动空间的对照。' },
  ],
  realism: [
    { to: '/thucydides', label: '修昔底德陷阱 · 可规避窗口', note: '共享结构起点，不同政策结论。' },
    { to: '/diplomacy', label: '外交博弈', note: '大国政治的实操盘面。' },
    { to: '/deterrence', label: '威慑战略', note: '谢林式边缘政策与可信承诺。' },
  ],
  deterrence: [
    { to: '/straits', label: '台海 · 介入代价', note: '外部干预的威慑平衡计算。' },
    { to: '/military', label: '军事力量', note: '威慑能力的物理载体。' },
    { to: '/gametheory', label: '博弈论 · 重复博弈', note: '以牙还牙与边缘策略的均衡。' },
  ],
  omnisecurity: [
    { to: '/food-security', label: '粮食安全 · 18 亿亩红线', note: '大安全观第一支柱的专题深潜。' },
    { to: '/energy', label: '能源 · 压舱石', note: 'SPR 与非化石转型的能源冗余。' },
    { to: '/supplychain', label: '供应链 · 韧性备份', note: '极端制裁下的生存确定性。' },
    { to: '/computing', label: '算力设施 · 语义防火墙', note: '网络主权与数据流向控制。' },
  ],
  redweb: [
    { to: '/digital-giant-web', label: '数字巨网 · 赛博反馈', note: '语义防火墙与舆情闭环的网络物理。' },
    { to: '/powerlogic', label: '权力逻辑 · 儒表法里', note: '权贵网络与数字利维坦的底层代码。' },
    { to: '/govsystem', label: '政府体系 · 执行算法', note: '压力型体制与晋升激励。' },
    { to: '/talent', label: '人才精英库 · 中国政要', note: '政治人物节点与权力网络的交叉验证。' },
  ],
  resources: [
    { to: '/marine', label: '海洋经济 · 航道安全', note: '权益矿与海上生命线的耦合。' },
    { to: '/bri', label: '一带一路 · 六廊六路', note: '海外资源获取的陆海通道。' },
    { to: '/energy', label: '能源 · 对外依存', note: '油气进口与战略储备的物理约束。' },
  ],
  marine: [
    { to: '/straits', label: '台海 · 第一岛链', note: '海权突破与岛链重力。' },
    { to: '/resources', label: '海外资源 · 权益矿', note: '海上通道与资源获取的联动。' },
    { to: '/foreign-trade', label: '对外贸易 · 海运通道', note: '全球贸易流量的物理载体。' },
  ],
  polar: [
    { to: '/resources', label: '海外资源 · 北极航道', note: '极地航线缩短亚欧航程的物理收益。' },
    { to: '/diplomacy', label: '外交博弈 · 极地治理', note: '北极理事会与规则制定权。' },
    { to: '/marine', label: '海洋经济 · 海权', note: '极地科考与商业开发的战略延伸。' },
  ],
  energy: [
    { to: '/nuclear', label: '核电 · 华龙一号', note: '基荷电源与能源压舱石。' },
    { to: '/smartgrid', label: '智能电网 · 特高压', note: '西电东送与源网荷储一体化。' },
    { to: '/hydrogen', label: '氢能 · 绿氢链条', note: '非化石能源的储运载体。' },
    { to: '/omnisecurity', label: '大安全观 · 能源冗余', note: 'SPR 与能源主权保障。' },
  ],
  private: [
    { to: '/soe', label: '国有资本 · 国进民退边界', note: '56789 贡献 vs 命脉国有控盘。' },
    { to: '/enterprise500', label: '民企 500 强 · 治理透视', note: '头部民营企业的产业分布。' },
    { to: '/reform', label: '改革开放 · 两个毫不动摇', note: '从政策善意到法律确权的演进。' },
  ],
  offshore: [
    { to: '/financeRmb', label: '人民币国际化 · CIPS', note: '离岸窗口与跨境清算体系。' },
    { to: '/ruleoflaw', label: '法治建设 · 涉外法治', note: '普通法窗口与内地法治的接口。' },
    { to: '/fdi', label: '跨境投资 · 双向流动', note: '离岸资本与内地市场的通道。' },
  ],
  semiconductor: [
    { to: '/manufacturing', label: '制造业 · GVC 位势', note: '芯片在微笑曲线上的锚点。' },
    { to: '/techtree', label: '科技树 · 卡脖子', note: 'EDA/光刻/材料的节点清单。' },
    { to: '/straits', label: '台海 · 硅盾', note: '10nm 以下产能的地缘集中度。' },
  ],
  computing: [
    { to: '/aiplus', label: '人工智能+ · 智算', note: '算力主权与行业大模型的底座。' },
    { to: '/data-element', label: '数据要素 · 东数西算', note: '算力枢纽与数据确权。' },
    { to: '/semiconductor', label: '半导体 · 芯片', note: '算力设施的硬件根节点。' },
  ],
  finance: [
    { to: '/debt', label: '地方债务 · 省际热力', note: '系统性风险的地理分布。' },
    { to: '/financeRmb', label: '人民币国际化', note: '货币主权与跨境支付。' },
    { to: '/greenfinance', label: '绿色金融 · 碳定价', note: '双碳目标下的金融工具。' },
  ],
  governance: [
    { to: '/govsystem', label: '政府体系 · 压力型体制', note: '网格治理与科层执行的接口。' },
    { to: '/socialgov', label: '基层治理 · 综治', note: '最后一公里与数字政府下沉。' },
    { to: '/ruleoflaw', label: '法治建设', note: '治理现代化的法治约束。' },
  ],
  govsystem: [
    { to: '/governance', label: '治理现代化', note: '执行算法与数字政府的上层设计。' },
    { to: '/principalagent', label: '委托代理 · 激励相容', note: '央地关系与信息不对称。' },
    { to: '/powerlogic', label: '权力逻辑', note: '儒表法里与数字利维坦。' },
  ],
  powerlogic: [
    { to: '/civilization', label: '文明透视 · 源代码', note: '权力逻辑在 12 卷叙事中的位置。' },
    { to: '/redweb', label: '红网 · 结构分析', note: '权贵网络与权力物理学的交叉。' },
    { to: '/govsystem', label: '政府体系', note: '压力型体制与执行算法。' },
  ],
  foodSecurity: [
    { to: '/omnisecurity', label: '大安全观 · 粮食支柱', note: '18 亿亩红线在大安全框架中的位置。' },
    { to: '/rural', label: '乡村振兴 · 县域', note: '粮食生产与农村制度的耦合。' },
    { to: '/bri', label: '一带一路 · 海外农业', note: '海外粮仓与进口多元化。' },
  ],
  ecology: [
    { to: '/energy', label: '能源 · 双碳转型', note: '非化石能源与碳排放强度。' },
    { to: '/greenfinance', label: '绿色金融 · 碳市场', note: 'GEP 与碳定价的金融化。' },
    { to: '/megaprojects', label: '超级工程 · 生态 ROI', note: '大型生态工程的物理约束。' },
  ],
  bri: [
    { to: '/foreign-trade', label: '对外贸易 · RCEP', note: '陆海通道与贸易流量。' },
    { to: '/resources', label: '海外资源 · 权益矿', note: '一带一路上的资源获取节点。' },
    { to: '/financeRmb', label: '人民币国际化', note: '项目融资与跨境清算。' },
  ],
  dashboard: [
    { to: '/modules/renqun-tupu', label: '人群画像总图谱 · GY-00', note: '中国人群分析组总入口，34 片切片钻探进度。' },
    { to: '/market-pulse', label: '全球资产脉搏 · 实时行情', note: '股债汇大宗 18 标的轮询。' },
    { to: '/diplomacy', label: '外交博弈 · 矢量盘', note: '战略态势速览数据源。' },
    { to: '/policydocs', label: '政策文库 · 施政基准', note: '政策脉搏活数据接口。' },
  ],
  foreignTrade: [
    { to: '/market-pulse', label: '全球资产脉搏 · 汇率大宗', note: 'USD/CNY 与贸易定价基准。' },
    { to: '/reform', label: '改革开放 · 入世红利', note: '外贸依存度峰值与回落。' },
    { to: '/bri', label: '一带一路', note: '贸易通道的陆海延伸。' },
    { to: '/marine', label: '海洋经济 · 航运', note: '海运通道与造船能力。' },
  ],
  supplychain: [
    { to: '/omnisecurity', label: '大安全观 · 生存冗余', note: '供应链备份与国产替代。' },
    { to: '/semiconductor', label: '半导体 · 卡脖子', note: '关键节点的断供风险。' },
    { to: '/materials', label: '关键材料 · 替代', note: '上游材料的韧性建设。' },
  ],
  hydrogen: [
    { to: '/energy', label: '能源 · 绿电制氢', note: '非化石能源的储运载体。' },
    { to: '/automotive', label: '汽车主权 · 燃料电池', note: '氢能汽车的产业化路径。' },
    { to: '/smartgrid', label: '智能电网 · 储能', note: '源网荷储与氢储能协同。' },
  ],
  nuclear: [
    { to: '/energy', label: '能源 · 压舱石', note: '基荷电源与能源结构。' },
    { to: '/materials', label: '关键材料 · 核级', note: '核级材料与进口替代。' },
    { to: '/megaprojects', label: '超级工程 · 华龙一号', note: '核电项目的多维 ROI。' },
  ],
  logistics: [
    { to: '/supplychain', label: '供应链 · 韧性', note: '多式联运与备份通道。' },
    { to: '/infrastructure', label: '基础设施 · 专项债', note: '物流枢纽的新老基建。' },
    { to: '/foreign-trade', label: '对外贸易 · 通道', note: '进出口流量的物理载体。' },
  ],
  cognition: [
    { to: '/middleincometrap', label: '中等收入陷阱', note: '长波周期与发展阶段窗口。' },
    { to: '/pathdependence', label: '路径依赖 · 锁定', note: '技术路线与制度锁定的交互。' },
    { to: '/reform', label: '改革开放 · 算法演进', note: '康波下行期的改革节奏。' },
  ],
  gametheory: [
    { to: '/deterrence', label: '威慑战略 · 边缘政策', note: '重复博弈与可信承诺。' },
    { to: '/diplomacy', label: '外交博弈', note: '大国互动的均衡求解。' },
    { to: '/straits', label: '台海 · 博弈盘面', note: '统一/维持/介入的三方博弈。' },
    { to: '/talent?tab=diplomatic', label: '外交人才 · 驻外使节', note: '多边与双边外交执行节点。' },
    { to: '/talent?tab=taiwan', label: '港澳台政要', note: '台港澳政治人物决策节点。' },
  ],
  automotive: [
    { to: '/foreign-trade', label: '对外贸易 · 新三样', note: 'EV 是出口结构升级引擎。' },
    { to: '/semiconductor', label: '半导体 · 车规芯片', note: '智驾芯片先进制程约束。' },
    { to: '/hydrogen', label: '氢能 · 燃料电池', note: '商用车氢能产业化路径。' },
  ],
  digital: [
    { to: '/digital-giant-web', label: '数字巨网 · 五维透视', note: '网络经济、传媒、舆情与治理的系统耦合。' },
    { to: '/data-element', label: '数据要素 · 确权入表', note: '数字经济与要素市场化耦合。' },
    { to: '/computing', label: '算力设施 · 东数西算', note: '智算中心是数字基础设施底座。' },
    { to: '/aiplus', label: '人工智能+ · 行业落地', note: '大模型驱动数实融合。' },
  ],
  digitalGiantWeb: [
    { to: '/digital', label: '数字经济 · 数实融合', note: '平台经济与产业数字化的宏观盘面。' },
    { to: '/data-element', label: '数据要素 · 确权入表', note: '数据作为第五要素的制度接口。' },
    { to: '/computing', label: '算力设施 · 东数西算', note: '网络世界的物理算力底座。' },
    { to: '/redweb', label: '红色巨网 · 结构拓扑', note: '赛博反馈与语义防火墙的控制网络。' },
    { to: '/socialgov', label: '基层治理 · 网格综治', note: '舆情闭环的毛细血管终端。' },
    { to: '/gig', label: '零工经济 · 算法治理', note: '网络经济的就业蓄水池。' },
    { to: '/culture', label: '文化软实力 · 短剧出海', note: '网络传媒的出海与规则博弈。' },
    { to: '/powerlogic', label: '权力逻辑 · 数字利维坦', note: '数字治理的底层权力代码。' },
  ],
  dataElement: [
    { to: '/computing', label: '算力设施 · 枢纽', note: '数据加工与算力地理分布耦合。' },
    { to: '/digital', label: '数字经济 · 数实融合', note: '要素市场化赋能千行百业。' },
    { to: '/ruleoflaw', label: '法治建设 · 数据合规', note: '确权、出境与隐私计算边界。' },
  ],
  culture: [
    { to: '/foreign-trade', label: '对外贸易 · 新业态', note: '文化出口与跨境电商协同。' },
    { to: '/digital', label: '数字经济 · 平台', note: '短视频与游戏出海底座。' },
    { to: '/diplomacy', label: '外交博弈 · 软实力', note: '文化渗透与规则话语权。' },
  ],
  aiplus: [
    { to: '/computing', label: '算力设施 · 智算', note: 'AI+ 的物理底座。' },
    { to: '/semiconductor', label: '半导体 · GPU', note: '训练芯片出口管制变量。' },
    { to: '/data-element', label: '数据要素 · 语料', note: '合规语料供给规模。' },
  ],
  quantum: [
    { to: '/npf', label: '新质生产力 · 未来产业', note: '量子信息是未来产业主赛道。' },
    { to: '/basic-research', label: '基础研究 · 大科学装置', note: '国家实验室领衔攻关。' },
    { to: '/techtree', label: '科技树 · 前沿分支', note: '量子在科技树中的节点。' },
  ],
  tech: [
    { to: '/basic-research', label: '基础研究 · 原始创新', note: 'R&D 结构的源头短板。' },
    { to: '/npf', label: '新质生产力', note: '创新体系支撑 TFP 提升。' },
    { to: '/semiconductor', label: '半导体 · 卡脖子', note: '关键核心技术攻关节点。' },
  ],
  npf: [
    { to: '/tech', label: '创新体系 · R&D', note: '新质生产力的制度底座。' },
    { to: '/computing', label: '算力设施', note: '算力与数据要素约束。' },
    { to: '/supplychain', label: '供应链 · 韧性备份', note: '产业链备份与冗余。' },
  ],
  urban: [
    { to: '/demographic', label: '人口结构 · 城镇化', note: '人口流动与城市群集聚。' },
    { to: '/housing', label: '住房地产 · 周期', note: '存量更新与保障房。' },
    { to: '/regional', label: '区域协调 · 四大板块', note: '城市群与转移支付。' },
  ],
  industrysoftware: [
    { to: '/manufacturing', label: '制造业 · GVC', note: '工业软件是制造之魂。' },
    { to: '/semiconductor', label: '半导体 · EDA', note: 'CAD/CAE/EDA 共瓶颈。' },
    { to: '/supplychain', label: '供应链 · 信创', note: '国产替代与生态兼容。' },
  ],
  basicResearch: [
    { to: '/tech', label: '创新体系 · R&D', note: '基础研究占比与投入结构。' },
    { to: '/npf', label: '新质生产力', note: '原始创新支撑未来产业。' },
    { to: '/quantum', label: '量子信息', note: '大科学装置与专项工程。' },
  ],
  bio: [
    { to: '/healthcare', label: '医疗医保 · DRG', note: '支付改革塑造创新药需求。' },
    { to: '/npf', label: '新质生产力 · 生命科技', note: '生物制造与未来健康赛道。' },
    { to: '/medequipment', label: '医疗装备 · 替代', note: '器械进口替代协同。' },
  ],
  neural: [
    { to: '/aiplus', label: '人工智能+ · BCI', note: '脑机接口与 AI 融合。' },
    { to: '/semiconductor', label: '半导体 · 神经芯片', note: '植入式芯片与测控。' },
    { to: '/ruleoflaw', label: '法治建设 · 神经数据', note: '伦理审查与数据主权。' },
  ],
  ideology: [
    { to: '/powerlogic', label: '权力逻辑 · 儒表法里', note: '意识形态与权力运作底层。' },
    { to: '/soe', label: '国有资本 · 公有制', note: '马克思主义与国家角色的实践接口。' },
    { to: '/private', label: '民营经济 · 市场化', note: '自由主义与新自由主义工具底色。' },
  ],
  powerphysics: [
    { to: '/powerlogic', label: '权力逻辑 · 能量守恒', note: '权力的物理约束与制度叙事。' },
    { to: '/redweb', label: '红网 · 结构拓扑', note: '权力流动的网络物理。' },
    { to: '/govsystem', label: '政府体系 · 压力传导', note: '科层体制的能量衰减。' },
  ],
  dissipative: [
    { to: '/cognition', label: '认知内核 · 复杂系统', note: '耗散结构与远离平衡态。' },
    { to: '/reform', label: '改革开放 · 试错迭代', note: '开放系统吸收负熵。' },
    { to: '/antifragile', label: '反脆弱 · 凸性收益', note: '波动与秩序的辩证。' },
  ],
  pathdependence: [
    { to: '/cognition', label: '认知内核', note: '技术锁定与制度惯性。' },
    { to: '/reform', label: '改革开放 · 路径分叉', note: '入世后的深度依赖。' },
    { to: '/middleincometrap', label: '中等收入陷阱', note: '增长路径的锁定风险。' },
  ],
  middleincometrap: [
    { to: '/cognition', label: '认知内核 · 康波', note: '长波周期与阶段窗口。' },
    { to: '/manufacturing', label: '制造业 · 位势跃迁', note: '跨越陷阱的产业锚点。' },
    { to: '/reform', label: '改革开放', note: '体制变革与增长动能。' },
  ],
  antifragile: [
    { to: '/omnisecurity', label: '大安全观 · 冗余', note: '杠铃策略与生存确定性。' },
    { to: '/supplychain', label: '供应链 · 韧性备份', note: '凸性布局与尾部风险。' },
    { to: '/dissipative', label: '耗散结构', note: '远离平衡态的自组织。' },
  ],
  constructivism: [
    { to: '/diplomacy', label: '外交博弈 · 话语建构', note: '规范与认同的塑造。' },
    { to: '/ideology', label: '意识形态', note: '叙事框架与身份认同。' },
    { to: '/realism', label: '现实主义', note: '建构主义与现实主义对照。' },
  ],
  principalagent: [
    { to: '/govsystem', label: '政府体系 · 央地委托', note: '信息不对称与激励扭曲。' },
    { to: '/governance', label: '治理现代化', note: '委托链条的数字化穿透。' },
    { to: '/anticorruption', label: '反腐专题', note: '代理成本与制度约束。' },
  ],
  commons: [
    { to: '/ecology', label: '生态环保 · 外部性', note: '公地悲剧与生态红线。' },
    { to: '/governance', label: '治理现代化', note: '集体行动与规则供给。' },
    { to: '/data-element', label: '数据要素', note: '数字公地与确权边界。' },
  ],
  contradictions: [
    { to: '/governance', label: '治理现代化 · 数字政府', note: '官民矛盾与执行精度的制度接口。' },
    { to: '/govsystem', label: '政府体系 · 央地委托', note: '事权财权倒挂与压力型体制。' },
    { to: '/regional', label: '区域协调 · 四大板块', note: '东中西梯度与转移支付。' },
    { to: '/rural', label: '乡村振兴 · 县域', note: '城乡矛盾与要素流动壁垒。' },
    { to: '/urban', label: '新型城镇化', note: '户籍城镇化与市民化缺口。' },
    { to: '/demographic', label: '人口结构 · 老龄化', note: '代际矛盾与抚养比攀升。' },
    { to: '/reform', label: '改革开放 · 制度演进', note: '矛盾缓和的机制性出口。' },
    { to: '/private', label: '民营经济 · 56789', note: '阶层流动与劳资博弈的市场维度。' },
  ],
  healthcare: [
    { to: '/demographic', label: '人口结构 · 老龄化', note: '医保精算压力来源。' },
    { to: '/bio', label: '生物制造 · 创新药', note: '集采后的研发驱动。' },
    { to: '/medequipment', label: '医疗装备 · 替代', note: '器械国产化协同。' },
  ],
  housing: [
    { to: '/demographic', label: '人口结构', note: '生育意愿的成本约束。' },
    { to: '/urban', label: '城镇化 · 城市群', note: '土地财政与区域集聚。' },
    { to: '/finance', label: '金融体系 · 债务', note: '三道红线与系统风险。' },
  ],
  education: [
    { to: '/demographic', label: '人口结构 · 人才红利', note: '密度红利供给端。' },
    { to: '/talent', label: '人才精英库', note: '结构化人力资本图谱与供给端交叉参照。' },
    { to: '/gig', label: '灵活就业', note: '普职分流与就业结构。' },
  ],
  gig: [
    { to: '/socialgov', label: '基层治理 · 综治', note: '新业态劳动者保障。' },
    { to: '/education', label: '教育 · 就业映射', note: '技能供给与平台用工。' },
    { to: '/urban', label: '城镇化', note: '城市灵活就业规模。' },
  ],
  socialgov: [
    { to: '/policydocs?tab=legal', label: '政令文库 · 法律条文', note: '信访、应急、处罚等行政法规的检索底座。' },
    { to: '/digital-giant-web', label: '数字巨网 · 舆情网格', note: '赛博反馈回路的基层终端。' },
    { to: '/governance', label: '治理现代化', note: '数字政府下沉最后一公里。' },
    { to: '/govsystem', label: '政府体系', note: '网格与科层接口。' },
    { to: '/gig', label: '灵活就业', note: '新业态纳入综治网格。' },
  ],
  infrastructure: [
    { to: '/megaprojects', label: '超级工程', note: '基建项目的多维 ROI。' },
    { to: '/logistics', label: '物流枢纽', note: '多式联运物理网络。' },
    { to: '/regional', label: '区域协调', note: '专项债与区域基建。' },
  ],
  megaprojects: [
    { to: '/infrastructure', label: '基础设施', note: '新老基建的物理底座。' },
    { to: '/nuclear', label: '核电 · 华龙一号', note: '能源超级工程的压舱石。' },
    { to: '/ecology', label: '生态环保', note: '生态工程的物理约束。' },
  ],
  space: [
    { to: '/military', label: '军事力量', note: '航天与国防的产业链耦合。' },
    { to: '/techtree', label: '科技树 · 航天分支', note: '商业航天与低轨星座。' },
    { to: '/megaprojects', label: '超级工程', note: '重大专项的跨周期投入。' },
  ],
  medequipment: [
    { to: '/healthcare', label: '医疗医保 · DRG', note: '支付改革塑造器械需求。' },
    { to: '/bio', label: '生物制造', note: '高端医疗器械国产化。' },
    { to: '/manufacturing', label: '制造业 · GVC', note: '进口替代与专精特新。' },
  ],
  tourism: [
    { to: '/culture', label: '文化产业', note: '文旅融合与消费升级。' },
    { to: '/foreign-trade', label: '对外贸易 · 服务贸易', note: '入境游与服务出口。' },
    { to: '/digital', label: '数字经济 · 平台', note: '在线文旅与数字营销。' },
  ],
  civilAviation: [
    { to: '/space', label: '商业航天', note: '空天一体化的产业链延伸。' },
    { to: '/logistics', label: '物流枢纽', note: '航空货运与多式联运。' },
    { to: '/manufacturing', label: '制造业 · C919', note: '大飞机国产化的制造节点。' },
  ],
  regional: [
    { to: '/urban', label: '城镇化 · 城市群', note: '四大板块与都市圈。' },
    { to: '/demographic', label: '人口流动', note: '人往哪里去决定区域位势。' },
    { to: '/bri', label: '一带一路', note: '西部陆海新通道与开放格局。' },
    { to: '/northeast', label: '东北振兴 · 三省', note: '老工业基地与全面振兴新突破。' },
  ],
  northeastRevival: [
    { to: '/regional', label: '区域协调 · 四大板块', note: '东北板块在转移支付与南北差距中的位势。' },
    { to: '/rural', label: '乡村振兴 · 北大仓', note: '粮食安全与黑土地保护工程。' },
    { to: '/manufacturing', label: '制造业 · 装备链', note: '老工业基地与 GVC 升级。' },
    { to: '/demographic', label: '人口结构 · 老龄化', note: '净流出、低生育与人才外流。' },
    { to: '/automotive', label: '汽车产业 · 一汽', note: '长春汽车城与新能源转型。' },
    { to: '/soe', label: '国有资本 · 央企', note: '国企比重与混改试点。' },
    { to: '/reform', label: '改革开放 · 制度创新', note: '体制机制创新与营商环境。' },
    { to: '/energy', label: '能源 · 油田煤电', note: '大庆油田与新能源替代。' },
  ],
  rural: [
    { to: '/food-security', label: '粮食安全 · 18亿亩', note: '耕地保护与产能底线。' },
    { to: '/demographic', label: '人口结构', note: '乡村振兴与劳动力回流。' },
    { to: '/ecology', label: '生态环保', note: '农业农村绿色发展。' },
  ],
  benchmark: [
    { to: '/manufacturing', label: '制造业 · 对标', note: '全球位势参照系。' },
    { to: '/regional', label: '区域协调', note: '省际竞争力排名。' },
    { to: '/infrastructure', label: '基础设施', note: '基建密度国际对照。' },
  ],
  diplomacy: [
    { to: '/thucydides', label: '修昔底德陷阱 · 实力窗口', note: '大国关系定价锚与实力转移物理约束。' },
    { to: '/gametheory', label: '博弈论 · 竞合均衡', note: '重复博弈与边缘政策的外交映射。' },
    { to: '/talent?tab=diplomatic', label: '外交人才 · 驻外使节全图', note: '中国驻外大使/公使/总领事公开任职节点与全球驻节分布。' },
    { to: '/talent?tab=taiwan', label: '港澳台政要', note: '台海博弈关键政治人物节点与权力结构。' },
    { to: '/bri', label: '一带一路 · 全球南方', note: '南南合作与多边机制的舞台延伸。' },
  ],
  techtree: [
    { to: '/semiconductor', label: '半导体 · 卡脖子', note: '科技树最硬受制节点深潜。' },
    { to: '/npf', label: '新质生产力', note: '战略科技领域与产业政策主线。' },
    { to: '/manufacturing', label: '制造业 · GVC 位势', note: '国产替代与微笑曲线锚点。' },
  ],
  depth: [
    { to: '/civilization', label: '文明透视 · 十二卷', note: '深度透视的内容母卷与逻辑锚点。' },
    { to: '/powerlogic', label: '权力逻辑', note: '制度专题的底层源代码。' },
    { to: '/cognition', label: '认知内核 · 理论透镜', note: '八维矩阵的理论支撑层。' },
  ],
  sandbox: [
    { to: '/sandbox?tab=handong', label: '汉东省沙盘', note: '虚构省域推演：参数配置、主官派遣、四件套应对。' },
    { to: '/sandbox?tab=inspection', label: '中央巡视沙盘', note: '线索研判、谈话调度与整改跟踪。' },
    { to: '/sandbox?tab=party-school', label: '党校研修', note: '干部培训与梯队建设推演。' },
    { to: '/sandbox?tab=org-dept', label: '组织画像', note: '全库六维画像与情景匹配底座。' },
    { to: '/sandbox?tab=wargame', label: '大国博弈推演桌', note: '科技-经贸回合制思想实验。' },
    { to: '/watchtower', label: '全局监测台', note: '红橙告警触发战役模式与判定回流。' },
    { to: '/govsystem', label: '政府体系 · 压力型体制', note: '组织算法与政绩评价矩阵。' },
    { to: '/talent', label: '人才精英库 · 中国政要', note: '政要池与省域配置联动。' },
    { to: '/talent?tab=anticorruption', label: '反腐透视', note: '反腐风暴情景的制度语境。' },
    { to: '/regional', label: '区域协调 · 省际', note: '熵增地图与区域治理对照。' },
  ],
  leadership: [
    { to: '/talent', label: '人才精英库 · 中国政要', note: '政治局常委与省部级政要结构化图谱，与本模块人事布局同源。' },
    { to: '/sandbox', label: '治国沙盒', note: '省域主官配置与危机情景推演，对接人事轮换逻辑。' },
    { to: '/sandbox?tab=inspection', label: '中央巡视沙盘', note: '巡视巡察作为制度工具箱的执行模拟。' },
    { to: '/diplomacy', label: '外交博弈 · 元首外交', note: '最高层对外校准与全球矢量盘。' },
    { to: '/govsystem', label: '政府体系 · 压力型体制', note: '科层执行算法与晋升激励矩阵。' },
    { to: '/powerlogic', label: '权力逻辑 · 儒表法里', note: '权力运作底层代码与制度叙事。' },
  ],
  policydocs: [
    { to: '/policydocs?tab=legal', label: '法律条文', note: '政策话语背后的立法与行政法规支撑。' },
    { to: '/reform', label: '改革开放 · 政策演进', note: '政府工作报告的历史脉络。' },
    { to: '/npf', label: '新质生产力', note: '政策话语迭代的关键节点。' },
    { to: '/foundation', label: '数据底座 · 文件库', note: '政策文件上传解析后台。' },
  ],
  talent: [
    { to: '/redweb', label: '红网 · 结构分析', note: '政治人物节点与权力网络交叉验证。' },
    { to: '/ruleoflaw', label: '法治建设', note: '司法现代化与权利救济的制度语境。' },
    { to: '/socialgov', label: '基层治理 · 综治', note: '网格治理与维稳机制的执行接口。' },
    { to: '/sandbox', label: '治国沙盒', note: '政要池与省域配置联动。' },
    { to: '/sandbox?tab=party-school', label: '党校研修', note: '干部培训与梯队建设推演。' },
    { to: '/sandbox?tab=org-dept', label: '组织画像', note: '全库六维画像与情景匹配底座。' },
    { to: '/education', label: '教育 · 人才红利', note: '机构载体与人力资本供给端。' },
    { to: '/talent?tab=dissident', label: '异见人士', note: '公开记录中的异议表达者与制度边界案例。' },
    { to: '/talent?tab=taiwan', label: '港澳台政要', note: '台港澳公开任职政治人物，与 PRC 中国政要分轨建档。' },
    { to: '/talent?tab=knowledge', label: '知识精英', note: '境内知识生产队列，与海外人才互补。' },
    { to: '/talent?tab=business', label: '商业精英', note: '境内资本逻辑队列，与海外产业节点交叉。' },
    { to: '/talent?tab=overseas', label: '海外人才', note: '跨境人力资本队列，聚焦海外驻留/游学节点。' },
    { to: '/talent?tab=diplomatic', label: '外交人才', note: '驻外使节公开任职图谱，与政要/海外人才分轨。' },
    { to: '/diplomacy', label: '外交博弈', note: '大国竞合与多边机制态势模块。' },
    { to: '/digital-giant-web', label: '数字巨头网络', note: '全球科技巨头与华人技术精英的产业链映射。' },
  ],
  enterprise500: [
    { to: '/private', label: '民营经济 · 56789', note: '宏观贡献与营商环境语境。' },
    { to: '/soe', label: '国有资本 · 战略底座', note: '国资/民营双轨对照。' },
    { to: '/principalagent', label: '委托代理', note: '创始人—职业经理人治理张力。' },
  ],
  foundation: [
    { to: '/watchtower', label: '全局监测台', note: '六域先行指标聚合与越线告警。' },
    { to: '/policydocs', label: '政令文库 · 政策文件', note: '前台政策比对与洞察。' },
    { to: '/policydocs?tab=legal', label: '政令文库 · 法律条文', note: '法律/行政法规语料前台检索。' },
    { to: '/talent', label: '人才精英库', note: '结构化人力资本图谱前台展示。' },
    { to: '/enterprise500', label: '民企500强', note: '民营经济数据集前台。' },
  ],
  watchtower: [
    { to: '/foundation', label: '数据底座', note: '指标底表与数据集录入后台。' },
    { to: '/sandbox', label: '治国沙盒', note: '红橙告警联动战役推演与判定回流。' },
    { to: '/dashboard', label: '中枢看板', note: '态势速览与简报生成。' },
  ],
  lowAltitude: [
    { to: '/civil-aviation', label: '民航与大飞机 · 空域', note: '低空与高空干线的空域分层与制造协同。' },
    { to: '/space', label: '航天 · 商业航天', note: '空天一体化的产业链延伸。' },
    { to: '/npf', label: '新质生产力 · 战新产业', note: '低空经济是战略性新兴产业新增长极。' },
  ],
  unifiedMarket: [
    { to: '/reform', label: '改革开放 · 要素市场化', note: '统一大市场是深化改革的内部底盘。' },
    { to: '/regional', label: '区域协调 · 破除分割', note: '地方保护与区域壁垒的破除接口。' },
    { to: '/private', label: '民营经济 · 公平竞争', note: '负面清单与平等准入的市场主体语境。' },
  ],
  consumption: [
    { to: '/demographic', label: '人口结构 · 内需基数', note: '人口与收入结构决定消费纵深。' },
    { to: '/private', label: '民营经济 · 就业与收入', note: '居民收入预期与消费能力的来源。' },
    { to: '/tourism', label: '文旅消费 · 服务升级', note: '服务消费扩容的重要载体。' },
  ],
  silverEconomy: [
    { to: '/demographic', label: '人口结构 · 老龄化', note: '银发需求侧的人口底盘。' },
    { to: '/healthcare', label: '医疗医保 · 医养结合', note: '长护险与养老照护的支付接口。' },
    { to: '/fertility-support', label: '生育支持 · 代际平衡', note: '少子化与老龄化的双向人口政策。' },
  ],
  futureIndustry: [
    { to: '/npf', label: '新质生产力 · 战新产业', note: '未来产业是新质生产力的种子期前沿。' },
    { to: '/techtree', label: '科技树 · 前沿分支', note: '颠覆性技术的赛道地图。' },
    { to: '/basic-research', label: '基础研究 · 原始创新', note: '种子赛道的源头供给。' },
  ],
  eduSciTalent: [
    { to: '/talent', label: '人才精英库', note: '人力资本图谱的供给与配置底座。' },
    { to: '/talent?tab=overseas', label: '海外人才', note: '跨境游学与海外华人知识技术节点的回流接口。' },
    { to: '/basic-research', label: '基础研究 · 创新链', note: '原始创新与攻关主战场。' },
    { to: '/tech', label: '创新体系 · R&D', note: '三链一体化的制度接口。' },
  ],
  publicSafety: [
    { to: '/governance', label: '治理现代化 · 应急', note: '平急两用与应急管理的治理接口。' },
    { to: '/omnisecurity', label: '大安全观 · 城市层面', note: '公共安全是大安全观的物理落地。' },
    { to: '/urban', label: '新型城镇化 · 韧性城市', note: '城市生命线与平急两用设施。' },
  ],
  fertilitySupport: [
    { to: '/demographic', label: '人口结构 · 生育率', note: '生育支持的人口政策底盘。' },
    { to: '/silver-economy', label: '银发经济 · 代际平衡', note: '少子与老龄的双向人口结构。' },
    { to: '/housing', label: '住房地产 · 养育成本', note: '住房是生育成本的两座大山之一。' },
  ],
  frontierGov: [
    { to: '/regional', label: '区域协调 · 转移支付', note: '边疆九省区财政转移支付与对口支援。' },
    { to: '/rural', label: '乡村振兴 · 兴边富民', note: '边境县产业振兴与城乡融合。' },
    { to: '/bri', label: '一带一路 · 向西开放', note: '边疆口岸与陆海新通道。' },
    { to: '/inst-open', label: '制度开放 · 自贸试验', note: '边疆自贸试验区制度创新。' },
  ],
  instOpen: [
    { to: '/fdi', label: '跨境投资 · 负面清单', note: '外资准入与双向流动。' },
    { to: '/foreign-trade', label: '对外贸易 · 高水平开放', note: '制度型开放与贸易流量。' },
    { to: '/offshore', label: '港澳离岸 · 规则衔接', note: '大湾区与普通法窗口。' },
    { to: '/ruleoflaw', label: '法治建设 · 涉外法治', note: '高标准经贸规则的法治接口。' },
  ],
  marketPulse: [
    { to: '/dashboard', label: '中枢看板 · 全局总揽', note: '态势速览与模块入口。' },
    { to: '/capital-market', label: '资本市场 · 耐心资本', note: 'A 股制度与中长期资金。' },
    { to: '/foreign-trade', label: '对外贸易 · 新三样', note: '汇率与贸易流量联动。' },
    { to: '/rmb', label: '人民币国际化 · CIPS', note: '离岸窗口与跨境结算。' },
  ],
  capitalMarket: [
    { to: '/market-pulse', label: '全球资产脉搏 · 实时行情', note: '股债汇大宗多标的快照。' },
    { to: '/finance', label: '金融系统 · 系统风险', note: '资本市场是金融安全的关键子系统。' },
    { to: '/npf', label: '新质生产力 · 创投', note: '耐心资本与硬科技孵化。' },
    { to: '/private', label: '民营经济 · 融资', note: '直接融资与民企资金链。' },
    { to: '/debt', label: '地方债务 · 化债', note: '城投与资本市场风险传导。' },
  ],
  serviceTrade: [
    { to: '/foreign-trade', label: '对外贸易 · 新三样', note: '货物贸易升级后的服务曲线。' },
    { to: '/digital', label: '数字经济 · 平台', note: '数字贸易的产业底座。' },
    { to: '/tourism', label: '文旅消费 · 入境游', note: '旅行服务贸易载体。' },
    { to: '/culture', label: '文化软实力 · 出海', note: '文化服务出口协同。' },
  ],
  tcmHealth: [
    { to: '/healthcare', label: '医疗医保 · 支付', note: '中医药纳入医保与集采。' },
    { to: '/bio', label: '生物医药 · 创新', note: '中药现代化与生物制造。' },
    { to: '/silver-economy', label: '银发经济 · 康养', note: '治未病与养老健康消费。' },
    { to: '/culture', label: '文化软实力 · 出海', note: '中医药文化走出去。' },
  ],
  defenseMobilization: [
    { to: '/military', label: '军事力量 · 主战', note: '动员体系与作战力量的接口。' },
    { to: '/public-safety', label: '公共安全 · 应急', note: '平急两用与应急管理衔接。' },
    { to: '/computing', label: '算力设施 · 动员潜力', note: '新域新质算力动员预案。' },
    { to: '/low-altitude', label: '低空经济 · 无人机', note: '民用无人机转军用通道。' },
  ],
  renqunTupu: [
    { to: '/modules/qingnian', label: '青年 · GY-03 子集 I', note: '已钻透三片之一，可见窗口决定对待方式。' },
    { to: '/modules/xingshaoshu', label: '性少数 · GY-04 子集 II', note: '已钻透三片之一，可见形态即存在形态。' },
    { to: '/modules/linggong', label: '零工经济 · GY-05 子集 III', note: '已钻透三片之一，双重身份者被寄存。' },
    { to: '/modules/tajian', label: '塔尖 · 退出成本校准点', note: '价目表话语权维极值，退出成本峰值。' },
    { to: '/modules/tuiyi', label: '退役军人 · 组织化校准点', note: '价目表风险维极值，组织化峰值。' },
    { to: '/modules/canzhang', label: '残障 · 可见性校准点', note: '价目表待遇维零点，可见性归零。' },
    { to: '/modules/guoyun', label: '国运推演 · GY-01', note: '与 GY-02 共用设计令牌与年度对账节奏。' },
    { to: '/modules/yishixingtai', label: '合法性机器 · GY-02', note: '母框架意识形态层，与人群价目表假说互证。' },
  ],
  guoyun: [
    { to: '/modules/renqun-tupu', label: '人群画像总图谱 · GY-00', note: '34 片人群切片母索引，钻探进度与价目表假说验证结构。' },
    { to: '/modules/yishixingtai', label: '合法性机器 · GY-02', note: '意识形态五组件与张力层，与推演三变量四情景双向耦合。' },
    { to: '/modules/yishixingtai?tab=tension&tension=t03', label: '张力 T-03 · 复兴叙事 ⟂ 停滞', note: '日本化情景的意识形态杀伤大于经济杀伤。' },
    { to: '/modules/guoyun?tab=timeline', label: '国运时间轴 · 已发生', note: '1949→2026 七时代六域大事记谱系。' },
    { to: '/modules/qingnian', label: '青年 · GY-03 子集 I', note: '人群画像第一子集，共享「被特定窗口看见」母命题。' },
    { to: '/modules/xingshaoshu', label: '性少数 · GY-04 子集 II', note: '挤压性存在，与 GY-01 人口螺旋、GY-03 CH-01 性别分叉耦合。' },
    { to: '/modules/linggong', label: '零工经济 · GY-05 子集 III', note: '悬空的基础设施，L8 变量 A 压力测试问二最先兑现现场。' },
    { to: '/cognition', label: '康波周期 · 长波', note: '国运推演变量 A 的康波供给侧坐标。' },
  ],
  qingnian: [
    { to: '/modules/renqun-tupu', label: '人群画像总图谱 · GY-00', note: '人群分层母索引，34 片切片与八轴配平图谱。' },
    { to: '/modules/linggong', label: '零工经济 · GY-05 子集 III', note: '冰河期/公平语法/风险时间表三处咬合，下沉白领与青年汇流。' },
    { to: '/modules/linggong?tab=l2', label: 'GY-05 L2 · 三重身份', note: '非正规化主体人群与 CH-02 对照同构。' },
    { to: '/modules/xingshaoshu', label: '性少数 · GY-04 子集 II', note: '人群画像第二子集，共享「被特定窗口看见才被特定方式对待」母命题。' },
    { to: '/modules/xingshaoshu?tab=s3', label: 'GY-04 S3 · 政治定位', note: '挤压-转移机制与 CH-01/CH-03 同构。' },
    { to: '/modules/guoyun', label: '国运推演 · GY-01', note: '人口螺旋与 S7 人口替罪羊压力联动。' },
    { to: '/modules/yishixingtai', label: '合法性机器 · GY-02', note: '对自组织的无差别恐惧，S3 政治定位的基岩。' },
    { to: '/demographic', label: '人口结构 · 负增长', note: '青年退出与性少数人口耦合的宏观底盘。' },
  ],
  xingshaoshu: [
    { to: '/modules/linggong', label: '零工经济 · GY-05 子集 III', note: '风险源/风险汇方法论唯一双重身份人群，L8 稳定器悖论。' },
    { to: '/modules/qingnian', label: '青年 · GY-03 子集 I', note: '人群画像第一子集，S7 风险翻转与青年体制风险形成镜像。' },
    { to: '/modules/qingnian?tab=ch01', label: 'GY-03 CH-01 · 性别分叉', note: 'S7 性别战争附属战场与 Q-05/Q-08 联动。' },
    { to: '/modules/yishixingtai', label: '合法性机器 · GY-02', note: 'S3 政治定位 ↔ 基岩对自组织的无差别恐惧。' },
    { to: '/modules/guoyun', label: '国运推演 · GY-01', note: 'S7 人口替罪羊压力 ↔ 人口螺旋。' },
    { to: '/demographic', label: '人口结构 · 少子化', note: '生育率危机与非生育取向污名压力的宏观语境。' },
    { to: '/healthcare', label: '医疗医保 · 公共卫生', note: 'S6 防艾飞地与 MSM 防控的公共卫生接口。' },
  ],
  linggong: [
    { to: '/modules/qingnian', label: '青年 · GY-03 子集 I', note: 'L1/L2 冰河期汇流，CH-02/CH-03 与 L3/L4/L5 三处咬合。' },
    { to: '/modules/qingnian?tab=ch02', label: 'GY-03 CH-02 · 冰河期对照', note: '2020 新就业形态 = 1995 日经连报告，非正规化许可证同构。' },
    { to: '/modules/qingnian?tab=ch03', label: 'GY-03 CH-03 · 公平语法', note: 'L3 算法雇主是公平语法最大燃料库。' },
    { to: '/modules/xingshaoshu', label: '性少数 · GY-04 子集 II', note: 'L8/L9 风险源/风险汇方法论，唯一双重身份人群。' },
    { to: '/modules/guoyun', label: '国运推演 · GY-01', note: 'L8 变量 A 压力测试问二（增长与就业脱钩）最先兑现现场。' },
    { to: '/modules/yishixingtai', label: '合法性机器 · GY-02', note: 'L6 陈国江案是基岩对自组织无差别恐惧的最干净实证。' },
    { to: '/gig', label: '零工经济 · 业态总览', note: '蓄水池与算法治理的系统级业态档案。' },
  ],
  yishixingtai: [
    { to: '/modules/guoyun', label: '国运推演 · GY-01', note: '三变量 × 四情景推演，张力层与观测哨年度对账联动。' },
    { to: '/modules/guoyun?panel=p-tuiyan&scenario=down', label: '情景三 · 日本化加深', note: '与张力 T-03 直接耦合的推演情景。' },
    { to: '/powerlogic', label: '权力逻辑 · 儒表法里', note: '合法性机器的制度底层与统治成本。' },
    { to: '/ideology', label: '意识形态 · 理论透镜', note: '自由主义 / 马克思等对照阅读。' },
  ],
};

export function getCrossLinks(moduleId) {
  return MAP[moduleId] || [];
}

export default MAP;
