// 大事记数据 —— 公开史实策展（教科书/白皮书口径），用于长周期结构分析。
// 口径说明：以制度/经济/科技/外交/社会结构里程碑为主线，客观百科表述；
// 曲折探索期事件按官方决议与教科书表述克制带过，不展开评价。
// 字段契约：ERAS { id, range, label, accent, summary } / DOMAINS { id, label, accent }
//          EVENTS { y, domain, title(≤14字), desc(≤56字), w(1|2|3), to(可选模块路由) } 按 y 升序

export const AS_OF = '2026-06-11';

export const ERAS = [
  { id: 'founding', range: [1949, 1957], label: '建国奠基', accent: '#c41e3a', summary: '开国奠基与制度移植：一五计划立起工业骨架，三大改造确立计划体制' },
  { id: 'winding', range: [1958, 1977], label: '曲折探索', accent: '#64748b', summary: '探索代价高昂：大跃进与文革打断积累，两弹一星为后续保留火种' },
  { id: 'reform', range: [1978, 1991], label: '改革开放', accent: '#10b981', summary: '放权让利换增长：承包制与特区试验撕开计划铁幕，短缺经济步入尾声' },
  { id: 'market', range: [1992, 2001], label: '市场化与全球化', accent: '#22d3ee', summary: '南方谈话定调：分税制、房改、国企攻坚落地，入世接入全球分工' },
  { id: 'boom', range: [2002, 2012], label: '高速增长', accent: '#e8a317', summary: '全球化红利兑现：世界工厂、城镇化与地产共振，总量跃居世界第二' },
  { id: 'newera', range: [2013, 2020], label: '新时代', accent: '#8b5cf6', summary: '动能切换：全面深改、供给侧与脱贫并进，中美博弈开启，疫情收尾' },
  { id: 'rivalry', range: [2021, 2026], label: '战略相持', accent: '#fb923c', summary: '相持攻坚：人口拐点、地产出清与科技封锁三重压力下押注新质生产力' },
];

export const DOMAINS = [
  { id: 'politics', label: '制度政治', accent: '#c41e3a' },
  { id: 'economy', label: '经济产业', accent: '#22d3ee' },
  { id: 'tech', label: '科技工程', accent: '#8b5cf6' },
  { id: 'diplomacy', label: '外交军事', accent: '#e8a317' },
  { id: 'society', label: '社会民生', accent: '#10b981' },
  { id: 'world', label: '外部环境', accent: '#64748b' },
];

export const EVENTS = [
  { y: 1949, domain: 'politics', title: '中华人民共和国成立', desc: '十月一日开国大典，大陆政权更替完成，现代国家建构与工业化议程同时启动。', w: 3 },
  { y: 1950, domain: 'society', title: '土地改革', desc: '《土地改革法》颁布，三亿农民分得土地，乡村旧秩序瓦解，政权完成基层渗透。', w: 2, to: '/rural' },
  { y: 1950, domain: 'diplomacy', title: '抗美援朝出兵', desc: '志愿军跨过鸭绿江，以巨大代价换取东北亚缓冲与国际地位，中美对抗格局成形。', w: 2, to: '/military' },
  { y: 1953, domain: 'economy', title: '一五计划启动', desc: '苏联援建156项工程铺开，重工业优先战略确立，计划经济体制随之成形。', w: 3 },
  { y: 1953, domain: 'world', title: '朝鲜停战协定', desc: '板门店停战，半岛分治固化，中国安全环境阶段性稳定，与西方的隔绝亦随之加深。', w: 2 },
  { y: 1954, domain: 'politics', title: '五四宪法颁布', desc: '第一届全国人大召开，首部宪法确立人民代表大会制度，国家政体框架定型。', w: 2 },
  { y: 1955, domain: 'diplomacy', title: '万隆会议', desc: '提出求同存异，和平共处五项原则走向世界，第三世界外交支点确立。', w: 2, to: '/diplomacy' },
  { y: 1956, domain: 'politics', title: '三大改造完成', desc: '农业、手工业与资本主义工商业完成社会主义改造，单一公有制经济格局确立。', w: 2 },
  { y: 1956, domain: 'tech', title: '十二年科技规划', desc: '科学技术发展远景规划出台，原子能、导弹、计算机等尖端领域定向布局。', w: 1 },
  { y: 1958, domain: 'economy', title: '大跃进运动', desc: '高指标与浮夸风导致国民经济比例严重失调，随后进入三年困难时期。', w: 2 },
  { y: 1958, domain: 'society', title: '户籍制度建立', desc: '《户口登记条例》施行，城乡二元结构制度化，人口流动管制延续数十年。', w: 2, to: '/urban' },
  { y: 1960, domain: 'world', title: '中苏关系破裂', desc: '苏联单方面撤走在华专家、撕毁合同，外援中断倒逼自力更生路线。', w: 2 },
  { y: 1964, domain: 'tech', title: '第一颗原子弹', desc: '罗布泊核试验成功，打破核垄断，大国安全底牌与国际话语权由此奠基。', w: 3, to: '/military' },
  { y: 1964, domain: 'diplomacy', title: '中法建交', desc: '西方大国中首个与新中国建交，冷战铁幕撕开缺口，外交孤立开始松动。', w: 1, to: '/diplomacy' },
  { y: 1966, domain: 'politics', title: '文化大革命开始', desc: '持续十年的全局性内乱开始，1981年历史决议对其作出彻底否定的结论。', w: 2 },
  { y: 1967, domain: 'tech', title: '氢弹试验成功', desc: '从原子弹到氢弹仅用两年八个月，速度居各核国家之首，核威慑体系成型。', w: 1, to: '/military' },
  { y: 1970, domain: 'tech', title: '东方红一号上天', desc: '首颗人造卫星入轨，两弹一星工程收官，航天工业体系的起点确立。', w: 3, to: '/space' },
  { y: 1971, domain: 'diplomacy', title: '恢复联合国席位', desc: '第26届联大恢复中华人民共和国合法席位，重返国际体系的制度入口打开。', w: 3, to: '/diplomacy' },
  { y: 1971, domain: 'world', title: '布雷顿森林解体', desc: '美元与黄金脱钩，信用货币时代开启，全球资本流动为日后开放提供水位。', w: 1 },
  { y: 1972, domain: 'diplomacy', title: '尼克松访华', desc: '中美关系破冰，《上海公报》发表，冷战格局重组，对外开放的地缘前提奠定。', w: 3, to: '/diplomacy' },
  { y: 1973, domain: 'tech', title: '杂交水稻育成', desc: '袁隆平团队籼型杂交水稻三系配套成功，粮食单产跃升，吃饭问题获技术解。', w: 2, to: '/food-security' },
  { y: 1976, domain: 'politics', title: '文革结束', desc: '粉碎"四人帮"，十年内乱终结，国家工作重心转移的政治前提形成。', w: 2 },
  { y: 1977, domain: 'society', title: '恢复高考', desc: '中断十年的高考恢复，570万人报考，人才断层开始修复，知识重获定价。', w: 3, to: '/education' },
  { y: 1978, domain: 'politics', title: '十一届三中全会', desc: '工作重心转向经济建设，改革开放成为基本国策，当代中国命运的总开关扳动。', w: 3, to: '/reform' },
  { y: 1979, domain: 'diplomacy', title: '中美建交', desc: '中美正式建立外交关系，融入美国主导经济体系的战略窗口期开启。', w: 2, to: '/diplomacy' },
  { y: 1980, domain: 'economy', title: '设立经济特区', desc: '深圳、珠海、汕头、厦门四特区设立，体制外试验田开张，增量改革范式确立。', w: 3, to: '/reform' },
  { y: 1980, domain: 'society', title: '独生子女政策', desc: '计划生育收紧为一胎化并延续35年，人口结构深远改变，老龄化伏笔埋下。', w: 2, to: '/demographic' },
  { y: 1982, domain: 'politics', title: '八二宪法颁布', desc: '现行宪法通过，国家机构与权利框架重建，此后历次修宪皆以此为基。', w: 1 },
  { y: 1982, domain: 'economy', title: '包产到户定局', desc: '中央一号文件确认家庭联产承包责任制，集体化退场，农业产出连年跃升。', w: 2, to: '/rural' },
  { y: 1984, domain: 'economy', title: '城市改革启动', desc: '十二届三中全会提出有计划的商品经济，改革重心由农村转向城市与国企。', w: 2, to: '/reform' },
  { y: 1984, domain: 'diplomacy', title: '中英联合声明', desc: '确认1997年对香港恢复行使主权，一国两制由构想进入实施轨道。', w: 1 },
  { y: 1985, domain: 'world', title: '广场协议', desc: '五国联手促美元贬值，日元升值催生泡沫，为中国汇率政策提供长期镜鉴。', w: 1 },
  { y: 1986, domain: 'tech', title: '863计划启动', desc: '四位科学家上书获批，高技术研究发展计划实施，追踪世界前沿的国家队组建。', w: 2 },
  { y: 1986, domain: 'society', title: '义务教育法', desc: '九年义务教育入法，基础教育普及提速，人口红利向人力资本转化的起点。', w: 1, to: '/education' },
  { y: 1990, domain: 'economy', title: '沪深交易所成立', desc: '上海、深圳证券交易所相继开业，资本市场从无到有，股份制改革获得出口。', w: 2 },
  { y: 1991, domain: 'world', title: '苏联解体', desc: '超级大国一夜解体，冷战终结，阵营崩塌反向坚定中国渐进改革路线。', w: 3 },
  { y: 1992, domain: 'politics', title: '南方谈话', desc: '邓小平南巡定调发展是硬道理，市场化改革重新提速，姓社姓资争论终结。', w: 3, to: '/reform' },
  { y: 1993, domain: 'politics', title: '市场经济入宪', desc: '修宪确立社会主义市场经济体制，十四届三中全会绘出市场化改革总图。', w: 1 },
  { y: 1994, domain: 'economy', title: '分税制改革', desc: '财权上收事权留地，央地财政关系重构，土地财政伏笔由此埋下。', w: 3, to: '/reform' },
  { y: 1994, domain: 'tech', title: '接入国际互联网', desc: '实现与国际互联网全功能连接，信息化浪潮入华，数字经济的种子落地。', w: 2 },
  { y: 1997, domain: 'politics', title: '香港回归', desc: '恢复对香港行使主权，一国两制落地，并获得联通世界的离岸金融窗口。', w: 2 },
  { y: 1997, domain: 'world', title: '亚洲金融危机', desc: '东南亚货币体系连环崩溃，中国坚持人民币不贬值，区域信用与教训并得。', w: 2 },
  { y: 1998, domain: 'economy', title: '住房制度改革', desc: '福利分房终止，住宅商品化启动，地产引擎点火，居民财富与债务同步扩张。', w: 3, to: '/housing' },
  { y: 1998, domain: 'economy', title: '国企三年脱困', desc: '抓大放小推进，数千万职工下岗分流，国有经济布局收缩与重组并存。', w: 2, to: '/soe' },
  { y: 1999, domain: 'politics', title: '澳门回归', desc: '恢复对澳门行使主权，港澳问题收官，国家统一议程剩台湾一题。', w: 1 },
  { y: 1999, domain: 'diplomacy', title: '驻南使馆被炸', desc: '北约导弹击中驻南联盟使馆，三名记者罹难，对美认知转折，国防现代化提速。', w: 2, to: '/military' },
  { y: 1999, domain: 'society', title: '高校扩招', desc: '高校大扩招启动，毛入学率十年数倍增长，工程师红利与学历通胀同时酝酿。', w: 2, to: '/education' },
  { y: 2001, domain: 'economy', title: '加入世贸组织', desc: '15年谈判收官，中国接入全球分工体系，世界工厂时代开启，出口爆发增长。', w: 3, to: '/foreign-trade' },
  { y: 2001, domain: 'world', title: '911事件', desc: '美国本土遭恐袭，反恐成华盛顿首要议程，中国获得约十年战略机遇窗口。', w: 2 },
  { y: 2001, domain: 'diplomacy', title: '上合组织成立', desc: '中俄主导的区域安全组织在上海成立，周边稳定与能源通道获得制度抓手。', w: 1, to: '/diplomacy' },
  { y: 2003, domain: 'tech', title: '神舟五号载人', desc: '杨利伟绕地飞行，中国成为第三个独立载人航天国家，航天工程体系成熟。', w: 3, to: '/space' },
  { y: 2003, domain: 'society', title: '非典疫情', desc: 'SARS暴发暴露公共卫生短板，信息披露与疾控体系随后重建。', w: 2 },
  { y: 2004, domain: 'politics', title: '私产入宪', desc: '修宪写入公民合法私有财产不受侵犯，民营经济获得宪法层面确认。', w: 1, to: '/private' },
  { y: 2005, domain: 'diplomacy', title: '反分裂国家法', desc: '以法律形式划定台海红线，明确非和平方式的适用条件，威慑制度化。', w: 2, to: '/straits' },
  { y: 2006, domain: 'society', title: '取消农业税', desc: '延续两千六百年的皇粮国税终结，工业反哺农业转向，城乡关系换挡。', w: 2, to: '/rural' },
  { y: 2008, domain: 'society', title: '汶川地震', desc: '8.0级强震逝者近七万，举国动员救灾重建，应急体系与社会韧性经受大考。', w: 2 },
  { y: 2008, domain: 'society', title: '北京奥运会', desc: '百年奥运梦想兑现，国家动员能力全球展示，民族自信心进入新区间。', w: 2 },
  { y: 2008, domain: 'tech', title: '高铁时代开启', desc: '京津城际开通运营，此后十余年建成全球最大高铁网，国土空间被重新压缩。', w: 2 },
  { y: 2008, domain: 'world', title: '全球金融危机', desc: '雷曼倒闭引爆系统性危机，西方模式光环褪色，全球经济重心加速东移。', w: 3 },
  { y: 2008, domain: 'economy', title: '四万亿计划', desc: '应对危机推出大规模刺激，增长保住而杠杆高企，地方债务与产能过剩埋雷。', w: 2 },
  { y: 2010, domain: 'economy', title: 'GDP超越日本', desc: '经济总量跃居世界第二，百年追赶完成关键一跃，中美双极格局浮现。', w: 2 },
  { y: 2011, domain: 'society', title: '城镇化率过半', desc: '城镇人口首超农村，千年农业国转身，土地财政与市民化矛盾同步显形。', w: 2, to: '/urban' },
  { y: 2012, domain: 'politics', title: '十八大召开', desc: '领导集体换届，八项规定随后出台，从严治党重塑政治生态。', w: 2 },
  { y: 2012, domain: 'diplomacy', title: '辽宁舰入列', desc: '首艘航母服役，海军由近海防御转向远海护卫，蓝水海军建设起步。', w: 2, to: '/military' },
  { y: 2013, domain: 'diplomacy', title: '一带一路倡议', desc: '丝路经济带与海上丝路倡议提出，产能、资本与基建出海获得总框架。', w: 3, to: '/bri' },
  { y: 2013, domain: 'politics', title: '全面深化改革', desc: '十八届三中全会部署336项改革，市场决定性作用写入决议。', w: 2, to: '/reform' },
  { y: 2014, domain: 'tech', title: '集成电路大基金', desc: '国家大基金一期成立，千亿资本注入芯片产业，国产替代长征启动。', w: 1, to: '/semiconductor' },
  { y: 2015, domain: 'economy', title: '供给侧改革', desc: '三去一降一补开局，去产能去库存重塑工业格局，增长逻辑由量转质。', w: 2, to: '/reform' },
  { y: 2015, domain: 'diplomacy', title: '国防军队改革', desc: '成立五大战区与火箭军，军委管总、战区主战，建国以来最深层军改落地。', w: 2, to: '/military' },
  { y: 2015, domain: 'society', title: '全面二孩', desc: '独生子女政策终结，生育限制松绑，但出生人口冲高回落，低生育率固化。', w: 1, to: '/demographic' },
  { y: 2015, domain: 'tech', title: '屠呦呦获诺奖', desc: '青蒿素研究获诺贝尔生理学或医学奖，本土科研首获诺贝尔科学奖项。', w: 1 },
  { y: 2016, domain: 'economy', title: '人民币入SDR', desc: '人民币纳入特别提款权货币篮子，国际化里程碑，但资本项开放仍谨慎。', w: 1, to: '/rmb' },
  { y: 2016, domain: 'diplomacy', title: '亚投行开业', desc: '57国创始成员的多边开发银行开业，战后首个中国主导的国际金融机构。', w: 1, to: '/bri' },
  { y: 2016, domain: 'world', title: '逆全球化转折', desc: '英国脱欧与特朗普当选叠加，自由贸易共识破裂，全球化进入退潮周期。', w: 1 },
  { y: 2017, domain: 'politics', title: '十九大召开', desc: '新时代与主要矛盾转化论断提出，两个一百年路线图细化为两步走。', w: 2 },
  { y: 2018, domain: 'world', title: '中美贸易战', desc: '美国对华加征关税，科技与贸易战并行，四十年接触政策终结，脱钩开场。', w: 3, to: '/foreign-trade' },
  { y: 2019, domain: 'tech', title: '5G商用启动', desc: '运营商获发牌照，全球最大5G网络铺开，同年华为遭实体清单制裁。', w: 2, to: '/semiconductor' },
  { y: 2020, domain: 'society', title: '新冠疫情暴发', desc: '武汉封城，举国动员防控，三年常态化防疫改变经济与社会运行轨迹。', w: 3 },
  { y: 2020, domain: 'society', title: '脱贫攻坚收官', desc: '现行标准下9899万农村贫困人口全部脱贫，绝对贫困历史性消除。', w: 2, to: '/rural' },
  { y: 2020, domain: 'economy', title: '三道红线出台', desc: '房企融资监管收紧，高杠杆模式终结，地产长周期下行由此开闸。', w: 2, to: '/housing' },
  { y: 2020, domain: 'tech', title: '北斗全球组网', desc: '北斗三号全球系统建成开通，导航授时摆脱GPS依赖，时空基础设施自主。', w: 2, to: '/space' },
  { y: 2020, domain: 'world', title: '疫情全球大流行', desc: '新冠席卷全球，供应链断裂与货币大放水并行，各国内顾倾向加深。', w: 2 },
  { y: 2020, domain: 'politics', title: '香港国安法', desc: '全国人大立法在港实施，修例风波后秩序重建，一国两制进入新阶段。', w: 2 },
  { y: 2021, domain: 'politics', title: '建党百年', desc: '宣告全面建成小康社会，第一个百年目标收官，共同富裕议程升温。', w: 1 },
  { y: 2021, domain: 'economy', title: '双碳目标落地', desc: '碳达峰碳中和写入顶层设计，能源结构转型定调，新能源产业获长期锚。', w: 2, to: '/energy' },
  { y: 2021, domain: 'society', title: '双减政策', desc: '校外学科培训全面压减，教培行业急刹车，教育内卷治理首役。', w: 1, to: '/education' },
  { y: 2021, domain: 'tech', title: '天问一号落火', desc: '首次火星探测实现绕落巡一次成功，深空探测三步并作一步。', w: 1, to: '/space' },
  { y: 2022, domain: 'politics', title: '二十大召开', desc: '中国式现代化成为总纲领，安全与发展并重，强国建设进入施工期。', w: 3 },
  { y: 2022, domain: 'society', title: '人口负增长', desc: '全国人口61年来首次负增长，劳动力长周期收缩开启，增长模型被迫改写。', w: 3, to: '/demographic' },
  { y: 2022, domain: 'world', title: '乌克兰危机升级', desc: '俄乌爆发全面冲突，欧洲安全秩序重构，阵营化与能源重组冲击全球。', w: 3 },
  { y: 2022, domain: 'world', title: 'ChatGPT问世', desc: '生成式AI引爆全球，算力成为战略资源，新一轮通用技术革命开闸。', w: 2, to: '/aiplus' },
  { y: 2022, domain: 'world', title: '美国芯片管制', desc: '美国出台对华先进制程全面出口管制，科技战升级，倒逼全链条国产化。', w: 2, to: '/semiconductor' },
  { y: 2022, domain: 'tech', title: '中国空间站建成', desc: '天宫空间站三舱合体完成在轨建造，长期有人驻留，太空基建自主闭环。', w: 2, to: '/space' },
  { y: 2022, domain: 'diplomacy', title: '环台军事演习', desc: '美国会众议长访台后解放军环台演习，台海军事化程度抬升，现状趋于脆弱。', w: 2, to: '/straits' },
  { y: 2023, domain: 'tech', title: '大模型集中爆发', desc: '百模大战开打，国产大模型密集发布，AI竞赛从应用层卷向基础层。', w: 2, to: '/aiplus' },
  { y: 2023, domain: 'tech', title: 'C919商业首航', desc: '国产大飞机投入商业运营，民航制造打破波音空客双寡头的缺口出现。', w: 2 },
  { y: 2023, domain: 'economy', title: '汽车出口第一', desc: '整车出口超日本跃居全球第一，新能源车产业链优势兑现为贸易格局。', w: 2, to: '/automotive' },
  { y: 2023, domain: 'diplomacy', title: '沙伊北京和解', desc: '斡旋沙特伊朗复交，中东出现后美国时代信号，安全公共品输出首秀。', w: 2, to: '/diplomacy' },
  { y: 2024, domain: 'economy', title: '新质生产力', desc: '新质生产力写入政府工作报告，要素逻辑从规模扩张转向全要素生产率。', w: 2, to: '/policydocs' },
  { y: 2024, domain: 'world', title: '特朗普再当选', desc: '特朗普重返白宫，关税与单边主义回归，中美博弈进入第二回合。', w: 2 },
  { y: 2024, domain: 'tech', title: '嫦娥六号采样', desc: '人类首次月球背面采样返回，深空探测能力进入第一梯队。', w: 1, to: '/space' },
  { y: 2025, domain: 'tech', title: 'DeepSeek时刻', desc: 'DeepSeek以低成本逼近顶尖模型性能，AI竞争叙事改写，开源路线抬头。', w: 2, to: '/aiplus' },
  { y: 2025, domain: 'world', title: '对等关税冲击', desc: '美国对全球加征对等关税，中美税率螺旋后谈判降温，贸易体系碎片化。', w: 2, to: '/foreign-trade' },
  { y: 2025, domain: 'economy', title: '十四五收官', desc: '十四五规划收官，制造业占比与研发强度达标，地产与人口压力转入下程。', w: 1, to: '/policydocs' },
  { y: 2025, domain: 'diplomacy', title: '九三阅兵', desc: '抗战胜利80周年阅兵，新型装备集中亮相，威慑展示与历史叙事并举。', w: 1, to: '/military' },
  { y: 2026, domain: 'economy', title: '十五五开局', desc: '十五五规划启动实施，科技自立自强与扩大内需双主线，相持期攻坚开局。', w: 2, to: '/policydocs' },
];
