// =====================================================================
import { AS_OF_BASELINE } from '../../lib/config/asOfBaseline.js';
// 瞭望塔 · 指标目录
// 监测台口径 = 各专题模块判读基准的聚合镜像（示意，非实时数据源）。
// 读数与各专题模块 2026-06 判读基准对齐，全部为公开口径示意值；
// 档位（warm/hold/cool）表达的是系统状态判读，不是预测。
// =====================================================================


export const AS_OF = AS_OF_BASELINE;

export const LEVELS = {
  warm: { label: '常态/向好', color: '#10b981' },
  hold: { label: '管控/僵持', color: '#e8a317' },
  cool: { label: '告警/恶化', color: '#c41e3a' },
};

export const DOMAINS = [
  { id: 'diplomacy', label: '外交安全', icon: 'Globe2', accent: '#c41e3a' },
  { id: 'economy', label: '宏观经济', icon: 'TrendingUp', accent: '#22d3ee' },
  { id: 'tech', label: '科技自立', icon: 'Cpu', accent: '#8b5cf6' },
  { id: 'energy', label: '能源资源', icon: 'Zap', accent: '#e8a317' },
  { id: 'society', label: '社会民生', icon: 'Users', accent: '#10b981' },
  { id: 'structure', label: '结构风险', icon: 'ShieldAlert', accent: '#fb923c' },
];

export const INDICATORS = [
  // ============================ 外交安全 ============================
  {
    id: 'dip-us-channel',
    domain: 'diplomacy',
    name: '中美元首沟通',
    sub: '战略沟通渠道温度',
    level: 'hold',
    reading: '热线维持·高层互访停滞',
    trend: '→',
    note: '渠道未断即护栏仍在；沟通频度决定误判概率。',
    bands: {
      warm: '元首互访+机制化对话',
      hold: '热线维持·事务级接触',
      cool: '渠道中断·隔空喊话',
    },
    to: '/diplomacy',
    src: '大国外交',
  },
  {
    id: 'dip-strait-mil',
    domain: 'diplomacy',
    name: '台海军事活动',
    sub: '绕台与越线频度',
    level: 'hold',
    reading: '常态化巡航·月均逾百架次',
    trend: '→',
    note: '高压成为新常态；常态本身就是变量的积累。',
    bands: {
      warm: '活动降频·默契恢复',
      hold: '常态化巡航施压',
      cool: '封控演训·抵近对峙',
    },
    to: '/straits',
    src: '台海推演',
  },
  {
    id: 'dip-eu-friction',
    domain: 'diplomacy',
    name: '中欧经贸摩擦',
    sub: '关税与反补贴扩围',
    level: 'cool',
    reading: '电动车关税+调查扩围',
    trend: '↑',
    note: '欧洲对冲加速；第二战线正在固化为结构。',
    bands: {
      warm: '关税回调·谈判解决',
      hold: '个案摩擦·谈判并行',
      cool: '关税扩围·体系对立',
    },
    to: '/foreign-trade',
    src: '外贸格局',
  },
  {
    id: 'dip-dprk-anchor',
    domain: 'diplomacy',
    name: '中朝再锚定',
    sub: '半岛支点修复进度',
    level: 'warm',
    reading: '高层互动恢复·边贸回温',
    trend: '↑',
    note: '缓冲带价值随大棋局升水；支点重新上桩。',
    bands: {
      warm: '高层互访·经援恢复',
      hold: '关系冷淡·渠道维持',
      cool: '平壤倒向单边押注',
    },
    to: '/diplomacy',
    src: '大国外交',
  },
  {
    id: 'dip-scs-friction',
    domain: 'diplomacy',
    name: '南海摩擦频度',
    sub: '仁爱礁/黄岩岛对峙',
    level: 'hold',
    reading: '补给对峙间歇化·未升级',
    trend: '→',
    note: '灰色地带的摩擦由节奏管理，不由意愿决定。',
    bands: {
      warm: '摩擦降温·准则推进',
      hold: '对峙间歇化·可控',
      cool: '撞船伤亡·条约触发',
    },
    to: '/military',
    src: '军事力量',
  },
  {
    id: 'dip-ukraine-spill',
    domain: 'diplomacy',
    name: '乌战外溢敞口',
    sub: '次级制裁传导风险',
    level: 'hold',
    reading: '次级制裁威胁悬置',
    trend: '→',
    note: '不下场即筹码；外溢风险取决于战场而非北京。',
    bands: {
      warm: '停火落地·敞口收敛',
      hold: '制裁威胁悬而未落',
      cool: '次级制裁实质落地',
    },
    to: '/omnisecurity',
    src: '总体安全',
  },

  // ============================ 宏观经济 ============================
  {
    id: 'eco-gdp-pace',
    domain: 'economy',
    name: 'GDP 目标进度',
    sub: '全年 5% 左右达标线',
    level: 'hold',
    reading: 'Q1 同比 5.0%·贴线运行',
    trend: '→',
    note: '增长靠政策托底而非内生动能；油门不敢松。',
    bands: {
      warm: '内生动能接棒·超 5%',
      hold: '政策托底·贴线达标',
      cool: '失速破 4.5%·被迫强刺激',
    },
    to: '/policydocs',
    src: '政策文库',
  },
  {
    id: 'eco-urban-unemp',
    domain: 'economy',
    name: '城镇调查失业率',
    sub: '统计口径内就业水位',
    level: 'hold',
    reading: '5.1%·口径内平稳',
    trend: '→',
    note: '口径内的平稳，掩盖口径外的灵活就业蓄水池。',
    bands: {
      warm: '降至 5% 下·结构改善',
      hold: '5%-5.5% 区间震荡',
      cool: '破 5.5%·外溢可见',
    },
    to: '/gig',
    src: '零工经济',
  },
  {
    id: 'eco-cpi',
    domain: 'economy',
    name: 'CPI 同比',
    sub: '低通胀/通缩预期',
    level: 'cool',
    reading: '+0.2%·贴地飞行',
    trend: '↓',
    note: '低通胀是需求不足的体温计；预期一旦自证即难逆。',
    bands: {
      warm: '回到 1%-2% 温和区间',
      hold: '0.5%-1%·弱回升',
      cool: '0 附近徘徊·通缩自证',
    },
    to: '/finance-system',
    src: '金融体系',
  },
  {
    id: 'eco-leverage',
    domain: 'economy',
    name: '宏观杠杆率',
    sub: '全社会债务/GDP',
    level: 'cool',
    reading: '~298%·仍在爬坡',
    trend: '↑',
    note: '置换只改变债主，不改变债务总量的物理。',
    bands: {
      warm: '增速放缓·名义增长消化',
      hold: '高位企稳·结构腾挪',
      cool: '逼近 300%·被动加杠杆',
    },
    to: '/debt',
    src: '债务化解',
  },
  {
    id: 'eco-private-inv',
    domain: 'economy',
    name: '民间投资增速',
    sub: '民营资本风险偏好',
    level: 'cool',
    reading: '同比约 -0.5%·连续承压',
    trend: '↓',
    note: '民间资本用脚投票；信心不是文件能签发的。',
    bands: {
      warm: '转正回升·扩表重启',
      hold: '0 附近·观望僵持',
      cool: '负增长·收缩自我强化',
    },
    to: '/private',
    src: '民营经济',
  },
  {
    id: 'eco-export',
    domain: 'economy',
    name: '出口增速',
    sub: '新三样与转口韧性',
    level: 'warm',
    reading: '新三样拉动·同比 +6%',
    trend: '↑',
    note: '出口是当前最硬的引擎；转速却握在对岸关税手里。',
    bands: {
      warm: '5% 上·份额保持',
      hold: '0-5%·靠抢出口续命',
      cool: '负增长·关税墙合围',
    },
    to: '/foreign-trade',
    src: '外贸格局',
  },

  // ============================ 科技自立 ============================
  {
    id: 'tech-node',
    domain: 'tech',
    name: '先进制程突破',
    sub: 'DUV 多重曝光极限',
    level: 'hold',
    reading: '7nm 良率爬坡·5nm 试产',
    trend: '↑',
    note: '物理极限前的逼近赛；良率每一个点都是产能。',
    bands: {
      warm: '5nm 量产·良率过线',
      hold: '7nm 爬坡·成本高企',
      cool: '设备禁运升级·停滞',
    },
    to: '/semiconductor',
    src: '半导体',
  },
  {
    id: 'tech-compute',
    domain: 'tech',
    name: 'AI 算力供给',
    sub: '高端训练卡缺口',
    level: 'cool',
    reading: '高端 GPU 缺口 ~40%',
    trend: '↑',
    note: '算力即权力；缺口决定大模型代差的下限。',
    bands: {
      warm: '国产卡顶上·缺口收敛',
      hold: '缺口僵持·集群优化补',
      cool: '缺口扩大·代差拉开',
    },
    to: '/computing',
    src: '算力网络',
  },
  {
    id: 'tech-bigfund3',
    domain: 'tech',
    name: '大基金三期落地',
    sub: '3440 亿投放节奏',
    level: 'warm',
    reading: '投放加速·设备材料倾斜',
    trend: '↑',
    note: '国家资本压向最窄的瓶颈；方向比金额重要。',
    bands: {
      warm: '投放过半·瓶颈环节聚焦',
      hold: '投放迟缓·撒胡椒面',
      cool: '项目暴雷·问责冻结',
    },
    to: '/semiconductor',
    src: '半导体',
  },
  {
    id: 'tech-eda-material',
    domain: 'tech',
    name: 'EDA/材料国产化',
    sub: '卡脖子清单消化度',
    level: 'hold',
    reading: '28nm 全流程贯通·先进受限',
    trend: '↑',
    note: '成熟制程已闭环；先进环节仍握在别人手里。',
    bands: {
      warm: '14nm 链路贯通',
      hold: '28nm 闭环·先进依赖',
      cool: '断供扩至成熟制程',
    },
    to: '/semiconductor',
    src: '半导体',
  },
  {
    id: 'tech-patent',
    domain: 'tech',
    name: '专利质量指数',
    sub: 'PCT 与高被引占比',
    level: 'hold',
    reading: '数量第一·引用质量爬坡',
    trend: '↑',
    note: '数量是面子，被引是里子；里子在缓慢变厚。',
    bands: {
      warm: '高被引占比追平美日',
      hold: '量大质升·梯度爬坡',
      cool: '灌水反弹·质量倒退',
    },
    to: '/talent',
    src: '人才战略',
  },
  {
    id: 'tech-humanoid',
    domain: 'tech',
    name: '人形机器人量产',
    sub: '具身智能产业化',
    level: 'warm',
    reading: '头部厂商千台级交付',
    trend: '↑',
    note: '供应链复用电车红利；这一仗打的是成本曲线。',
    bands: {
      warm: '千台级交付·成本下行',
      hold: '小批量示范·场景受限',
      cool: '融资退潮·量产证伪',
    },
    to: '/robotics',
    src: '机器人',
  },

  // ============================ 能源资源 ============================
  {
    id: 'eng-oil-dep',
    domain: 'energy',
    name: '原油对外依存',
    sub: '海运通道脆弱性',
    level: 'cool',
    reading: '~72%·海运咽喉未解',
    trend: '→',
    note: '马六甲仍是悬在工业血管上的阀门。',
    bands: {
      warm: '降至 65% 下·管道替代',
      hold: '70% 附近·储备对冲',
      cool: '72%+ 高位·通道受制',
    },
    to: '/energy',
    src: '能源安全',
  },
  {
    id: 'eng-soy-dep',
    domain: 'energy',
    name: '粮食大豆依存',
    sub: '蛋白与油脂缺口',
    level: 'cool',
    reading: '大豆自给率 ~17%',
    trend: '→',
    note: '蛋白缺口是刚性的；饭碗端稳不等于油瓶在手。',
    bands: {
      warm: '自给率升·多元采购成型',
      hold: '巴西替代·敞口可控',
      cool: '依存 80%+·单一来源',
    },
    to: '/food-security',
    src: '粮食安全',
  },
  {
    id: 'eng-rareearth',
    domain: 'energy',
    name: '稀土反制筹码',
    sub: '上游卡位有效性',
    level: 'warm',
    reading: '出口管制清单扩容',
    trend: '↑',
    note: '上游卡位是少数非对称筹码；用一次贬值一次。',
    bands: {
      warm: '管制有效·替代难成',
      hold: '对手去风险加速',
      cool: '海外供应链闭环成型',
    },
    to: '/resources',
    src: '资源版图',
  },
  {
    id: 'eng-nev',
    domain: 'energy',
    name: '新能源渗透率',
    sub: 'NEV 销量占比',
    level: 'warm',
    reading: 'NEV 渗透率 >50%',
    trend: '↑',
    note: '石油需求达峰提前；交通电气化是战略减敞口。',
    bands: {
      warm: '50%+·替代不可逆',
      hold: '40%-50%·补贴依赖',
      cool: '渗透停滞·油耗反弹',
    },
    to: '/automotive',
    src: '汽车产业',
  },
  {
    id: 'eng-grid',
    domain: 'energy',
    name: '电网消纳率',
    sub: '弃风弃光水位',
    level: 'hold',
    reading: '弃电率回升至 ~5%',
    trend: '↑',
    note: '装机狂奔、电网跟跑；消纳是绿电的真瓶颈。',
    bands: {
      warm: '弃电率 3% 内·储能接力',
      hold: '5% 附近·局部弃电',
      cool: '弃电率破 10%·投资空转',
    },
    to: '/smartgrid',
    src: '智能电网',
  },
  {
    id: 'eng-spr',
    domain: 'energy',
    name: '战略储备天数',
    sub: '原油储备当量',
    level: 'hold',
    reading: '原油储备 ~90 天当量',
    trend: '↑',
    note: '储备买的是谈判时间，不是安全本身。',
    bands: {
      warm: '120 天+·逢低补库',
      hold: '90 天上下·继续扩容',
      cool: '低于 60 天·被动消耗',
    },
    to: '/energy',
    src: '能源安全',
  },

  // ============================ 社会民生 ============================
  {
    id: 'soc-pop-growth',
    domain: 'society',
    name: '人口自然增长',
    sub: '出生-死亡净值',
    level: 'cool',
    reading: '-1.39‰·连续负增长',
    trend: '↓',
    note: '人口是最慢的变量，也是最不可逆的变量。',
    bands: {
      warm: '出生回升·降幅收窄',
      hold: '负增长但斜率平缓',
      cool: '负增长加速·预期固化',
    },
    to: '/demographic',
    src: '人口结构',
  },
  {
    id: 'soc-aging',
    domain: 'society',
    name: '老龄化率',
    sub: '60 岁以上人口占比',
    level: 'cool',
    reading: '60 岁+ 占比 >22%',
    trend: '↑',
    note: '抚养比恶化是确定性事件；窗口只剩适应。',
    bands: {
      warm: '延退+银发经济对冲',
      hold: '渐进式适应推进',
      cool: '占比破 22%·加速爬坡',
    },
    to: '/healthcare',
    src: '医疗健康',
  },
  {
    id: 'soc-youth-job',
    domain: 'society',
    name: '青年就业',
    sub: '16-24 岁失业率',
    level: 'cool',
    reading: '16-24 岁失业率 ~15%',
    trend: '→',
    note: '学历通胀撞上岗位收缩；蓄水池在体外扩容。',
    bands: {
      warm: '降至 12% 下·缺口对接',
      hold: '15% 附近·灵活就业承接',
      cool: '15%+ 高位·预期塌陷',
    },
    to: '/education',
    src: '教育体系',
  },
  {
    id: 'soc-income',
    domain: 'society',
    name: '居民收入增速',
    sub: '可支配收入实际增速',
    level: 'hold',
    reading: '+5.1%·跑平名义 GDP',
    trend: '→',
    note: '收入跑平不等于敢花钱；分配结构决定乘数。',
    bands: {
      warm: '跑赢 GDP·占比回升',
      hold: '跑平·消费倾向偏弱',
      cool: '跑输·预防性储蓄抬头',
    },
    to: '/private',
    src: '民营经济',
  },
  {
    id: 'soc-pension',
    domain: 'society',
    name: '社保基金平衡',
    sub: '养老金统筹收支',
    level: 'hold',
    reading: '全国统筹调剂顶压',
    trend: '→',
    note: '统筹是空间换时间；时间表写在人口曲线里。',
    bands: {
      warm: '国资划转+委托投资增厚',
      hold: '统筹调剂维持平衡',
      cool: '多省穿底·中央兜底',
    },
    to: '/demographic',
    src: '人口结构',
  },
  {
    id: 'soc-housing-price',
    domain: 'society',
    name: '房价止跌企稳',
    sub: '70 城价格指数',
    level: 'hold',
    reading: '一线环比转平·二三线寻底',
    trend: '→',
    note: '价格信号是预期的锚；锚没扎稳就谈不上修复。',
    bands: {
      warm: '一二线同步转正',
      hold: '一线企稳·低线分化',
      cool: '全线续跌·负反馈重启',
    },
    to: '/housing',
    src: '房地产',
  },

  // ============================ 结构风险 ============================
  {
    id: 'str-localdebt',
    domain: 'structure',
    name: '地方债务化解',
    sub: '置换额度执行进度',
    level: 'hold',
    reading: '置换额度过半·付息承压',
    trend: '→',
    note: '化债化的是流动性，偿付能力要靠增长归还。',
    bands: {
      warm: '利息负担实质下降',
      hold: '置换推进·拖中求稳',
      cool: '非标违约扩散·城投破刚兑',
    },
    to: '/debt',
    src: '债务化解',
  },
  {
    id: 'str-developer',
    domain: 'structure',
    name: '房企风险出清',
    sub: '保交楼与白名单',
    level: 'hold',
    reading: '保交楼收尾·白名单续贷',
    trend: '→',
    note: '出清在管道内进行；代价由时间分期摊销。',
    bands: {
      warm: '头部修复·拿地恢复',
      hold: '管道内出清·不外溢',
      cool: '混合所有制房企暴雷',
    },
    to: '/housing',
    src: '房地产',
  },
  {
    id: 'str-smallbank',
    domain: 'structure',
    name: '中小银行风险',
    sub: '高风险机构压降',
    level: 'hold',
    reading: '高风险机构数量压降中',
    trend: '→',
    note: '合并重组是吸收而非消灭；资本金才是底牌。',
    bands: {
      warm: '高风险机构清零过半',
      hold: '合并重组有序推进',
      cool: '区域性挤兑·风险联动',
    },
    to: '/finance-system',
    src: '金融体系',
  },
  {
    id: 'str-capital-flow',
    domain: 'structure',
    name: '资本外流压力',
    sub: '跨境证券与直投',
    level: 'hold',
    reading: '证券项下波动·直投偏弱',
    trend: '→',
    note: '管制闸门有效但有代价；水位差才是根因。',
    bands: {
      warm: '北向回流·FDI 转正',
      hold: '波动可控·闸门起效',
      cool: '持续净流出·储备消耗',
    },
    to: '/fdi',
    src: '外资动向',
  },
  {
    id: 'str-fx',
    domain: 'structure',
    name: '汇率稳定',
    sub: '人民币对美元中枢',
    level: 'warm',
    reading: '7.10 上下·中间价锚定',
    trend: '→',
    note: '汇率是信心的报价；7.1 中枢即管理层底线宣示。',
    bands: {
      warm: '7.1 上下窄幅·预期平',
      hold: '逼近 7.3·逆周期加码',
      cool: '破 7.5·贬值预期自证',
    },
    to: '/rmb',
    src: '人民币',
  },
  {
    id: 'str-reserves',
    domain: 'structure',
    name: '外储规模',
    sub: '外汇储备+黄金',
    level: 'warm',
    reading: '3.2 万亿美元·黄金增持',
    trend: '↑',
    note: '外储是最后的弹药库；黄金占比是去美元注脚。',
    bands: {
      warm: '3.2 万亿稳·黄金增持',
      hold: '3 万亿附近·消耗护盘',
      cool: '快速跌破 3 万亿',
    },
    to: '/rmb',
    src: '人民币',
  },
];

const LEVEL_SCORE = { warm: 90, hold: 60, cool: 30 };

// 域健康分：warm=90 / hold=60 / cool=30 取均值四舍五入，0-100。
export function domainScore(indicators, domainId) {
  const rows = indicators.filter((i) => i.domain === domainId);
  if (!rows.length) return 0;
  const sum = rows.reduce((acc, i) => acc + (LEVEL_SCORE[i.level] ?? 0), 0);
  return Math.round(sum / rows.length);
}
