// 杨光斌 · 思想光谱条目（取自 data.js 已核验条目；无可核验表态的议题留空）
export const STANCES = {
  democracy: {
    stance: '以"可治理的民主"界定中国民主，认为民主的条件比形式更重要，反对以竞争性选举为唯一尺度',
    type: '原话',
    quote: '“可治理的民主”可以说是“全过程人民民主”的一种学理化表达。',
    date: '2026-02',
    venue: '《学术月刊》2026 年第 2 期访谈',
    source: '《学术月刊》（爱思想转载）',
    url: 'https://www.aisixiang.com/data/173547.html',
    verified: 'reprint',
  },
  partyState: {
    stance: '持"政党中心主义"，认为代表人民性的政党是人民民主的关键，民主集中制为其实现机制',
    type: '原话',
    quote: '因此，实现人民民主的关键是能够代表人民性的政党，其实现机制是民主集中制。',
    date: '2019-01',
    venue: '《人民民主：优势、挑战与对策》（与乔哲青合作），《西华大学学报》2019 年第 1 期',
    source: '中国政治学网（中国社会科学网）转载',
    url: 'http://chinaps.cssn.cn/zxcg/202002/t20200204_5084784.shtml',
    verified: 'primary',
  },
  centralLocal: {
    stance: '认为民主集中制贯穿国家机构、央地、政经与国家—社会关系，是理解央地权力关系的枢纽',
    type: '转述',
    date: '2015',
    venue: '《论作为"中国模式"的民主集中制政体》，《政治学研究》2015 年',
    source: '《政治学研究》论文摘要',
    verified: 'primary',
  },
  bureaucracy: {
    stance: '认为科层体系必然伴生官僚主义；早年批评局长竞选等"行政民主"走得过远，违背行政规律',
    type: '原话',
    quote: '哪怕党性和人民性是一致的，也不可能消灭官僚主义。',
    date: '2019-01',
    venue: '《人民民主：优势、挑战与对策》（与乔哲青合作），《西华大学学报》2019 年第 1 期',
    source: '中国政治学网（中国社会科学网）转载',
    url: 'http://chinaps.cssn.cn/zxcg/202002/t20200204_5084784.shtml',
    verified: 'primary',
  },
  legitimacy: {
    stance: '反对把合法性等同于选举授权，主张多维重述，有效性是合法性的最大公约数',
    type: '原话',
    quote: '合法律性、有效性和正义性都能达成共识，其中“有效性”又是合法性的最大公约数，而“人民性”则存在争议',
    date: '2015-12',
    venue: '《不能做"合法性"概念的囚徒》，共识网',
    source: '爱思想转载（2015-12-03）',
    url: 'https://www.aisixiang.com/data/94647.html',
    verified: 'reprint',
  },
  reformPath: {
    stance: '反对把政治制度当作解决社会问题的"原因"去改组，主张以治理能力而非政体变革为改革重心',
    type: '原话',
    quote: '一些国家没有认识到政治制度是其他权力相互作用的结果而非原因',
    date: '2020-02',
    venue: '《衡量国家治理能力的基本指标》，《前线》',
    source: '爱思想转载（2020-02-18）',
    url: 'https://www.aisixiang.com/data/120254.html',
    verified: 'reprint',
  },
};
