// ============================================================================
// 中国政要 · 人大/政协/部委副职/中直机关结构性补全 · 2026-06
// ----------------------------------------------------------------------------
// 政协主席王沪宁、人大委员长赵乐际、政治局常委等见省级库；部委部长见 central 库。
// 来源：十四届全国人大/政协公报、中国政府网任免、部委官网（2023–2026）。
// 生成：scripts/genPoliticalStructureSeed.py
// ============================================================================

import { AS_OF, fig } from './figureCommon.js';

export const FIGURE_POLITICAL_STRUCTURE_META = {
  id: 'political-structure-2026-06',
  asOf: AS_OF,
  label: '人大政协部委中直 · 结构性补全 · 2026-06',
  sources: ['中国人大网', '全国政协网', '中国政府网', '新华网', '部委官网'],
  scope: 'institutionType 四维补全：中直: 33, 人大: 62, 政协: 56, 部委: 57，合计 208',
  notes: '政协文化文史和学习委员会主任吴英杰2024-07去职后暂缺；部委副部长以官网部领导栏目为准',
};

const C = (o) => fig({ province: '中央', ...o });

const R = ({ name, institutionType, institution, org, role, level, title, birth, native, rank, tookOffice, career }) =>
  C({
    name,
    level,
    role,
    sector: institutionType === '政协' ? '全国政协' : institutionType === '人大' ? '国家机关' : institutionType === '部委' ? '国务院' : '党中央',
    org,
    source: `十四届全国人大政协/国务院任免·${tookOffice}`,
    fields: {
      title,
      birth,
      native,
      rank,
      tookOffice,
      institution,
      institutionType,
    },
    career,
  });

export const FIGURE_POLITICAL_STRUCTURE_2026 = [
  R({
    name: '巴音朝鲁',
    institutionType: '人大',
    institution: '全国人大民族委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大民族委员会主任委员',
    birth: '1955年10月',
    native: '内蒙古',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大民族委员会主任委员' }, { from: '2018', to: '2023', desc: '任吉林省人大常委会主任' }, { from: '2013', to: '2018', desc: '任吉林省委书记' }],
  }),
  R({
    name: '信春鹰',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会主任委员',
    birth: '1956年10月',
    native: '陕西渭南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会主任委员' }, { from: '2018', to: '2023', desc: '任全国人大常委会副秘书长' }, { from: '2015', to: '2018', desc: '任全国人大常委会法制工作委员会主任' }],
  }),
  R({
    name: '杨晓超',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大监察和司法委员会主任委员',
    birth: '1957年10月',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会主任委员' }, { from: '2016', to: '2023', desc: '任中央纪委副书记' }, { from: '2014', to: '2016', desc: '任监察部副部长' }],
  }),
  R({
    name: '钟山',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大财政经济委员会主任委员',
    birth: '1954年7月',
    native: '浙江象山',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会主任委员' }, { from: '2018', to: '2023', desc: '任商务部部长' }, { from: '2013', to: '2018', desc: '任商务部副部长' }],
  }),
  R({
    name: '雒树刚',
    institutionType: '人大',
    institution: '全国人大教育科学文化卫生委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大教科文卫委员会主任委员',
    birth: '1958年6月',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大教科文卫委员会主任委员' }, { from: '2018', to: '2023', desc: '任文化和旅游部部长' }, { from: '2016', to: '2018', desc: '任中央宣传部副部长' }],
  }),
  R({
    name: '娄勤俭',
    institutionType: '人大',
    institution: '全国人大外事委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大外事委员会主任委员',
    birth: '1957年12月',
    native: '贵州桐梓',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大外事委员会主任委员' }, { from: '2018', to: '2023', desc: '任江苏省委书记' }, { from: '2013', to: '2018', desc: '任江苏省委副书记、省长' }],
  }),
  R({
    name: '于伟国',
    institutionType: '人大',
    institution: '全国人大华侨委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大华侨委员会主任委员',
    birth: '1953年4月',
    native: '山东文登',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大华侨委员会主任委员' }, { from: '2015', to: '2023', desc: '任福建省委书记' }, { from: '2011', to: '2015', desc: '任福建省委副书记、省长' }],
  }),
  R({
    name: '鹿心社',
    institutionType: '人大',
    institution: '全国人大环境与资源保护委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大环境与资源保护委员会主任委员',
    birth: '1956年11月',
    native: '山东巨野',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大环境与资源保护委员会主任委员' }, { from: '2018', to: '2023', desc: '任江西省委书记' }, { from: '2013', to: '2018', desc: '任江西省委副书记、省长' }],
  }),
  R({
    name: '杜家毫',
    institutionType: '人大',
    institution: '全国人大农业与农村委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大农业与农村委员会主任委员',
    birth: '1952年2月',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大农业与农村委员会主任委员' }, { from: '2018', to: '2023', desc: '任湖南省人大常委会主任' }, { from: '2013', to: '2018', desc: '任湖南省委书记' }],
  }),
  R({
    name: '杨振武',
    institutionType: '人大',
    institution: '全国人大社会建设委员会',
    org: '全国人大常委会',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国人大社会建设委员会主任委员',
    birth: '1955年5月',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大社会建设委员会主任委员' }, { from: '2018', to: '2023', desc: '任人民日报社社长' }, { from: '2014', to: '2018', desc: '任人民日报社总编辑' }],
  }),
  R({
    name: '王志民',
    institutionType: '人大',
    institution: '全国人大民族委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大民族委员会副主任委员',
    birth: '1957年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大民族委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中央统战部副部长' }],
  }),
  R({
    name: '安兆庆',
    institutionType: '人大',
    institution: '全国人大民族委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大民族委员会副主任委员',
    birth: '1958年',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大民族委员会副主任委员' }, { from: '2017', to: '2023', desc: '任新疆军区政治委员' }],
  }),
  R({
    name: '肖开提·依明',
    institutionType: '人大',
    institution: '全国人大民族委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大民族委员会副主任委员',
    birth: '1957年',
    native: '新疆',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大民族委员会副主任委员' }, { from: '2018', to: '2023', desc: '任新疆维吾尔自治区人大常委会主任' }],
  }),
  R({
    name: '黄明',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1960年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2018', to: '2023', desc: '任应急管理部部长' }],
  }),
  R({
    name: '袁曙宏',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1956年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2018', to: '2023', desc: '任国务院副秘书长' }],
  }),
  R({
    name: '沈春耀',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1960年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2018', to: '2023', desc: '任全国人大常委会法制工作委员会主任' }],
  }),
  R({
    name: '何平',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1957年',
    native: '四川',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2017', to: '2023', desc: '任四川省委副书记、省长' }],
  }),
  R({
    name: '丛斌',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1957年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2018', to: '2023', desc: '任九三学社中央常务副主席' }],
  }),
  R({
    name: '徐辉',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1958年',
    native: '浙江',
    rank: '民进中央常务副主席',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2017', to: '2023', desc: '任全国政协副主席' }],
  }),
  R({
    name: '王洪祥',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中央政法委副秘书长' }],
  }),
  R({
    name: '周光权',
    institutionType: '人大',
    institution: '全国人大宪法和法律委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大宪法和法律委员会副主任委员',
    birth: '1968年',
    native: '湖南',
    rank: '无党派',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大宪法和法律委员会副主任委员' }, { from: '2017', to: '2023', desc: '任清华大学法学院院长' }],
  }),
  R({
    name: '邱学强',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1955年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2017', to: '2023', desc: '任中央纪委副书记' }],
  }),
  R({
    name: '张轩',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1960年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2018', to: '2023', desc: '任重庆市人大常委会主任' }],
  }),
  R({
    name: '李钺锋',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1962年',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2018', to: '2023', desc: '任台盟中央常务副主席' }],
  }),
  R({
    name: '王建武',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1962年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2017', to: '2023', desc: '任中央军委政治工作部主任' }],
  }),
  R({
    name: '蒋卓庆',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1959年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2018', to: '2023', desc: '任上海市人大常委会主任' }],
  }),
  R({
    name: '彭金辉',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1963年',
    native: '云南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中国科学院副院长' }],
  }),
  R({
    name: '谷振春',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1963年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2018', to: '2023', desc: '任辽宁省人大常委会副主任' }],
  }),
  R({
    name: '高友东',
    institutionType: '人大',
    institution: '全国人大监察和司法委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大监察和司法委员会副主任委员',
    birth: '1963年',
    native: '河南',
    rank: '民建中央常务副主席',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大监察和司法委员会副主任委员' }, { from: '2017', to: '2023', desc: '任民建中央副主席' }],
  }),
  R({
    name: '郭树清',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1956年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中国人民银行党委书记、银保监会主席' }],
  }),
  R({
    name: '沈金龙',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1956年',
    native: '上海',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2017', to: '2023', desc: '任海军司令员' }],
  }),
  R({
    name: '史耀斌',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1963年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2018', to: '2023', desc: '任财政部副部长' }],
  }),
  R({
    name: '翁杰明',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1963年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2018', to: '2023', desc: '任国务院国资委副主任' }],
  }),
  R({
    name: '田国立',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1960年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2017', to: '2023', desc: '任中国银行董事长' }],
  }),
  R({
    name: '陈雨露',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1966年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中国人民银行副行长' }],
  }),
  R({
    name: '于春生',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中央纪委国家监委委员' }],
  }),
  R({
    name: '安立佳',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1963年',
    native: '黑龙江',
    rank: '无党派',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2017', to: '2023', desc: '任中华全国总工会副主席' }],
  }),
  R({
    name: '谢经荣',
    institutionType: '人大',
    institution: '全国人大财政经济委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大财政经济委员会副主任委员',
    birth: '1963年',
    native: '山东',
    rank: '民盟中央副主席',
    tookOffice: '2023-03-05',
    career: [{ from: '2023', to: '', desc: '任全国人大财政经济委员会副主任委员' }, { from: '2017', to: '2023', desc: '任民盟中央副主席' }],
  }),
  R({
    name: '邓秀新',
    institutionType: '人大',
    institution: '全国人大农业与农村委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大农业与农村委员会副主任委员',
    birth: '1962年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大农业与农村委员会副主任委员' }, { from: '2017', to: '2023', desc: '任华中农业大学校长' }],
  }),
  R({
    name: '秦生祥',
    institutionType: '人大',
    institution: '全国人大社会建设委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大社会建设委员会副主任委员',
    birth: '1961年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大社会建设委员会副主任委员' }, { from: '2018', to: '2023', desc: '任国家体育总局局长' }],
  }),
  R({
    name: '孙绍骋',
    institutionType: '人大',
    institution: '全国人大社会建设委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大社会建设委员会副主任委员',
    birth: '1960年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大社会建设委员会副主任委员' }, { from: '2020', to: '2023', desc: '任退役军人事务部部长' }],
  }),
  R({
    name: '杜玉波',
    institutionType: '人大',
    institution: '全国人大教育科学文化卫生委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大教育科学文化卫生委员会副主任委员',
    birth: '1955年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大教科文卫委员会副主任委员' }, { from: '2016', to: '2023', desc: '任教育部副部长' }],
  }),
  R({
    name: '李巍',
    institutionType: '人大',
    institution: '全国人大教育科学文化卫生委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大教育科学文化卫生委员会副主任委员',
    birth: '1963年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大教科文卫委员会副主任委员' }, { from: '2018', to: '2023', desc: '任辽宁省副省长' }],
  }),
  R({
    name: '郝平',
    institutionType: '人大',
    institution: '全国人大教育科学文化卫生委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大教育科学文化卫生委员会副主任委员',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大教科文卫委员会副主任委员' }, { from: '2018', to: '2023', desc: '任北京大学党委书记' }],
  }),
  R({
    name: '许达哲',
    institutionType: '人大',
    institution: '全国人大外事委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大外事委员会副主任委员',
    birth: '1956年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大外事委员会副主任委员' }, { from: '2020', to: '2023', desc: '任湖南省人大常委会主任' }],
  }),
  R({
    name: '周亚宁',
    institutionType: '人大',
    institution: '全国人大外事委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大外事委员会副主任委员',
    birth: '1957年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大外事委员会副主任委员' }, { from: '2017', to: '2023', desc: '任南部战区司令员' }],
  }),
  R({
    name: '李作成',
    institutionType: '人大',
    institution: '全国人大外事委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大外事委员会副主任委员',
    birth: '1953年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大外事委员会副主任委员' }, { from: '2017', to: '2023', desc: '任南部战区政治委员' }],
  }),
  R({
    name: '黄志贤',
    institutionType: '人大',
    institution: '全国人大华侨委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大华侨委员会副主任委员',
    birth: '1955年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大华侨委员会副主任委员' }, { from: '2018', to: '2023', desc: '任中央统战部副部长' }],
  }),
  R({
    name: '罗保铭',
    institutionType: '人大',
    institution: '全国人大华侨委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大华侨委员会副主任委员',
    birth: '1955年',
    native: '天津',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大华侨委员会副主任委员' }, { from: '2017', to: '2020', desc: '任海南省人大常委会主任' }],
  }),
  R({
    name: '白春礼',
    institutionType: '人大',
    institution: '全国人大环境与资源保护委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大环境与资源保护委员会副主任委员',
    birth: '1953年',
    native: '辽宁',
    rank: '无党派',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大环境与资源保护委员会副主任委员' }, { from: '2011', to: '2020', desc: '任中国科学院院长' }],
  }),
  R({
    name: '李锦斌',
    institutionType: '人大',
    institution: '全国人大环境与资源保护委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大环境与资源保护委员会副主任委员',
    birth: '1956年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大环境与资源保护委员会副主任委员' }, { from: '2020', to: '2023', desc: '任安徽省人大常委会主任' }],
  }),
  R({
    name: '雪克来提·扎克尔',
    institutionType: '人大',
    institution: '全国人大环境与资源保护委员会',
    org: '全国人大常委会',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国人大环境与资源保护委员会副主任委员',
    birth: '1953年8月',
    native: '新疆伊宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-12',
    career: [{ from: '2023', to: '', desc: '任全国人大环境与资源保护委员会副主任委员' }, { from: '2023', to: '', desc: '任全国人大常委会副委员长' }],
  }),
  R({
    name: '古小玉',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会副秘书长',
    birth: '1963年',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会副秘书长' }, { from: '2018', to: '2023', desc: '任全国人大常委会法制工作委员会副主任' }],
  }),
  R({
    name: '郭雷',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会副秘书长',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会副秘书长' }, { from: '2018', to: '2023', desc: '任中国科学院副院长' }],
  }),
  R({
    name: '欧阳昌琼',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1963年',
    native: '江西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2018', to: '2023', desc: '任中国证监会副主席' }],
  }),
  R({
    name: '许达哲',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1956年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2020', to: '2023', desc: '任湖南省人大常委会主任' }],
  }),
  R({
    name: '李锦斌',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1956年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2020', to: '2023', desc: '任安徽省人大常委会主任' }],
  }),
  R({
    name: '楼阳生',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1957年',
    native: '山西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2021', to: '2023', desc: '任河南省委书记' }],
  }),
  R({
    name: '林武',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1962年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2021', to: '2023', desc: '任山东省委书记' }],
  }),
  R({
    name: '易炼红',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1959年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2022', to: '2023', desc: '任浙江省委书记' }],
  }),
  R({
    name: '马兴瑞',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1959年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2021', to: '2023', desc: '任新疆维吾尔自治区党委书记' }],
  }),
  R({
    name: '尹力',
    institutionType: '人大',
    institution: '全国人大常委会',
    org: '全国人大常委会',
    role: '常委会委员',
    level: '省部级',
    title: '全国人大常委会委员',
    birth: '1962年',
    native: '北京',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国人大常委会委员' }, { from: '2022', to: '2023', desc: '任福建省委书记' }],
  }),
  R({
    name: '刘家义',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协提案委员会主任',
    birth: '1956年5月',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会主任' }, { from: '2021', to: '2023', desc: '任山东省委书记' }, { from: '2018', to: '2021', desc: '任山东省委副书记、省长' }],
  }),
  R({
    name: '王国生',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协经济委员会主任',
    birth: '1956年5月',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会主任' }, { from: '2018', to: '2021', desc: '任河南省委书记' }, { from: '2013', to: '2018', desc: '任青海省委书记' }],
  }),
  R({
    name: '王建军',
    institutionType: '政协',
    institution: '全国政协农业和农村委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协农业和农村委员会主任',
    birth: '1958年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协农业和农村委员会主任' }, { from: '2017', to: '2023', desc: '任陕西省委书记' }, { from: '2013', to: '2017', desc: '任陕西省委副书记、省长' }],
  }),
  R({
    name: '车俊',
    institutionType: '政协',
    institution: '全国政协人口资源环境委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协人口资源环境委员会主任',
    birth: '1955年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协人口资源环境委员会主任' }, { from: '2018', to: '2023', desc: '任浙江省人大常委会主任' }, { from: '2013', to: '2018', desc: '任浙江省委副书记、省长' }],
  }),
  R({
    name: '陈宝生',
    institutionType: '政协',
    institution: '全国政协教科卫体委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协教科卫体委员会主任',
    birth: '1956年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协教科卫体委员会主任' }, { from: '2018', to: '2023', desc: '任教育部部长' }, { from: '2016', to: '2018', desc: '任国务院副秘书长' }],
  }),
  R({
    name: '徐令义',
    institutionType: '政协',
    institution: '全国政协社会和法制委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协社会和法制委员会主任',
    birth: '1956年',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协社会和法制委员会主任' }, { from: '2018', to: '2023', desc: '任中央纪委国家监委委员' }],
  }),
  R({
    name: '张裔炯',
    institutionType: '政协',
    institution: '全国政协民族和宗教委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协民族和宗教委员会主任',
    birth: '1955年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协民族和宗教委员会主任' }, { from: '2017', to: '2023', desc: '任中央统战部副部长' }],
  }),
  R({
    name: '刘赐贵',
    institutionType: '政协',
    institution: '全国政协港澳台侨委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协港澳台侨委员会主任',
    birth: '1955年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协港澳台侨委员会主任' }, { from: '2017', to: '2023', desc: '任海南省委书记' }, { from: '2013', to: '2017', desc: '任海南省委副书记、省长' }],
  }),
  R({
    name: '何平',
    institutionType: '政协',
    institution: '全国政协外事委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协外事委员会主任',
    birth: '1957年',
    native: '四川',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协外事委员会主任' }, { from: '2017', to: '2023', desc: '任四川省委副书记、省长' }],
  }),
  R({
    name: '（文化文史和学习委员会主任暂缺）',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会主任（暂缺）',
    birth: '',
    native: '',
    rank: '—',
    tookOffice: '2024-07-25',
    career: [{ from: '2024-07', to: '', desc: '吴英杰去职后主任职务待任命' }],
  }),
  R({
    name: '李世杰',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1957年',
    native: '吉林',
    rank: '民革中央副主席',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2017', to: '2023', desc: '任民革中央副主席' }],
  }),
  R({
    name: '张军扩',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1954年',
    native: '山东',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2018', to: '2023', desc: '任国务院发展研究中心副主任' }],
  }),
  R({
    name: '赵爱明',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1961年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2018', to: '2023', desc: '任国务院国资委副主任' }],
  }),
  R({
    name: '高鸿钧',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1963年',
    native: '河南',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2017', to: '2023', desc: '任中国科学院副院长' }],
  }),
  R({
    name: '崔波',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1957年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2017', to: '2023', desc: '任河北省委副书记' }],
  }),
  R({
    name: '韩卫国',
    institutionType: '政协',
    institution: '全国政协提案委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协提案委员会副主任',
    birth: '1956年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协提案委员会副主任' }, { from: '2017', to: '2023', desc: '任陆军司令员' }],
  }),
  R({
    name: '马建堂',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1958年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任国务院发展研究中心主任' }],
  }),
  R({
    name: '方光华',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1963年',
    native: '湖南',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任陕西省副省长' }],
  }),
  R({
    name: '尹艳林',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1962年',
    native: '江西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任国家统计局副局长' }],
  }),
  R({
    name: '宁吉喆',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1956年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2017', to: '2023', desc: '任国家发展改革委副主任' }],
  }),
  R({
    name: '毕井泉',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1955年',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2015', to: '2023', desc: '任国家食品药品监督管理总局局长' }],
  }),
  R({
    name: '余蔚平',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1963年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任财政部副部长' }],
  }),
  R({
    name: '苗圩',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1955年',
    native: '北京',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2012', to: '2020', desc: '任工业和信息化部部长' }],
  }),
  R({
    name: '林毅夫',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1952年',
    native: '台湾',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2008', to: '2023', desc: '任北京大学国家发展研究院名誉院长' }],
  }),
  R({
    name: '易纲',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1958年',
    native: '北京',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任中国人民银行行长' }],
  }),
  R({
    name: '戴东昌',
    institutionType: '政协',
    institution: '全国政协经济委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协经济委员会副主任',
    birth: '1962年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协经济委员会副主任' }, { from: '2018', to: '2023', desc: '任交通运输部副部长' }],
  }),
  R({
    name: '王晓东',
    institutionType: '政协',
    institution: '全国政协农业和农村委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协农业和农村委员会副主任',
    birth: '1957年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协农业和农村委员会副主任' }, { from: '2017', to: '2023', desc: '任湖北省委副书记、省长' }],
  }),
  R({
    name: '张桃林',
    institutionType: '政协',
    institution: '全国政协农业和农村委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协农业和农村委员会副主任',
    birth: '1961年',
    native: '江苏',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协农业和农村委员会副主任' }, { from: '2018', to: '2023', desc: '任农业农村部副部长' }],
  }),
  R({
    name: '胡盛寿',
    institutionType: '政协',
    institution: '全国政协农业和农村委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协农业和农村委员会副主任',
    birth: '1963年',
    native: '江西',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协农业和农村委员会副主任' }, { from: '2017', to: '2023', desc: '任中国医学科学院阜外医院院长' }],
  }),
  R({
    name: '蒋旭光',
    institutionType: '政协',
    institution: '全国政协农业和农村委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协农业和农村委员会副主任',
    birth: '1960年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协农业和农村委员会副主任' }, { from: '2018', to: '2023', desc: '任国务院国资委副主任' }],
  }),
  R({
    name: '王金南',
    institutionType: '政协',
    institution: '全国政协人口资源环境委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协人口资源环境委员会副主任',
    birth: '1957年',
    native: '浙江',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协人口资源环境委员会副主任' }, { from: '2017', to: '2023', desc: '任生态环境部副部长' }],
  }),
  R({
    name: '李微微',
    institutionType: '政协',
    institution: '全国政协人口资源环境委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协人口资源环境委员会副主任',
    birth: '1959年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协人口资源环境委员会副主任' }, { from: '2016', to: '2023', desc: '任湖南省政协主席' }],
  }),
  R({
    name: '杨小伟',
    institutionType: '政协',
    institution: '全国政协教科卫体委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协教科卫体委员会副主任',
    birth: '1962年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协教科卫体委员会副主任' }, { from: '2018', to: '2023', desc: '任中央宣传部副部长' }],
  }),
  R({
    name: '陈元',
    institutionType: '政协',
    institution: '全国政协教科卫体委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协教科卫体委员会副主任',
    birth: '1945年',
    native: '北京',
    rank: '无党派',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协教科卫体委员会副主任' }, { from: '2008', to: '2018', desc: '任全国政协副主席' }],
  }),
  R({
    name: '辜胜阻',
    institutionType: '政协',
    institution: '全国政协社会和法制委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协社会和法制委员会副主任',
    birth: '1956年',
    native: '湖北',
    rank: '民建中央副主席',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协社会和法制委员会副主任' }, { from: '2017', to: '2023', desc: '任全国政协副主席' }],
  }),
  R({
    name: '汪铁民',
    institutionType: '政协',
    institution: '全国政协社会和法制委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协社会和法制委员会副主任',
    birth: '1962年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协社会和法制委员会副主任' }, { from: '2018', to: '2023', desc: '任全国人大常委会副秘书长' }],
  }),
  R({
    name: '张道宏',
    institutionType: '政协',
    institution: '全国政协社会和法制委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协社会和法制委员会副主任',
    birth: '1962年',
    native: '陕西',
    rank: '民盟中央副主席',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协社会和法制委员会副主任' }, { from: '2017', to: '2023', desc: '任陕西省副省长' }],
  }),
  R({
    name: '张纪',
    institutionType: '政协',
    institution: '全国政协民族和宗教委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协民族和宗教委员会副主任',
    birth: '1957年',
    native: '北京',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协民族和宗教委员会副主任' }, { from: '2018', to: '2023', desc: '任中央宣传部副部长' }],
  }),
  R({
    name: '王宁',
    institutionType: '政协',
    institution: '全国政协外事委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协外事委员会副主任',
    birth: '1962年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协外事委员会副主任' }, { from: '2021', to: '2023', desc: '任云南省委书记' }],
  }),
  R({
    name: '王炳南',
    institutionType: '政协',
    institution: '全国政协外事委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协外事委员会副主任',
    birth: '1961年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协外事委员会副主任' }, { from: '2018', to: '2023', desc: '任商务部副部长' }],
  }),
  R({
    name: '朱生岭',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1957年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2017', to: '2023', desc: '任武警部队政治委员' }],
  }),
  R({
    name: '李宝善',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1956年',
    native: '山西',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任人民日报社社长' }],
  }),
  R({
    name: '陈润儿',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1957年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任河南省省长' }],
  }),
  R({
    name: '聂辰席',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1961年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任国家广播电视总局局长' }],
  }),
  R({
    name: '黄建盛',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1956年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任黑龙江省政协主席' }],
  }),
  R({
    name: '阎晶明',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1961年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任中国作家协会党组书记' }],
  }),
  R({
    name: '傅兴国',
    institutionType: '政协',
    institution: '全国政协文化文史和学习委员会',
    org: '全国政协',
    role: '专门委员会副主任',
    level: '副部级',
    title: '全国政协文化文史和学习委员会副主任',
    birth: '1963年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-13',
    career: [{ from: '2023', to: '', desc: '任全国政协文化文史和学习委员会副主任' }, { from: '2018', to: '2023', desc: '任中央组织部副部长' }],
  }),
  R({
    name: '马培华',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1949年',
    native: '江苏',
    rank: '民建中央副主席',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2017', to: '2023', desc: '任全国工商联专职副主席' }],
  }),
  R({
    name: '王荣',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1958年',
    native: '广东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2017', to: '2023', desc: '任广东省政协主席' }],
  }),
  R({
    name: '卢展工',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1952年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2018', to: '2023', desc: '任河南省政协主席' }],
  }),
  R({
    name: '齐扎拉',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1958年',
    native: '云南',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2017', to: '2023', desc: '任西藏自治区政府主席' }],
  }),
  R({
    name: '李惠东',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1962年',
    native: '福建',
    rank: '民革中央副主席',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2017', to: '2023', desc: '任民革中央副主席' }],
  }),
  R({
    name: '杨岳',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1961年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2018', to: '2023', desc: '任江苏省政协主席' }],
  }),
  R({
    name: '郑建闽',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1962年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2022', to: '2023', desc: '任福建省省长' }],
  }),
  R({
    name: '黄志贤',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1955年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2018', to: '2023', desc: '任中央统战部副部长' }],
  }),
  R({
    name: '楼继伟',
    institutionType: '政协',
    institution: '全国政协',
    org: '全国政协',
    role: '政协常委',
    level: '省部级',
    title: '全国政协常委',
    birth: '1950年',
    native: '山西',
    rank: '无党派',
    tookOffice: '2023-03-10',
    career: [{ from: '2023', to: '', desc: '任全国政协常委' }, { from: '2016', to: '2023', desc: '任全国社会保障基金理事会理事长' }],
  }),
  R({
    name: '马朝旭',
    institutionType: '部委',
    institution: '外交部',
    org: '外交部',
    role: '副部长',
    level: '副部级',
    title: '外交部副部长 · 党组成员',
    birth: '1969年',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2023-01',
    career: [{ from: '2023', to: '', desc: '任外交部副部长' }, { from: '2019', to: '2023', desc: '任外交部驻联合国代表' }],
  }),
  R({
    name: '孙卫东',
    institutionType: '部委',
    institution: '外交部',
    org: '外交部',
    role: '副部长',
    level: '副部级',
    title: '外交部副部长 · 党组成员',
    birth: '1965年',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2022-12',
    career: [{ from: '2022', to: '', desc: '任外交部副部长' }, { from: '2019', to: '2022', desc: '任外交部亚洲司司长' }],
  }),
  R({
    name: '邓励',
    institutionType: '部委',
    institution: '外交部',
    org: '外交部',
    role: '副部长',
    level: '副部级',
    title: '外交部副部长 · 党组成员',
    birth: '1967年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2021-12',
    career: [{ from: '2021', to: '', desc: '任外交部副部长' }, { from: '2019', to: '2021', desc: '任外交部拉丁美洲司司长' }],
  }),
  R({
    name: '陈晓东',
    institutionType: '部委',
    institution: '外交部',
    org: '外交部',
    role: '副部长',
    level: '副部级',
    title: '外交部副部长 · 党组成员',
    birth: '1965年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2024-06',
    career: [{ from: '2024', to: '', desc: '任外交部副部长' }, { from: '2021', to: '2024', desc: '任国际发展合作署署长' }],
  }),
  R({
    name: '赵辰昕',
    institutionType: '部委',
    institution: '国家发展改革委',
    org: '国家发展改革委',
    role: '副部长',
    level: '副部级',
    title: '国家发展改革委副主任 · 党组成员',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任国家发展改革委副主任' }, { from: '2018', to: '2022', desc: '任国家发展改革委秘书长' }],
  }),
  R({
    name: '李春临',
    institutionType: '部委',
    institution: '国家发展改革委',
    org: '国家发展改革委',
    role: '副部长',
    level: '副部级',
    title: '国家发展改革委副主任 · 党组成员',
    birth: '1968年',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2022-12',
    career: [{ from: '2022', to: '', desc: '任国家发展改革委副主任' }, { from: '2021', to: '2022', desc: '任陕西省常务副省长' }],
  }),
  R({
    name: '丛亮',
    institutionType: '部委',
    institution: '国家发展改革委',
    org: '国家发展改革委',
    role: '副部长',
    level: '副部级',
    title: '国家发展改革委副主任 · 党组成员',
    birth: '1971年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-12',
    career: [{ from: '2022', to: '', desc: '任国家发展改革委副主任' }, { from: '2018', to: '2022', desc: '任国家发展改革委秘书长' }],
  }),
  R({
    name: '刘苏社',
    institutionType: '部委',
    institution: '国家发展改革委',
    org: '国家发展改革委',
    role: '副部长',
    level: '副部级',
    title: '国家发展改革委副主任 · 党组成员',
    birth: '1965年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任国家发展改革委副主任' }, { from: '2020', to: '2023', desc: '任国家发展改革委秘书长' }],
  }),
  R({
    name: '廖岷',
    institutionType: '部委',
    institution: '财政部',
    org: '财政部',
    role: '副部长',
    level: '副部级',
    title: '财政部副部长 · 党组成员',
    birth: '1968年',
    native: '江西',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任财政部副部长' }, { from: '2018', to: '2022', desc: '任中央财经委员会办公室副主任' }],
  }),
  R({
    name: '王东伟',
    institutionType: '部委',
    institution: '财政部',
    org: '财政部',
    role: '副部长',
    level: '副部级',
    title: '财政部副部长 · 党组成员',
    birth: '1969年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-09',
    career: [{ from: '2023', to: '', desc: '任财政部副部长' }, { from: '2021', to: '2023', desc: '任安徽省副省长' }],
  }),
  R({
    name: '宋其超',
    institutionType: '部委',
    institution: '财政部',
    org: '财政部',
    role: '副部长',
    level: '副部级',
    title: '财政部副部长 · 党组成员',
    birth: '1970年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2024-11',
    career: [{ from: '2024', to: '', desc: '任财政部副部长' }, { from: '2022', to: '2024', desc: '任财政部部长助理' }],
  }),
  R({
    name: '王受文',
    institutionType: '部委',
    institution: '商务部',
    org: '商务部',
    role: '副部长',
    level: '副部级',
    title: '商务部副部长 · 党组副书记 · 国际贸易谈判代表',
    birth: '1966年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2022-07',
    career: [{ from: '2022', to: '', desc: '任商务部副部长兼国际贸易谈判代表' }, { from: '2015', to: '2022', desc: '任商务部副部长' }],
  }),
  R({
    name: '凌激',
    institutionType: '部委',
    institution: '商务部',
    org: '商务部',
    role: '副部长',
    level: '副部级',
    title: '商务部副部长 · 党组成员 · 国际贸易谈判副代表',
    birth: '1969年',
    native: '上海',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任商务部副部长兼国际贸易谈判副代表' }, { from: '2020', to: '2022', desc: '任商务部部长助理' }],
  }),
  R({
    name: '盛秋平',
    institutionType: '部委',
    institution: '商务部',
    org: '商务部',
    role: '副部长',
    level: '副部级',
    title: '商务部副部长 · 党组成员',
    birth: '1964年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2022-05',
    career: [{ from: '2022', to: '', desc: '任商务部副部长' }, { from: '2018', to: '2022', desc: '任商务部部长助理' }],
  }),
  R({
    name: '郭婷婷',
    institutionType: '部委',
    institution: '商务部',
    org: '商务部',
    role: '副部长',
    level: '副部级',
    title: '商务部副部长 · 党组成员',
    birth: '1970年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任商务部副部长' }, { from: '2022', to: '2022', desc: '任商务部部长助理' }],
  }),
  R({
    name: '李飞',
    institutionType: '部委',
    institution: '商务部',
    org: '商务部',
    role: '副部长',
    level: '副部级',
    title: '商务部副部长 · 党组成员',
    birth: '1973年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03',
    career: [{ from: '2023', to: '', desc: '任商务部副部长' }, { from: '2022', to: '2023', desc: '任商务部部长助理' }],
  }),
  R({
    name: '辛国斌',
    institutionType: '部委',
    institution: '工业和信息化部',
    org: '工业和信息化部',
    role: '副部长',
    level: '副部级',
    title: '工业和信息化部副部长 · 党组成员',
    birth: '1964年',
    native: '青海',
    rank: '二十届中央委员',
    tookOffice: '2017-07',
    career: [{ from: '2017', to: '', desc: '任工业和信息化部副部长' }, { from: '2013', to: '2017', desc: '任工业和信息化部总工程师' }],
  }),
  R({
    name: '张云明',
    institutionType: '部委',
    institution: '工业和信息化部',
    org: '工业和信息化部',
    role: '副部长',
    level: '副部级',
    title: '工业和信息化部副部长 · 党组成员',
    birth: '1965年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任工业和信息化部副部长' }, { from: '2018', to: '2022', desc: '任工业和信息化部总工程师' }],
  }),
  R({
    name: '叶民',
    institutionType: '部委',
    institution: '工业和信息化部',
    org: '工业和信息化部',
    role: '副部长',
    level: '副部级',
    title: '工业和信息化部副部长 · 党组成员',
    birth: '1965年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任工业和信息化部副部长' }, { from: '2018', to: '2022', desc: '任生态环境部副部长' }],
  }),
  R({
    name: '任洪斌',
    institutionType: '部委',
    institution: '国务院国资委',
    org: '国务院国资委',
    role: '副部长',
    level: '副部级',
    title: '国务院国资委副主任 · 党组成员',
    birth: '1963年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2018-07',
    career: [{ from: '2018', to: '', desc: '任国务院国资委副主任' }, { from: '2015', to: '2018', desc: '任中国机械工业集团董事长' }],
  }),
  R({
    name: '苟坪',
    institutionType: '部委',
    institution: '国务院国资委',
    org: '国务院国资委',
    role: '副部长',
    level: '副部级',
    title: '国务院国资委副主任 · 党组成员',
    birth: '1964年',
    native: '甘肃',
    rank: '二十届中央委员',
    tookOffice: '2020-12',
    career: [{ from: '2020', to: '', desc: '任国务院国资委副主任' }, { from: '2018', to: '2020', desc: '任国务院国资委秘书长' }],
  }),
  R({
    name: '王宏志',
    institutionType: '部委',
    institution: '国务院国资委',
    org: '国务院国资委',
    role: '副部长',
    level: '副部级',
    title: '国务院国资委副主任 · 党组成员',
    birth: '1969年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任国务院国资委副主任' }, { from: '2021', to: '2023', desc: '任国家能源局局长' }],
  }),
  R({
    name: '马晓伟',
    institutionType: '部委',
    institution: '国家卫生健康委',
    org: '国家卫生健康委',
    role: '副部长',
    level: '副部级',
    title: '国家卫生健康委副主任 · 党组成员',
    birth: '1959年',
    native: '山西',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任国家卫生健康委副主任' }, { from: '2013', to: '2018', desc: '任国家卫生计生委副主任' }],
  }),
  R({
    name: '曾益新',
    institutionType: '部委',
    institution: '国家卫生健康委',
    org: '国家卫生健康委',
    role: '副部长',
    level: '副部级',
    title: '国家卫生健康委副主任 · 党组成员',
    birth: '1962年',
    native: '广东',
    rank: '二十届中央委员',
    tookOffice: '2022-05',
    career: [{ from: '2022', to: '', desc: '任国家卫生健康委副主任' }, { from: '2018', to: '2022', desc: '任中山大学校长' }],
  }),
  R({
    name: '余艳红',
    institutionType: '部委',
    institution: '国家卫生健康委',
    org: '国家卫生健康委',
    role: '副部长',
    level: '副部级',
    title: '国家卫生健康委副主任 · 党组成员',
    birth: '1963年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任国家卫生健康委副主任' }, { from: '2013', to: '2018', desc: '任湖南省副省长' }],
  }),
  R({
    name: '齐玉',
    institutionType: '部委',
    institution: '公安部',
    org: '公安部',
    role: '副部长',
    level: '副部级',
    title: '公安部副部长 · 党委副书记',
    birth: '1965年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任公安部副部长' }, { from: '2018', to: '2022', desc: '任外交部副部长' }],
  }),
  R({
    name: '亓伟',
    institutionType: '部委',
    institution: '公安部',
    org: '公安部',
    role: '副部长',
    level: '副部级',
    title: '公安部副部长 · 党委委员',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任公安部副部长' }, { from: '2018', to: '2022', desc: '任公安部政治部主任' }],
  }),
  R({
    name: '徐大彤',
    institutionType: '部委',
    institution: '公安部',
    org: '公安部',
    role: '副部长',
    level: '副部级',
    title: '公安部副部长 · 党委委员',
    birth: '1966年',
    native: '天津',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任公安部副部长' }, { from: '2021', to: '2023', desc: '任陕西省副省长' }],
  }),
  R({
    name: '孙新阳',
    institutionType: '部委',
    institution: '司法部',
    org: '司法部',
    role: '副部长',
    level: '副部级',
    title: '司法部副部长 · 党组成员',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任司法部副部长' }, { from: '2016', to: '2018', desc: '任中央纪委国家监委委员' }],
  }),
  R({
    name: '王喜武',
    institutionType: '部委',
    institution: '司法部',
    org: '司法部',
    role: '副部长',
    level: '副部级',
    title: '司法部副部长 · 党组成员',
    birth: '1965年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2020-04',
    career: [{ from: '2020', to: '', desc: '任司法部副部长' }, { from: '2018', to: '2020', desc: '任司法部政治部主任' }],
  }),
  R({
    name: '左力',
    institutionType: '部委',
    institution: '司法部',
    org: '司法部',
    role: '副部长',
    level: '副部级',
    title: '司法部副部长 · 党组成员',
    birth: '1969年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任司法部副部长' }, { from: '2021', to: '2023', desc: '任司法部政治部主任' }],
  }),
  R({
    name: '熊选国',
    institutionType: '部委',
    institution: '人力资源和社会保障部',
    org: '人力资源和社会保障部',
    role: '副部长',
    level: '副部级',
    title: '人社部副部长 · 党组成员',
    birth: '1964年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任人社部副部长' }, { from: '2016', to: '2018', desc: '任司法部政治部主任' }],
  }),
  R({
    name: '俞家文',
    institutionType: '部委',
    institution: '人力资源和社会保障部',
    org: '人力资源和社会保障部',
    role: '副部长',
    level: '副部级',
    title: '人社部副部长 · 党组成员',
    birth: '1968年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任人社部副部长' }, { from: '2021', to: '2023', desc: '任人社部就业促进司司长' }],
  }),
  R({
    name: '李良生',
    institutionType: '部委',
    institution: '人力资源和社会保障部',
    org: '人力资源和社会保障部',
    role: '副部长',
    level: '副部级',
    title: '人社部副部长 · 党组成员',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2024-06',
    career: [{ from: '2024', to: '', desc: '任人社部副部长' }, { from: '2022', to: '2024', desc: '任人社部人事司司长' }],
  }),
  R({
    name: '王广华',
    institutionType: '部委',
    institution: '自然资源部',
    org: '自然资源部',
    role: '副部长',
    level: '副部级',
    title: '自然资源部副部长 · 党组成员',
    birth: '1963年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任自然资源部副部长' }, { from: '2016', to: '2018', desc: '任国土资源部副部长' }],
  }),
  R({
    name: '刘国洪',
    institutionType: '部委',
    institution: '自然资源部',
    org: '自然资源部',
    role: '副部长',
    level: '副部级',
    title: '自然资源部副部长 · 党组成员',
    birth: '1964年',
    native: '辽宁',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任自然资源部副部长' }, { from: '2018', to: '2022', desc: '任自然资源部总规划师' }],
  }),
  R({
    name: '孙雪涛',
    institutionType: '部委',
    institution: '生态环境部',
    org: '生态环境部',
    role: '副部长',
    level: '副部级',
    title: '生态环境部副部长 · 党组成员',
    birth: '1966年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2022-12',
    career: [{ from: '2022', to: '', desc: '任生态环境部副部长' }, { from: '2018', to: '2022', desc: '任生态环境部总工程师' }],
  }),
  R({
    name: '郭芳',
    institutionType: '部委',
    institution: '生态环境部',
    org: '生态环境部',
    role: '副部长',
    level: '副部级',
    title: '生态环境部副部长 · 党组成员',
    birth: '1970年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任生态环境部副部长' }, { from: '2021', to: '2023', desc: '任上海市副市长' }],
  }),
  R({
    name: '董建国',
    institutionType: '部委',
    institution: '住房城乡建设部',
    org: '住房城乡建设部',
    role: '副部长',
    level: '副部级',
    title: '住房城乡建设部副部长 · 党组成员',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任住房城乡建设部副部长' }, { from: '2021', to: '2023', desc: '任重庆市副市长' }],
  }),
  R({
    name: '秦海翔',
    institutionType: '部委',
    institution: '住房城乡建设部',
    org: '住房城乡建设部',
    role: '副部长',
    level: '副部级',
    title: '住房城乡建设部副部长 · 党组成员',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任住房城乡建设部副部长' }, { from: '2018', to: '2022', desc: '任中国建筑集团有限公司总经理' }],
  }),
  R({
    name: '付绪银',
    institutionType: '部委',
    institution: '交通运输部',
    org: '交通运输部',
    role: '副部长',
    level: '副部级',
    title: '交通运输部副部长 · 党组成员',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任交通运输部副部长' }, { from: '2021', to: '2023', desc: '任交通运输部海事局局长' }],
  }),
  R({
    name: '李扬',
    institutionType: '部委',
    institution: '交通运输部',
    org: '交通运输部',
    role: '副部长',
    level: '副部级',
    title: '交通运输部副部长 · 党组成员',
    birth: '1969年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2024-06',
    career: [{ from: '2024', to: '', desc: '任交通运输部副部长' }, { from: '2022', to: '2024', desc: '任交通运输部公路局局长' }],
  }),
  R({
    name: '朱鹤新',
    institutionType: '部委',
    institution: '中国人民银行',
    org: '中国人民银行',
    role: '副部长',
    level: '副部级',
    title: '中国人民银行副行长 · 党委委员',
    birth: '1968年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-07',
    career: [{ from: '2023', to: '', desc: '任中国人民银行副行长' }, { from: '2020', to: '2023', desc: '任国家外汇管理局局长' }],
  }),
  R({
    name: '宣昌能',
    institutionType: '部委',
    institution: '中国人民银行',
    org: '中国人民银行',
    role: '副部长',
    level: '副部级',
    title: '中国人民银行副行长 · 党委委员',
    birth: '1967年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2023-01',
    career: [{ from: '2023', to: '', desc: '任中国人民银行副行长' }, { from: '2019', to: '2023', desc: '任国家外汇管理局副局长' }],
  }),
  R({
    name: '陆磊',
    institutionType: '部委',
    institution: '中国人民银行',
    org: '中国人民银行',
    role: '副部长',
    level: '副部级',
    title: '中国人民银行副行长 · 党委委员',
    birth: '1971年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2024-06',
    career: [{ from: '2024', to: '', desc: '任中国人民银行副行长' }, { from: '2019', to: '2024', desc: '任国家外汇管理局副局长' }],
  }),
  R({
    name: '马有祥',
    institutionType: '部委',
    institution: '农业农村部',
    org: '农业农村部',
    role: '副部长',
    level: '副部级',
    title: '农业农村部副部长 · 党组成员',
    birth: '1964年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任农业农村部副部长' }, { from: '2015', to: '2018', desc: '任农业部副部长' }],
  }),
  R({
    name: '吴宏耀',
    institutionType: '部委',
    institution: '农业农村部',
    org: '农业农村部',
    role: '副部长',
    level: '副部级',
    title: '农业农村部副部长 · 党组成员',
    birth: '1963年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任农业农村部副部长' }, { from: '2018', to: '2022', desc: '任中央农村工作领导小组办公室副主任' }],
  }),
  R({
    name: '麦尔丹·木盖提',
    institutionType: '部委',
    institution: '农业农村部',
    org: '农业农村部',
    role: '副部长',
    level: '副部级',
    title: '农业农村部副部长 · 党组成员',
    birth: '1968年',
    native: '新疆',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任农业农村部副部长' }, { from: '2021', to: '2023', desc: '任新疆维吾尔自治区副主席' }],
  }),
  R({
    name: '邓小刚',
    institutionType: '部委',
    institution: '水利部',
    org: '水利部',
    role: '副部长',
    level: '副部级',
    title: '水利部副部长 · 党组成员',
    birth: '1964年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任水利部副部长' }, { from: '2015', to: '2018', desc: '任海南省副省长' }],
  }),
  R({
    name: '陈敏',
    institutionType: '部委',
    institution: '水利部',
    org: '水利部',
    role: '副部长',
    level: '副部级',
    title: '水利部副部长 · 党组成员',
    birth: '1965年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任水利部副部长' }, { from: '2018', to: '2022', desc: '任水利部总工程师' }],
  }),
  R({
    name: '王道席',
    institutionType: '部委',
    institution: '水利部',
    org: '水利部',
    role: '副部长',
    level: '副部级',
    title: '水利部副部长 · 党组成员',
    birth: '1969年',
    native: '河南',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任水利部副部长' }, { from: '2021', to: '2023', desc: '任黄河水利委员会主任' }],
  }),
  R({
    name: '王江平',
    institutionType: '部委',
    institution: '应急管理部',
    org: '应急管理部',
    role: '副部长',
    level: '副部级',
    title: '应急管理部副部长 · 党组成员',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任应急管理部副部长' }, { from: '2017', to: '2022', desc: '任工业和信息化部副部长' }],
  }),
  R({
    name: '徐加爱',
    institutionType: '部委',
    institution: '应急管理部',
    org: '应急管理部',
    role: '副部长',
    level: '副部级',
    title: '应急管理部副部长 · 党组成员',
    birth: '1964年',
    native: '湖南',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任应急管理部副部长' }, { from: '2018', to: '2022', desc: '任中央纪委国家监委委员' }],
  }),
  R({
    name: '宋元明',
    institutionType: '部委',
    institution: '应急管理部',
    org: '应急管理部',
    role: '副部长',
    level: '副部级',
    title: '应急管理部副部长 · 党委委员',
    birth: '1965年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任应急管理部副部长' }, { from: '2018', to: '2022', desc: '任国家矿山安全监察局局长' }],
  }),
  R({
    name: '蒲宇',
    institutionType: '部委',
    institution: '退役军人事务部',
    org: '退役军人事务部',
    role: '副部长',
    level: '副部级',
    title: '退役军人事务部副部长 · 党组成员',
    birth: '1965年',
    native: '四川',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任退役军人事务部副部长' }, { from: '2018', to: '2022', desc: '任退役军人事务部政治部主任' }],
  }),
  R({
    name: '林国耀',
    institutionType: '部委',
    institution: '退役军人事务部',
    org: '退役军人事务部',
    role: '副部长',
    level: '副部级',
    title: '退役军人事务部副部长 · 党组成员',
    birth: '1968年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任退役军人事务部副部长' }, { from: '2021', to: '2023', desc: '任福建省副省长' }],
  }),
  R({
    name: '林新',
    institutionType: '部委',
    institution: '科技部',
    org: '科技部',
    role: '副部长',
    level: '副部级',
    title: '科学技术部副部长 · 党组成员',
    birth: '1968年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2023-12',
    career: [{ from: '2023', to: '', desc: '任科技部副部长' }, { from: '2021', to: '2023', desc: '任科技部秘书长' }],
  }),
  R({
    name: '孟祥锋',
    institutionType: '中直',
    institution: '中央办公厅',
    org: '中央办公厅',
    role: '副主任',
    level: '副部级',
    title: '中央办公厅副主任 · 中央和国家机关工委副书记',
    birth: '1964年',
    native: '河北',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任中央办公厅副主任' }, { from: '2017', to: '2018', desc: '任中央办公厅秘书局局长' }],
  }),
  R({
    name: '游钧',
    institutionType: '中直',
    institution: '中央办公厅',
    org: '中央办公厅',
    role: '副主任',
    level: '副部级',
    title: '中央办公厅副主任',
    birth: '1963年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央办公厅副主任' }, { from: '2018', to: '2022', desc: '任人力资源和社会保障部副部长' }],
  }),
  R({
    name: '刘海星',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '部长',
    level: '正部级',
    title: '中央对外联络部部长 · 党组书记',
    birth: '1963年4月',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2025-09-30',
    career: [{ from: '2025', to: '', desc: '任中央对外联络部部长' }, { from: '2022', to: '2025', desc: '任中央国安办常务副主任' }, { from: '2018', to: '2022', desc: '任中央国安办副主任' }],
  }),
  R({
    name: '陈洲',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '副部长',
    level: '副部级',
    title: '中央对外联络部副部长',
    birth: '1965年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任中央对外联络部副部长' }, { from: '2018', to: '2022', desc: '任中央对外联络部秘书长' }],
  }),
  R({
    name: '李明祥',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '副部长',
    level: '副部级',
    title: '中央对外联络部副部长',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任中央对外联络部副部长' }, { from: '2018', to: '2022', desc: '任中央对外联络部办公厅主任' }],
  }),
  R({
    name: '孙海燕',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '副部长',
    level: '副部级',
    title: '中央对外联络部副部长',
    birth: '1970年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任中央对外联络部副部长' }, { from: '2018', to: '2022', desc: '任共青团中央书记处书记' }],
  }),
  R({
    name: '陆慷',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '副部长',
    level: '副部级',
    title: '中央对外联络部副部长',
    birth: '1968年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任中央对外联络部副部长' }, { from: '2019', to: '2022', desc: '任外交部新闻司司长' }],
  }),
  R({
    name: '马辉',
    institutionType: '中直',
    institution: '中央对外联络部',
    org: '中央对外联络部',
    role: '副部长',
    level: '副部级',
    title: '中央对外联络部副部长',
    birth: '1968年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-06',
    career: [{ from: '2022', to: '', desc: '任中央对外联络部副部长' }, { from: '2018', to: '2022', desc: '任中央对外联络部研究室主任' }],
  }),
  R({
    name: '傅华',
    institutionType: '中直',
    institution: '中央宣传部',
    org: '中央宣传部',
    role: '副部长',
    level: '副部级',
    title: '中央宣传部副部长 · 国务院新闻办公室主任',
    birth: '1964年',
    native: '北京',
    rank: '二十届中央委员',
    tookOffice: '2021-06',
    career: [{ from: '2021', to: '', desc: '任中央宣传部副部长兼国务院新闻办公室主任' }, { from: '2018', to: '2021', desc: '任广东省委常委、宣传部部长' }],
  }),
  R({
    name: '莫高义',
    institutionType: '中直',
    institution: '中央宣传部',
    org: '中央宣传部',
    role: '副部长',
    level: '副部级',
    title: '中央宣传部副部长',
    birth: '1964年',
    native: '陕西',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央宣传部副部长' }, { from: '2018', to: '2022', desc: '任北京市委常委、宣传部部长' }],
  }),
  R({
    name: '洪大用',
    institutionType: '中直',
    institution: '中央宣传部',
    org: '中央宣传部',
    role: '副部长',
    level: '副部级',
    title: '中央宣传部副部长',
    birth: '1965年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央宣传部副部长' }, { from: '2018', to: '2022', desc: '任科技部副部长' }],
  }),
  R({
    name: '姜信治',
    institutionType: '中直',
    institution: '中央组织部',
    org: '中央组织部',
    role: '副部长',
    level: '副部级',
    title: '中央组织部副部长',
    birth: '1960年5月',
    native: '山东龙口',
    rank: '二十届中央委员',
    tookOffice: '2017-03',
    career: [{ from: '2017', to: '', desc: '任中央组织部副部长' }, { from: '2012', to: '2017', desc: '任中央办公厅副主任' }],
  }),
  R({
    name: '喻云林',
    institutionType: '中直',
    institution: '中央组织部',
    org: '中央组织部',
    role: '副部长',
    level: '副部级',
    title: '中央组织部副部长',
    birth: '1962年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2023-03',
    career: [{ from: '2023', to: '', desc: '任中央组织部副部长' }, { from: '2018', to: '2023', desc: '任天津市委副书记' }],
  }),
  R({
    name: '王瑞连',
    institutionType: '中直',
    institution: '中央统战部',
    org: '中央统战部',
    role: '副部长',
    level: '副部级',
    title: '中央统战部副部长',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央统战部副部长' }, { from: '2018', to: '2022', desc: '任湖北省委常委、组织部部长' }],
  }),
  R({
    name: '陈旭',
    institutionType: '中直',
    institution: '中央统战部',
    org: '中央统战部',
    role: '副部长',
    level: '副部级',
    title: '中央统战部副部长',
    birth: '1963年',
    native: '吉林',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央统战部副部长' }, { from: '2018', to: '2022', desc: '任国务院侨务办公室主任' }],
  }),
  R({
    name: '潘岳',
    institutionType: '中直',
    institution: '中央统战部',
    org: '中央统战部',
    role: '副部长',
    level: '副部级',
    title: '中央统战部副部长 · 国家民委主任',
    birth: '1962年',
    native: '安徽',
    rank: '二十届中央委员',
    tookOffice: '2025-09',
    career: [{ from: '2025', to: '', desc: '任国家民委主任兼中央统战部副部长' }, { from: '2020', to: '2025', desc: '任中央统战部副部长' }],
  }),
  R({
    name: '訚柏',
    institutionType: '中直',
    institution: '中央政法委',
    org: '中央政法委',
    role: '秘书长',
    level: '副部级',
    title: '中央政法委秘书长',
    birth: '1966年',
    native: '云南',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央政法委秘书长' }, { from: '2018', to: '2022', desc: '任青海省委副书记' }],
  }),
  R({
    name: '徐麟',
    institutionType: '中直',
    institution: '中央政法委',
    org: '中央政法委',
    role: '副秘书长',
    level: '副部级',
    title: '中央政法委副秘书长',
    birth: '1963年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央政法委副秘书长' }, { from: '2018', to: '2022', desc: '任贵州省委书记' }],
  }),
  R({
    name: '王洪祥',
    institutionType: '中直',
    institution: '中央政法委',
    org: '中央政法委',
    role: '副秘书长',
    level: '副部级',
    title: '中央政法委副秘书长',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-03',
    career: [{ from: '2023', to: '', desc: '任中央政法委副秘书长' }, { from: '2018', to: '2023', desc: '任宪法和法律委员会副主任委员' }],
  }),
  R({
    name: '庄荣文',
    institutionType: '中直',
    institution: '中央网信办',
    org: '中央网信办',
    role: '主任',
    level: '正部级',
    title: '中央网信办主任 · 国家网信办主任',
    birth: '1961年',
    native: '福建',
    rank: '二十届中央委员',
    tookOffice: '2018-08',
    career: [{ from: '2018', to: '', desc: '任中央网信办主任' }, { from: '2016', to: '2018', desc: '任中央宣传部副部长' }],
  }),
  R({
    name: '曹淑敏',
    institutionType: '中直',
    institution: '中央网信办',
    org: '中央网信办',
    role: '副主任',
    level: '副部级',
    title: '中央网信办副主任 · 国家广电总局局长',
    birth: '1966年7月',
    native: '河北阜平',
    rank: '二十届中央候补委员',
    tookOffice: '2023-05',
    career: [{ from: '2023', to: '', desc: '任国家广电总局局长兼中央网信办副主任' }, { from: '2018', to: '2023', desc: '任中国电子信息产业发展研究院院长' }],
  }),
  R({
    name: '牛一兵',
    institutionType: '中直',
    institution: '中央网信办',
    org: '中央网信办',
    role: '副主任',
    level: '副部级',
    title: '中央网信办副主任',
    birth: '1966年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央网信办副主任' }, { from: '2018', to: '2022', desc: '任陕西省委常委、宣传部部长' }],
  }),
  R({
    name: '张通',
    institutionType: '中直',
    institution: '中央网信办',
    org: '中央网信办',
    role: '副主任',
    level: '副部级',
    title: '中央网信办副主任',
    birth: '1965年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央网信办副主任' }, { from: '2018', to: '2022', desc: '任工业和信息化部总工程师' }],
  }),
  R({
    name: '张晓明',
    institutionType: '中直',
    institution: '国务院港澳办',
    org: '国务院港澳办',
    role: '副主任',
    level: '副部级',
    title: '国务院港澳办副主任',
    birth: '1960年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2023-02',
    career: [{ from: '2023', to: '', desc: '任国务院港澳办副主任' }, { from: '2017', to: '2023', desc: '任中央港澳办副主任' }],
  }),
  R({
    name: '周霁',
    institutionType: '中直',
    institution: '国务院港澳办',
    org: '国务院港澳办',
    role: '副主任',
    level: '副部级',
    title: '国务院港澳办副主任',
    birth: '1964年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2023-02',
    career: [{ from: '2023', to: '', desc: '任国务院港澳办副主任' }, { from: '2021', to: '2023', desc: '任湖北省委副书记' }],
  }),
  R({
    name: '王灵桂',
    institutionType: '中直',
    institution: '国务院港澳办',
    org: '国务院港澳办',
    role: '副主任',
    level: '副部级',
    title: '国务院港澳办副主任',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2023-02',
    career: [{ from: '2023', to: '', desc: '任国务院港澳办副主任' }, { from: '2018', to: '2023', desc: '任中国社会科学院副院长' }],
  }),
  R({
    name: '高翔',
    institutionType: '中直',
    institution: '中国社会科学院',
    org: '中国社会科学院',
    role: '院长',
    level: '正部级',
    title: '中国社会科学院院长 · 党组书记',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中国社会科学院院长' }, { from: '2018', to: '2022', desc: '任中央党史和文献研究院副院长' }],
  }),
  R({
    name: '黄晓薇',
    institutionType: '中直',
    institution: '中央党校',
    org: '中央党校',
    role: '校长',
    level: '正部级',
    title: '中央党校校长 · 国家行政学院院长',
    birth: '1963年',
    native: '湖北',
    rank: '二十届中央委员',
    tookOffice: '2022-10',
    career: [{ from: '2022', to: '', desc: '任中央党校校长' }, { from: '2018', to: '2022', desc: '任民政部党组书记、部长' }],
  }),
  R({
    name: '韩文秀',
    institutionType: '中直',
    institution: '中央财办',
    org: '中央财办',
    role: '副主任',
    level: '副部级',
    title: '中央财经委员会办公室副主任',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2018-03',
    career: [{ from: '2018', to: '', desc: '任中央财经办副主任' }, { from: '2016', to: '2018', desc: '任国家发展改革委副秘书长' }],
  }),
  R({
    name: '王志军',
    institutionType: '中直',
    institution: '国务院办公厅',
    org: '国务院办公厅',
    role: '副秘书长',
    level: '副部级',
    title: '国务院副秘书长',
    birth: '1966年',
    native: '黑龙江',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任国务院副秘书长' }, { from: '2018', to: '2022', desc: '任工业和信息化部副部长' }],
  }),
  R({
    name: '丁学东',
    institutionType: '中直',
    institution: '国务院办公厅',
    org: '国务院办公厅',
    role: '副秘书长',
    level: '副部级',
    title: '国务院副秘书长',
    birth: '1960年',
    native: '江苏',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任国务院副秘书长' }, { from: '2017', to: '2022', desc: '任全国社会保障基金理事会理事长' }],
  }),
  R({
    name: '徐绍史',
    institutionType: '中直',
    institution: '国务院办公厅',
    org: '国务院办公厅',
    role: '副秘书长',
    level: '副部级',
    title: '国务院副秘书长',
    birth: '1954年',
    native: '浙江',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任国务院副秘书长' }, { from: '2013', to: '2018', desc: '任国家发展改革委主任' }],
  }),
  R({
    name: '郭玮',
    institutionType: '中直',
    institution: '国务院研究室',
    org: '国务院研究室',
    role: '副主任',
    level: '副部级',
    title: '国务院研究室副主任',
    birth: '1963年',
    native: '山东',
    rank: '二十届中央委员',
    tookOffice: '2022-04',
    career: [{ from: '2022', to: '', desc: '任国务院研究室副主任' }, { from: '2018', to: '2022', desc: '任国务院研究室党组成员' }],
  })
];

export const FIGURE_POLITICAL_STRUCTURE_COUNT = FIGURE_POLITICAL_STRUCTURE_2026.length;
