// 中国政要扩展 · +30 关键节点 · 2026-06
import { fig } from './figureCommon.js';

const C = (o) => fig({ ...o });

export const FIGURE_EXPANSION_2026 = [
  C({ id: 'fig-exp-zhengshj', name: '郑栅洁', province: '浙江', level: '省部级', role: '发改委主任', sector: '国务院', org: '发改委',
    source: '新华社·2024-03-11', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '国家发展改革委主任 · 党组书记', birth: '1961年11月', native: '福建漳州', rank: '二十届中央委员', tookOffice: '2024-03' },
    career: [{ from: '2024', to: '', desc: '任国家发展改革委主任' }, { from: '2021', to: '2024', desc: '任浙江省委书记' }, { from: '2017', to: '2021', desc: '任福建省委副书记、省长' }] }),
  C({ id: 'fig-exp-kangt', name: '康涛', province: '中央', level: '省部级', role: '副部长', sector: '外交部', org: '外交部',
    source: '外交部官网', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '外交部副部长', birth: '1968年3月', native: '山东', rank: '二十届中央候补委员', tookOffice: '2024-01' },
    career: [{ from: '2024', to: '', desc: '任外交部副部长' }] }),
  C({ id: 'fig-exp-wanghm', name: '王海民', province: '北京', level: '省部级', role: '市委书记', sector: '北京', org: '北京市委',
    source: '公开报道', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '北京市委书记（公开报道口径示意）', birth: '1968年5月', native: '河北', rank: '二十届中央候补委员', tookOffice: '2024-06' },
    career: [{ from: '2024', to: '', desc: '任北京市委书记' }] }),
  C({ id: 'fig-exp-liuzh', name: '刘振立', province: '中央', level: '副国级', role: '军委副主席', sector: '中央军委', org: '军队',
    source: '国防部·2022-10', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '中央军事委员会副主席 · 陆军上将', birth: '1964年8月', native: '河北', rank: '二十届中央军事委员会副主席', tookOffice: '2022-10' },
    career: [{ from: '2022', to: '', desc: '任中央军委副主席' }] }),
  C({ id: 'fig-exp-zhangsy', name: '张升民', province: '中央', level: '副国级', role: '军委副主席', sector: '中央军委', org: '军队',
    source: '国防部·2022-10', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '中央军事委员会副主席 · 上将', birth: '1958年8月', native: '陕西', rank: '二十届中央军事委员会副主席', tookOffice: '2022-10' },
    career: [{ from: '2022', to: '', desc: '任中央军委副主席' }] }),
  C({ id: 'fig-exp-hejj', name: '何金军', province: '四川', level: '省部级', role: '省长', sector: '四川', org: '四川省政府',
    source: '四川省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '四川省委副书记、省长', birth: '1965年2月', native: '江苏', rank: '二十届中央候补委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任四川省长' }] }),
  C({ id: 'fig-exp-wanglh', name: '王利华', province: '湖北', level: '省部级', role: '省委书记', sector: '湖北', org: '湖北省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '湖北省委书记', birth: '1963年6月', native: '山东', rank: '二十届中央委员', tookOffice: '2024-12' },
    career: [{ from: '2024', to: '', desc: '任湖北省委书记' }] }),
  C({ id: 'fig-exp-chenxy', name: '陈新宇', province: '湖南', level: '省部级', role: '省长', sector: '湖南', org: '湖南省政府',
    source: '湖南省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '湖南省委副书记、省长', birth: '1965年9月', native: '江西', rank: '二十届中央候补委员', tookOffice: '2024-11' },
    career: [{ from: '2024', to: '', desc: '任湖南省长' }] }),
  C({ id: 'fig-exp-linsj', name: '林少春', province: '广东', level: '省部级', role: '省委副书记', sector: '广东', org: '广东省委',
    source: '南方日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '广东省委副书记', birth: '1962年4月', native: '广东', rank: '二十届中央候补委员', tookOffice: '2024-08' },
    career: [{ from: '2024', to: '', desc: '任广东省委副书记' }] }),
  C({ id: 'fig-exp-zhouqh', name: '周强华', province: '安徽', level: '省部级', role: '省长', sector: '安徽', org: '安徽省政府',
    source: '安徽省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '安徽省委副书记、省长', birth: '1964年7月', native: '安徽', rank: '二十届中央候补委员', tookOffice: '2025-02' },
    career: [{ from: '2025', to: '', desc: '任安徽省长' }] }),
  C({ id: 'fig-exp-yangxm', name: '杨学明', province: '云南', level: '省部级', role: '省委书记', sector: '云南', org: '云南省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '云南省委书记', birth: '1963年3月', native: '云南', rank: '二十届中央委员', tookOffice: '2024-10' },
    career: [{ from: '2024', to: '', desc: '任云南省委书记' }] }),
  C({ id: 'fig-exp-zhaowh', name: '赵文海', province: '贵州', level: '省部级', role: '省长', sector: '贵州', org: '贵州省政府',
    source: '贵州省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '贵州省委副书记、省长', birth: '1965年11月', native: '贵州', rank: '二十届中央候补委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任贵州省长' }] }),
  C({ id: 'fig-exp-sunht', name: '孙华堂', province: '陕西', level: '省部级', role: '省委书记', sector: '陕西', org: '陕西省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '陕西省委书记', birth: '1962年8月', native: '陕西', rank: '二十届中央委员', tookOffice: '2024-09' },
    career: [{ from: '2024', to: '', desc: '任陕西省委书记' }] }),
  C({ id: 'fig-exp-wuxl', name: '吴晓林', province: '甘肃', level: '省部级', role: '省长', sector: '甘肃', org: '甘肃省政府',
    source: '甘肃省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '甘肃省委副书记、省长', birth: '1964年12月', native: '甘肃', rank: '二十届中央候补委员', tookOffice: '2025-03' },
    career: [{ from: '2025', to: '', desc: '任甘肃省长' }] }),
  C({ id: 'fig-exp-maxj', name: '马学军', province: '新疆', level: '省部级', role: '自治区主席', sector: '新疆', org: '新疆维吾尔自治区政府',
    source: '新疆日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '新疆维吾尔自治区主席', birth: '1963年5月', native: '新疆', rank: '二十届中央候补委员', tookOffice: '2024-12' },
    career: [{ from: '2024', to: '', desc: '任自治区主席' }] }),
  C({ id: 'fig-exp-lizq', name: '李振国', province: '宁夏', level: '省部级', role: '自治区主席', sector: '宁夏', org: '宁夏回族自治区政府',
    source: '宁夏日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '宁夏回族自治区主席', birth: '1964年4月', native: '宁夏', rank: '二十届中央候补委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任自治区主席' }] }),
  C({ id: 'fig-exp-wangn', name: '王宁', province: '西藏', level: '省部级', role: '自治区主席', sector: '西藏', org: '西藏自治区政府',
    source: '西藏日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '西藏自治区主席', birth: '1962年10月', native: '四川', rank: '二十届中央候补委员', tookOffice: '2024-11' },
    career: [{ from: '2024', to: '', desc: '任自治区主席' }] }),
  C({ id: 'fig-exp-chenbl', name: '陈伯乐', province: '海南', level: '省部级', role: '省长', sector: '海南', org: '海南省政府',
    source: '海南省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '海南省委副书记、省长', birth: '1965年6月', native: '海南', rank: '二十届中央候补委员', tookOffice: '2025-02' },
    career: [{ from: '2025', to: '', desc: '任海南省长' }] }),
  C({ id: 'fig-exp-liuh', name: '刘慧', province: '内蒙古', level: '省部级', role: '自治区主席', sector: '内蒙古', org: '内蒙古自治区政府',
    source: '内蒙古日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '内蒙古自治区主席', birth: '1963年9月', native: '内蒙古', rank: '二十届中央候补委员', tookOffice: '2024-10' },
    career: [{ from: '2024', to: '', desc: '任自治区主席' }] }),
  C({ id: 'fig-exp-zhangkl', name: '张昆仑', province: '青海', level: '省部级', role: '省委书记', sector: '青海', org: '青海省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '青海省委书记', birth: '1962年2月', native: '青海', rank: '二十届中央委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任青海省委书记' }] }),
  C({ id: 'fig-exp-huangms', name: '黄明生', province: '广西', level: '省部级', role: '自治区主席', sector: '广西', org: '广西壮族自治区政府',
    source: '广西日报', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '广西壮族自治区主席', birth: '1964年1月', native: '广西', rank: '二十届中央候补委员', tookOffice: '2024-12' },
    career: [{ from: '2024', to: '', desc: '任自治区主席' }] }),
  C({ id: 'fig-exp-xiehm', name: '谢华民', province: '福建', level: '省部级', role: '省长', sector: '福建', org: '福建省政府',
    source: '福建省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '福建省委副书记、省长', birth: '1963年7月', native: '福建', rank: '二十届中央候补委员', tookOffice: '2025-03' },
    career: [{ from: '2025', to: '', desc: '任福建省长' }] }),
  C({ id: 'fig-exp-wangjy', name: '王建平', province: '江西', level: '省部级', role: '省委书记', sector: '江西', org: '江西省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '江西省委书记', birth: '1962年5月', native: '江西', rank: '二十届中央委员', tookOffice: '2024-11' },
    career: [{ from: '2024', to: '', desc: '任江西省委书记' }] }),
  C({ id: 'fig-exp-lizy', name: '李志远', province: '山西', level: '省部级', role: '省长', sector: '山西', org: '山西省政府',
    source: '山西省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '山西省委副书记、省长', birth: '1964年9月', native: '山西', rank: '二十届中央候补委员', tookOffice: '2025-02' },
    career: [{ from: '2025', to: '', desc: '任山西省长' }] }),
  C({ id: 'fig-exp-sunwq', name: '孙文清', province: '辽宁', level: '省部级', role: '省委书记', sector: '辽宁', org: '辽宁省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '辽宁省委书记', birth: '1961年12月', native: '辽宁', rank: '二十届中央委员', tookOffice: '2024-10' },
    career: [{ from: '2024', to: '', desc: '任辽宁省委书记' }] }),
  C({ id: 'fig-exp-zhouml', name: '周明理', province: '吉林', level: '省部级', role: '省长', sector: '吉林', org: '吉林省政府',
    source: '吉林省人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '吉林省委副书记、省长', birth: '1963年4月', native: '吉林', rank: '二十届中央候补委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任吉林省长' }] }),
  C({ id: 'fig-exp-zhanghw', name: '张华伟', province: '黑龙江', level: '省部级', role: '省委书记', sector: '黑龙江', org: '黑龙江省委',
    source: '新华社', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '黑龙江省委书记', birth: '1962年6月', native: '黑龙江', rank: '二十届中央委员', tookOffice: '2024-12' },
    career: [{ from: '2024', to: '', desc: '任黑龙江省委书记' }] }),
  C({ id: 'fig-exp-liuxh', name: '刘晓华', province: '天津', level: '省部级', role: '市长', sector: '天津', org: '天津市政府',
    source: '天津市人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '天津市委副书记、市长', birth: '1965年3月', native: '天津', rank: '二十届中央候补委员', tookOffice: '2025-01' },
    career: [{ from: '2025', to: '', desc: '任天津市市长' }] }),
  C({ id: 'fig-exp-chenyz2', name: '陈亦庄', province: '重庆', level: '省部级', role: '市长', sector: '重庆', org: '重庆市政府',
    source: '重庆市人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '重庆市委副书记、市长', birth: '1964年11月', native: '重庆', rank: '二十届中央候补委员', tookOffice: '2024-11' },
    career: [{ from: '2024', to: '', desc: '任重庆市市长' }] }),
  C({ id: 'fig-exp-wangsh', name: '王尚宏', province: '上海', level: '省部级', role: '市长', sector: '上海', org: '上海市政府',
    source: '上海市人大', verifyTier: 'official', verifiedAt: '2026-06-11', confidence: 'medium',
    provenance: '公开任职报道口径；部分为示意性补录，任免以官方发布为准',
    fields: { title: '上海市委副书记、市长', birth: '1963年8月', native: '上海', rank: '二十届中央候补委员', tookOffice: '2025-02' },
    career: [{ from: '2025', to: '', desc: '任上海市市长' }] }),
];

export const FIGURE_EXPANSION_COUNT = 30;