// ============================================================================
// 人才库扩展 · Part 3 · curated by scripts/genTalentExpansion3.py
// ============================================================================
import { withProvenance, fig } from './figureCommon.js';

export const DISSIDENT_EXPANSION_3 = [
  withProvenance({ id: 'dv-x3-01', name: '胡佳', nameEn: 'Hu Jia', category: 'online', subCategory: '网络异议', background: '北京环保NGO', field: '公民监督', knownFor: '艾滋病与环保维权', status: '监视居住', location: '境内·北京', keyEvents: [{ from: '2008', to: '', desc: '因煽动颠覆国家政权罪被判三年半' }, { from: '2013', to: '', desc: '刑满后继续公开评论' }], tags: '环保,艾滋病', tier: 'A', source: '公开判决', bio: '以环保与公民监督议题进入公开记录；案件属政治安全类公诉，叙事存在阵营化差异。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-02', name: '杨恒均', nameEn: 'Yang Hengjun', category: 'writer', subCategory: '作家', background: '旅澳作家/前外交官', field: '政治评论', knownFor: '间谍罪指控', status: '在押', location: '境内', keyEvents: [{ from: '2019', to: '', desc: '广州入境后被拘' }, { from: '2020', to: '', desc: '以间谍罪被判死刑缓期二年' }], tags: '间谍罪,评论', tier: 'A', source: '公开判决', bio: '旅澳中文作家；间谍罪判决引发中澳外交与人道议题。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-03', name: '桂敏海', nameEn: 'Gui Minhai', category: 'writer', subCategory: '作家', background: '瑞典籍书商', field: '出版', knownFor: '铜锣湾书店', status: '在押', location: '境内', keyEvents: [{ from: '2015', to: '', desc: '泰国失踪' }, { from: '2016', to: '', desc: '央视认罪' }, { from: '2018', to: '', desc: '瑞典籍获释后再被拘' }], tags: '铜锣湾,出版', tier: 'A', source: '公开报道', bio: '铜锣湾书店案核心人物；跨境拘押与国籍议题交织。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-04', name: '曾建元', nameEn: 'Zeng Jianyuan', category: 'writer', subCategory: '学者', background: '旅美学者', field: '宪政研究', knownFor: '《中国民主化》', status: '流亡', location: '海外·美国', keyEvents: [{ from: '1989', to: '', desc: '六四后流亡' }, { from: '2000', to: '', desc: '持续出版宪政研究' }], tags: '宪政,民运', tier: 'B', source: '公开报道', bio: '六四后流亡学者；宪政与民主化研究。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-05', name: '徐琳', nameEn: 'Xu Lin', category: 'movement', subCategory: '民运', background: '广州异议', field: '街头抗议', knownFor: '孙志刚案后抗议', status: '在押', location: '境内·广东', keyEvents: [{ from: '2006', to: '', desc: '参与街头抗议' }, { from: '2018', to: '', desc: '因寻衅滋事罪被判三年' }], tags: '孙志刚,街头', tier: 'B', source: '公开判决', bio: '孙志刚案后街头抗议参与者。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-06', name: '陈子明', nameEn: 'Chen Ziming', category: 'movement', subCategory: '民运', background: '北大物理系', field: '1989学运', knownFor: '六四知识分子', status: '已故', location: '境内', keyEvents: [{ from: '1989', to: '', desc: '参与学运' }, { from: '1991', to: '', desc: '以煽动颠覆罪被判' }, { from: '2014', to: '', desc: '狱中逝世' }], tags: '六四,知识分子', tier: 'A', source: '公开报道', bio: '八九学运知识分子；长期服刑后狱中逝世。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-07', name: '程翔', nameEn: 'Cheng Xiang', category: 'journalist', subCategory: '记者', background: '香港《亚洲周刊》', field: '政治报道', knownFor: '泄密案', status: '流亡', location: '海外·香港', keyEvents: [{ from: '2005', to: '', desc: '因间谍罪被判五年' }, { from: '2007', to: '', desc: '刑满后赴港' }], tags: '记者,泄密', tier: 'A', source: '公开判决', bio: '资深记者涉密案件；香港媒体自由议题案例。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-08', name: '黎智英', nameEn: 'Jimmy Lai', category: 'journalist', subCategory: '媒体', background: '壹传媒创办人', field: '媒体自由', knownFor: '苹果日报', status: '在押', location: '境内·香港', keyEvents: [{ from: '2020', to: '', desc: '国安法下被捕' }, { from: '2021', to: '', desc: '以串谋勾结外国势力等罪起诉' }, { from: '2024', to: '', desc: '被判十四年' }], tags: '苹果日报,国安法', tier: 'A', source: '公开判决', bio: '壹传媒创办人；国安法下媒体案件标志性人物。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-09', name: '邹幸彤', nameEn: 'Zhang Xintong', category: 'journalist', subCategory: '记者', background: '香港记者', field: '新闻自由', knownFor: '六四纪念报道', status: '在押', location: '境内·香港', keyEvents: [{ from: '2021', to: '', desc: '因参与六四纪念被捕' }, { from: '2023', to: '', desc: '被判监禁' }], tags: '六四,记者', tier: 'A', source: '公开判决', bio: '香港记者；六四纪念相关案件。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-10', name: '卢思位', nameEn: 'Lu Siwei', category: 'lawyer', subCategory: '维权律师', background: '成都律师', field: '709案', knownFor: '律师辩护', status: '在押', location: '境内·四川', keyEvents: [{ from: '2021', to: '', desc: '试图出境时被捕' }, { from: '2023', to: '', desc: '以煽动颠覆罪被判' }], tags: '709案,律师', tier: 'A', source: '公开判决', bio: '709案后续辩护律师；出境被捕引发关注。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-11', name: '袁弓夷', nameEn: 'Yuan Gongyi', category: 'online', subCategory: '网络异议', background: '香港商人', field: '政治评论', knownFor: '国安法案件', status: '在押', location: '境内·香港', keyEvents: [{ from: '2023', to: '', desc: '因煽动罪被捕' }], tags: '国安法,评论', tier: 'B', source: '公开报道', bio: '香港商界人士涉国安法案件。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-12', name: '许颖婷', nameEn: 'Joanna Ching', category: 'movement', subCategory: '网络异议', background: '香港社运', field: '海外连线', knownFor: '国安法通缉', status: '流亡', location: '海外·英国', keyEvents: [{ from: '2020', to: '', desc: '参与社运' }, { from: '2023', to: '', desc: '被国安法通缉' }], tags: '国安法,社运', tier: 'B', source: '公开报道', bio: '国安法下被通缉的海外港人之一。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-13', name: '黄之锋', nameEn: 'Joshua Wong', category: 'movement', subCategory: '网络异议', background: '香港学运', field: '雨伞运动', knownFor: 'Demosisto', status: '在押', location: '境内·香港', keyEvents: [{ from: '2014', to: '', desc: '雨伞运动' }, { from: '2020', to: '', desc: '国安法下被捕' }, { from: '2021', to: '', desc: '被判监禁' }], tags: '雨伞运动,国安法', tier: 'A', source: '公开报道', bio: '雨伞运动学生领袖；国安法后多次入罪。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-14', name: '罗冠聪', nameEn: 'Nathan Law', category: 'movement', subCategory: '网络异议', background: '香港学运', field: '立法会议员', knownFor: 'Demosisto', status: '流亡', location: '海外·英国', keyEvents: [{ from: '2016', to: '', desc: '当选立法会议员' }, { from: '2017', to: '', desc: '被剥夺议员资格' }, { from: '2020', to: '', desc: '流亡英国' }], tags: '学运,流亡', tier: 'A', source: '公开报道', bio: '最年轻立法会议员之一；被剥夺资格后流亡。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x3-15', name: '周锋锁', nameEn: 'Zhou Fengsuo', category: 'movement', subCategory: '民运', background: '1989学运', field: '学生领袖', knownFor: '六四', status: '流亡', location: '海外·美国', keyEvents: [{ from: '1989', to: '', desc: '学运领袖' }, { from: '1990', to: '', desc: '流亡美国' }], tags: '六四,学运', tier: 'A', source: '公开报道', bio: '1989学运学生领袖；流亡后从事人权 advocacy。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
];
export const DISSIDENT_EXPANSION_3_COUNT = 15;

export const TAIWAN_POLITICAL_EXPANSION_3 = [
  withProvenance({ id: 'tw-x3-01', name: '周万来', nameEn: 'Chou Wan-lai', region: 'tw', category: 'legislature', party: 'DPP', role: '立法院秘书长', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '任立法院秘书长' }, { from: '2016', to: '2024', desc: '任立委' }], tags: '立院,民进党', bio: '2024任立法院秘书长；曾任立法委员。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-02', name: '翁柏宗', nameEn: 'Weng Po-tsung', region: 'tw', category: 'executive', party: 'DPP', role: 'NCC主委', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '任NCC主委' }], tags: 'NCC,通讯', bio: '2024任国家通讯传播委员会主任委员。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-03', name: '郑英耀', nameEn: 'Cheng Ying-yao', region: 'tw', category: 'premier', party: 'DPP', role: '教育部长', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '任教育部长' }, { from: '2016', to: '2020', desc: '任高雄市副市长' }], tags: '教育部,民进党', bio: '2024卓荣泰内阁教育部长；曾任高雄市副市长。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-04', name: '周春米', nameEn: 'Chou Chun-mi', region: 'tw', category: 'local', party: 'DPP', role: '屏东县长', term: '2018—', status: '在任', keyEvents: [{ from: '2018', to: '', desc: '当选屏东县长' }, { from: '2022', to: '', desc: '连任屏东县长' }], tags: '民进党,屏东', bio: '民进党屏东县长；连任成功。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-05', name: '钟东锦', nameEn: 'Chung Tung-chin', region: 'tw', category: 'local', party: '无党籍', role: '苗栗县长', term: '2022—', status: '在任', keyEvents: [{ from: '2022', to: '', desc: '当选苗栗县长' }], tags: '苗栗,无党籍', bio: '2022以无党籍身份当选苗栗县长。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-06', name: '陈福海', nameEn: 'Chen Fu-hai', region: 'tw', category: 'local', party: 'DPP', role: '澎湖县长', term: '2014—', status: '在任', keyEvents: [{ from: '2014', to: '', desc: '当选澎湖县长' }, { from: '2022', to: '', desc: '连任澎湖县长' }], tags: '民进党,澎湖', bio: '民进党澎湖县长；外岛治理案例。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-07', name: '饶庆铃', nameEn: 'Rao Ching-ling', region: 'tw', category: 'local', party: 'KMT', role: '台东县长', term: '2018—', status: '在任', keyEvents: [{ from: '2018', to: '', desc: '当选台东县长' }, { from: '2022', to: '', desc: '连任台东县长' }], tags: '国民党,台东', bio: '国民党台东县长；原住民与观光议题。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-08', name: '谢国梁', nameEn: 'Hieh Kuo-liang', region: 'tw', category: 'local', party: 'KMT', role: '基隆市长', term: '2022—', status: '在任', keyEvents: [{ from: '2022', to: '', desc: '当选基隆市长' }], tags: '国民党,基隆', bio: '2022国民党夺回基隆市。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-09', name: '吴思瑶', nameEn: 'Wu Szu-yao', region: 'tw', category: 'legislature', party: 'DPP', role: '立委', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '连任立委' }, { from: '2016', to: '2024', desc: '台北市立委' }], tags: '民进党,立委', bio: '民进党台北市立法委员。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-10', name: '邱臣远', nameEn: 'Chiu Chen-yuan', region: 'tw', category: 'legislature', party: 'TPP', role: '立委', term: '2020—2024', status: '卸任', keyEvents: [{ from: '2020', to: '', desc: '民众党籍不分区立委' }, { from: '2024', to: '', desc: '未连任' }], tags: '民众党,立委', bio: '2020—2024民众党籍不分区立法委员。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-11', name: '王鸿薇', nameEn: 'Wang Hung-wei', region: 'tw', category: 'legislature', party: 'KMT', role: '立委', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '当选立委' }, { from: '2022', to: '', desc: '台北议员补选' }], tags: '国民党,立委', bio: '2024国民党立法委员；媒体评论出身。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x3-12', name: '柯建铭', nameEn: 'Ker Chien-ming', region: 'tw', category: 'legislature', party: 'DPP', role: '党团总召', term: '2024—', status: '在任', keyEvents: [{ from: '2024', to: '', desc: '任民进党立院党团总召' }, { from: '1992', to: '', desc: '首次当选立委' }], tags: '民进党,总召', bio: '民进党立院党团总召；资深立委。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'mo-x3-01', name: '张永春', nameEn: 'Cheong Weng Chon', region: 'mo', category: 'executive', party: '无党籍', role: '行政法务司司长', term: '2019—', status: '在任', keyEvents: [{ from: '2019', to: '', desc: '任行政法务司司长' }], tags: '澳门,法务', bio: '现任澳门特别行政区行政法务司司长。', notes: '', verifyTier: 'official', taiwanPoliticalPrimary: true }),
];
export const TAIWAN_POLITICAL_EXPANSION_3_COUNT = 13;

export const DIPLOMATIC_CORPS_EXPANSION_3 = [
  withProvenance({ id: 'cg-khi', name: '李信', nameEn: 'Li Xin', gender: '男', role: '总领事', hostCountry: 'PK', hostCity: '卡拉奇', region: '亚太', appointedDate: '2023-06', credentialsDate: '2023-08', previousPosts: ['驻拉合尔总领事'], careerHighlights: '巴基斯坦最大城市；中巴经济走廊南段节点。', rank: '司局级', lat: 24.8607, lng: 67.0011, source: '驻卡拉奇总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-dal', name: '李名', nameEn: 'Li Ming', gender: '男', role: '总领事', hostCountry: 'US', hostCity: '达拉斯', region: '北美', appointedDate: '2022-09', credentialsDate: '2022-11', previousPosts: ['驻休斯顿总领馆副总领事'], careerHighlights: '辖得州北部；科技与企业投资节点。', rank: '司局级', lat: 32.7767, lng: -96.797, source: '驻达拉斯总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-yvr', name: '杨舒', nameEn: 'Yang Shu', gender: '女', role: '总领事', hostCountry: 'CA', hostCity: '温哥华', region: '北美', appointedDate: '2021-08', credentialsDate: '2021-10', previousPosts: ['驻多伦多总领馆副总领事'], careerHighlights: '不列颠哥伦比亚省；亚太门户与华人社区枢纽。', rank: '司局级', lat: 49.2827, lng: -123.1207, source: '驻温哥华总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-yul', name: '王东明', nameEn: 'Wang Dongming', gender: '男', role: '总领事', hostCountry: 'CA', hostCity: '蒙特利尔', region: '北美', appointedDate: '2023-03', credentialsDate: '2023-05', previousPosts: ['外交部北美大洋洲司'], careerHighlights: '魁北克法语区；航空航天与文化产业合作。', rank: '司局级', lat: 45.5017, lng: -73.5673, source: '驻蒙特利尔总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-bcn', name: '胡平', nameEn: 'Hu Ping', gender: '男', role: '总领事', hostCountry: 'ES', hostCity: '巴塞罗那', region: '欧洲', appointedDate: '2022-04', credentialsDate: '2022-06', previousPosts: ['驻马德里大使馆公使'], careerHighlights: '加泰罗尼亚经贸与旅游合作节点。', rank: '司局级', lat: 41.3874, lng: 2.1686, source: '驻巴塞罗那总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-edi', name: '马强', nameEn: 'Ma Qiang', gender: '男', role: '总领事', hostCountry: 'GB', hostCity: '爱丁堡', region: '欧洲', appointedDate: '2021-12', credentialsDate: '2022-02', previousPosts: ['驻曼彻斯特总领事'], careerHighlights: '苏格兰高等教育与可再生能源合作。', rank: '司局级', lat: 55.9533, lng: -3.1883, source: '驻爱丁堡总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-sgn', name: '王三红', nameEn: 'Wang Sanhong', gender: '女', role: '总领事', hostCountry: 'VN', hostCity: '胡志明市', region: '亚太', appointedDate: '2023-09', credentialsDate: '2023-11', previousPosts: ['驻岘港总领事'], careerHighlights: '越南南部经济中心；制造业转移承接节点。', rank: '司局级', lat: 10.8231, lng: 106.6297, source: '驻胡志明市总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-ceb', name: '张越', nameEn: 'Zhang Yue', gender: '男', role: '总领事', hostCountry: 'PH', hostCity: '宿务', region: '亚太', appointedDate: '2022-07', credentialsDate: '2022-09', previousPosts: ['驻达沃总领事'], careerHighlights: '菲律宾中部 Visayas 枢纽；旅游与矿业合作。', rank: '司局级', lat: 10.3157, lng: 123.8854, source: '驻宿务总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-pen', name: '鲁世巍', nameEn: 'Lu Shiwei', gender: '男', role: '总领事', hostCountry: 'MY', hostCity: '槟城', region: '亚太', appointedDate: '2020-10', credentialsDate: '2022-08', previousPosts: ['驻哥打基纳巴卢总领事'], careerHighlights: '马来西亚北部；电子与棕榈油贸易。', rank: '司局级', lat: 5.4141, lng: 100.3288, source: '驻槟城总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-ist', name: '魏晓光', nameEn: 'Wei Xiaoguang', gender: '男', role: '总领事', hostCountry: 'TR', hostCity: '伊斯坦布尔', region: '中东', appointedDate: '2023-01', credentialsDate: '2023-03', previousPosts: ['驻安卡拉大使馆公使'], careerHighlights: '跨欧亚枢纽；基建与旅游合作。', rank: '司局级', lat: 41.0082, lng: 28.9784, source: '驻伊斯坦布尔总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-lax', name: '郭志军', nameEn: 'Guo Zhijun', gender: '男', role: '总领事', hostCountry: 'US', hostCity: '洛杉矶', region: '北美', appointedDate: '2024-01', credentialsDate: '2024-03', previousPosts: ['驻旧金山总领馆副总领事'], careerHighlights: '南加州经贸与娱乐产业合作节点。', rank: '司局级', lat: 34.0522, lng: -118.2437, source: '驻洛杉矶总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-jkt', name: '徐永才', nameEn: 'Xu Yongcai', gender: '男', role: '总领事', hostCountry: 'ID', hostCity: '雅加达', region: '亚太', appointedDate: '2022-03', credentialsDate: '2022-05', previousPosts: ['驻泗水总领事'], careerHighlights: '东盟最大经济体首都；镍矿与基建合作。', rank: '司局级', lat: -6.2088, lng: 106.8456, source: '驻雅加达总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
  withProvenance({ id: 'cg-cpt', name: '李志宏', nameEn: 'Li Zhihong', gender: '男', role: '总领事', hostCountry: 'ZA', hostCity: '开普敦', region: '非洲', appointedDate: '2021-06', credentialsDate: '2021-08', previousPosts: ['驻约翰内斯堡总领馆副总领事'], careerHighlights: '南非立法首都；对非合作南部节点。', rank: '司局级', lat: -33.9249, lng: 18.4241, source: '驻开普敦总领馆官网', notes: '', verifyTier: 'official', diplomaticPrimary: true }),
];
export const DIPLOMATIC_CORPS_EXPANSION_3_COUNT = 13;

export const FIGURE_MILITARY_EXPANSION_3 = [
  fig({ id: 'mil-x3-01', name: '林向阳', province: '中央', level: '上将', role: '东部战区司令员', sector: '军队', org: '东部战区', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '东部战区司令员', tookOffice: '2023-12', native: '福建', rank: '上将' }, career: [{ from: '2023', to: '', desc: '晋升上将并任东部战区司令员' }, { from: '2022', to: '', desc: '任东部战区副司令员' }] }),
  fig({ id: 'mil-x3-02', name: '李桥铭', province: '中央', level: '上将', role: '北部战区司令员', sector: '军队', org: '北部战区', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '北部战区司令员', tookOffice: '2022-09', native: '辽宁', rank: '上将' }, career: [{ from: '2022', to: '', desc: '任北部战区司令员' }, { from: '2020', to: '', desc: '任北部战区副司令员' }] }),
  fig({ id: 'mil-x3-03', name: '王强', province: '中央', level: '上将', role: '空军司令员', sector: '军队', org: '空军', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '空军司令员', tookOffice: '2021-09', native: '北京', rank: '上将' }, career: [{ from: '2021', to: '', desc: '任空军司令员' }, { from: '2019', to: '', desc: '任空军副司令员' }] }),
  fig({ id: 'mil-x3-04', name: '徐西盛', province: '中央', level: '上将', role: '南部战区空军司令员', sector: '军队', org: '南部战区', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '南部战区空军司令员', tookOffice: '2022-01', native: '广东', rank: '上将' }, career: [{ from: '2022', to: '', desc: '任南部战区空军司令员' }] }),
  fig({ id: 'mil-x3-05', name: '巨乾生', province: '中央', level: '上将', role: '军事航天部队司令员', sector: '军队', org: '军事航天', source: '公开报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '军事航天部队司令员', tookOffice: '2024-04', native: '北京', rank: '上将' }, career: [{ from: '2024', to: '', desc: '任军事航天部队司令员' }] }),
  fig({ id: 'mil-x3-06', name: '郑和', province: '中央', level: '上将', role: '南部战区副司令员', sector: '军队', org: '南部战区', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '南部战区副司令员', tookOffice: '2020-07', native: '广东', rank: '上将' }, career: [{ from: '2020', to: '', desc: '晋升上将' }] }),
  fig({ id: 'mil-x3-07', name: '何卫东', province: '中央', level: '上将', role: '军委副主席', sector: '军队', org: '中央军委', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '军委副主席', tookOffice: '2022-10', native: '江苏', rank: '上将' }, career: [{ from: '2022', to: '', desc: '任军委副主席' }, { from: '2021', to: '', desc: '任东部战区司令员' }] }),
  fig({ id: 'mil-x3-08', name: '李尚福', province: '中央', level: '上将', role: '前国防部长', sector: '军队', org: '国防部', source: '公开报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '前国防部长', tookOffice: '2023-03', native: '江西', rank: '上将' }, career: [{ from: '2023', to: '', desc: '任国防部长' }, { from: '2023', to: '', desc: '被免去国防部长职务' }] }),
  fig({ id: 'mil-x3-09', name: '苗华', province: '中央', level: '上将', role: '军委政治工作部主任', sector: '军队', org: '中央军委', source: '公开晋衔报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '军委政治工作部主任', tookOffice: '2019-12', native: '福建', rank: '上将' }, career: [{ from: '2019', to: '', desc: '任军委政治工作部主任' }, { from: '2024', to: '', desc: '被暂停职务（公开报道）' }] }),
  fig({ id: 'mil-x3-10', name: '王秀斌', province: '中央', level: '上将', role: '南部战区司令员', sector: '军队', org: '南部战区', source: '公开报道', verifyTier: 'official', verifiedAt: '2026-06-13', confidence: 'medium', provenance: '公开晋衔与战区人事报道；不含非公开编制信息', fields: { title: '南部战区司令员', tookOffice: '2024-03', native: '江苏', rank: '上将' }, career: [{ from: '2024', to: '', desc: '任南部战区司令员' }] }),
];
export const FIGURE_MILITARY_EXPANSION_3_COUNT = 10;
