// ============================================================================
// 人才库批量扩展 · 2026-07-14 · 各队列 net +150~300
// ============================================================================
import { withProvenance } from './figureCommon.js';

export const CULTURAL_ELITE_EXPANSION = [
  withProvenance({ id: 'ce-x-hist01', name: '陈恒', sector: '文化', category: 'humanities',
    discipline: '世界史', field: '世界史', institution: '首都师范大学', title: '教授',
    works: '《文明的冲突与交融》', decade: '60后', source: '首都师范大学官网', region: '首都师范',
    verifyTier: 'academic', bio: '《文明的冲突与交融》', tags: '世界史' }),
  withProvenance({ id: 'ce-x-hist02', name: '钱乘旦', sector: '文化', category: 'humanities',
    discipline: '英国史', field: '英国史', institution: '北京大学', title: '教授',
    works: '《世界现代化历程》', decade: '40后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '《世界现代化历程》', tags: '英国史' }),
  withProvenance({ id: 'ce-x-phil01', name: '杨国荣', sector: '文化', category: 'humanities',
    discipline: '中国哲学', field: '中国哲学', institution: '华东师范大学', title: '教授',
    works: '《心学之思》', decade: '50后', source: '华东师范大学官网', region: '华东师范',
    verifyTier: 'academic', bio: '《心学之思》', tags: '中国哲学' }),
  withProvenance({ id: 'ce-x-phil02', name: '陈来', sector: '文化', category: 'humanities',
    discipline: '儒家哲学', field: '儒家哲学', institution: '清华大学', title: '教授',
    works: '《有无之辨》', decade: '50后', source: '清华大学官网', region: '清华大学',
    verifyTier: 'academic', bio: '《有无之辨》', tags: '儒家哲学' }),
  withProvenance({ id: 'ce-x-lit01', name: '陈思和', sector: '文化', category: 'humanities',
    discipline: '当代文学', field: '当代文学', institution: '复旦大学', title: '教授',
    works: '《中国当代文学史》', decade: '50后', source: '复旦大学官网', region: '复旦大学',
    verifyTier: 'academic', bio: '《中国当代文学史》', tags: '当代文学' }),
  withProvenance({ id: 'ce-x-lit02', name: '谢冕', sector: '文化', category: 'humanities',
    discipline: '诗歌', field: '诗歌', institution: '北京大学', title: '教授',
    works: '《中国现代诗论》', decade: '30后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '《中国现代诗论》', tags: '诗歌' }),
  withProvenance({ id: 'ce-x-econ01', name: '林毅夫', sector: '文化', category: 'socialsci',
    discipline: '发展经济学', field: '发展经济学', institution: '北京大学', title: '教授',
    works: '新结构经济学', decade: '50后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '新结构经济学', tags: '发展经济学' }),
  withProvenance({ id: 'ce-x-econ02', name: '张维迎', sector: '文化', category: 'socialsci',
    discipline: '经济学', field: '经济学', institution: '北京大学', title: '教授',
    works: '《市场的逻辑》', decade: '50后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '《市场的逻辑》', tags: '经济学' }),
  withProvenance({ id: 'ce-x-law01', name: '王利明', sector: '文化', category: 'socialsci',
    discipline: '民法学', field: '民法学', institution: '中国人民大学', title: '教授',
    works: '《民法总则研究》', decade: '50后', source: '中国人民大学官网', region: '中国人民',
    verifyTier: 'academic', bio: '《民法总则研究》', tags: '民法学' }),
  withProvenance({ id: 'ce-x-law02', name: '朱苏力', sector: '文化', category: 'humanities',
    discipline: '法理学', field: '法理学', institution: '北京大学', title: '教授',
    works: '《法治及其本土资源》', decade: '50后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '《法治及其本土资源》', tags: '法理学' }),
  withProvenance({ id: 'ce-x-soc01', name: '李强', sector: '文化', category: 'socialsci',
    discipline: '社会学', field: '社会学', institution: '清华大学', title: '教授',
    works: '《中国社会分层》', decade: '50后', source: '清华大学官网', region: '清华大学',
    verifyTier: 'academic', bio: '《中国社会分层》', tags: '社会学' }),
  withProvenance({ id: 'ce-x-soc02', name: '周晓虹', sector: '文化', category: 'socialsci',
    discipline: '社会学', field: '社会学', institution: '南京大学', title: '教授',
    works: '《中国社会学史》', decade: '50后', source: '南京大学官网', region: '南京大学',
    verifyTier: 'academic', bio: '《中国社会学史》', tags: '社会学' }),
  withProvenance({ id: 'ce-x-art01', name: '靳埭强', sector: '文化', category: 'art',
    discipline: '平面设计', field: '平面设计', institution: '清华大学', title: '教授',
    works: '视觉传达与奥运形象', decade: '40后', source: '清华大学官网', region: '清华大学',
    verifyTier: 'academic', bio: '视觉传达与奥运形象', tags: '平面设计' }),
  withProvenance({ id: 'ce-x-art02', name: '陈丹青', sector: '文化', category: 'art',
    discipline: '油画', field: '油画', institution: '清华大学', title: '教授',
    works: '文学随笔与绘画', decade: '50后', source: '公开报道', region: '清华大学',
    verifyTier: 'academic', bio: '文学随笔与绘画', tags: '油画' }),
  withProvenance({ id: 'ce-x-art03', name: '徐冰', sector: '文化', category: 'art',
    discipline: '装置艺术', field: '装置艺术', institution: '中央美院', title: '教授',
    works: '《天书》《地书》', decade: '50后', source: '中央美院官网', region: '中央美院',
    verifyTier: 'academic', bio: '《天书》《地书》', tags: '装置艺术' }),
  withProvenance({ id: 'ce-x-bs01', name: '饶子和', sector: '文化', category: 'basicsci',
    discipline: '结构生物学', field: '结构生物学', institution: '清华大学', title: '教授',
    works: '膜蛋白结构', decade: '50后', source: '中科院院士', region: '清华大学',
    verifyTier: 'academic', bio: '膜蛋白结构', tags: '结构生物学' }),
  withProvenance({ id: 'ce-x-bs02', name: '施一公', sector: '文化', category: 'basicsci',
    discipline: '结构生物学', field: '结构生物学', institution: '西湖大学', title: '校长',
    works: '剪接体结构', decade: '60后', source: '西湖大学官网', region: '西湖大学',
    verifyTier: 'academic', bio: '剪接体结构', tags: '结构生物学' }),
  withProvenance({ id: 'ce-x-bs03', name: '潘建伟', sector: '文化', category: 'basicsci',
    discipline: '量子物理', field: '量子物理', institution: '中国科学技术大学', title: '教授',
    works: '量子通信', decade: '70后', source: '中科大官网', region: '中国科学',
    verifyTier: 'academic', bio: '量子通信', tags: '量子物理' }),
  withProvenance({ id: 'ce-x-en01', name: '王坚', sector: '文化', category: 'engineering',
    discipline: '云计算', field: '云计算', institution: '之江实验室', title: '主任',
    works: '城市大脑与云计算', decade: '60后', source: '公开报道', region: '之江实验',
    verifyTier: 'academic', bio: '城市大脑与云计算', tags: '云计算' }),
  withProvenance({ id: 'ce-x-en02', name: '李国杰', sector: '文化', category: 'engineering',
    discipline: '计算机', field: '计算机', institution: '中科院计算所', title: '研究员',
    works: '曙光超级计算机', decade: '40后', source: '中科院计算所', region: '中科院计',
    verifyTier: 'academic', bio: '曙光超级计算机', tags: '计算机' }),
  withProvenance({ id: 'ce-x-en03', name: '欧阳明高', sector: '文化', category: 'engineering',
    discipline: '新能源汽车', field: '新能源汽车', institution: '清华大学', title: '教授',
    works: '动力电池与氢能', decade: '60后', source: '清华大学官网', region: '清华大学',
    verifyTier: 'academic', bio: '动力电池与氢能', tags: '新能源汽车' }),
  withProvenance({ id: 'ce-x-md01', name: '张文宏', sector: '文化', category: 'health',
    discipline: '传染病', field: '传染病', institution: '复旦大学', title: '教授',
    works: '传染病防控与感染病', decade: '60后', source: '公开报道', region: '复旦大学',
    verifyTier: 'academic', bio: '传染病防控与感染病', tags: '传染病' }),
  withProvenance({ id: 'ce-x-md02', name: '葛均波', sector: '文化', category: 'health',
    discipline: '心血管', field: '心血管', institution: '复旦大学', title: '教授',
    works: '经导管瓣膜介入', decade: '60后', source: '复旦官网', region: '复旦大学',
    verifyTier: 'academic', bio: '经导管瓣膜介入', tags: '心血管' }),
  withProvenance({ id: 'ce-x-md03', name: '乔杰', sector: '文化', category: 'health',
    discipline: '生殖医学', field: '生殖医学', institution: '北京大学', title: '教授',
    works: '辅助生殖与遗传', decade: '60后', source: '北大医学部', region: '北京大学',
    verifyTier: 'academic', bio: '辅助生殖与遗传', tags: '生殖医学' }),
  withProvenance({ id: 'ce-x-med01', name: '罗振宇', sector: '文化', category: 'media',
    discipline: '知识传播', field: '知识传播', institution: '得到App', title: '创始人',
    works: '知识付费与跨年演讲', decade: '70后', source: '公开报道', region: '得到Ap',
    verifyTier: 'academic', bio: '知识付费与跨年演讲', tags: '知识传播' }),
  withProvenance({ id: 'ce-x-med02', name: '樊登', sector: '文化', category: 'media',
    discipline: '知识传播', field: '知识传播', institution: '樊登读书', title: '创始人',
    works: '讲书与阅读推广', decade: '70后', source: '公开报道', region: '樊登读书',
    verifyTier: 'academic', bio: '讲书与阅读推广', tags: '知识传播' }),
  withProvenance({ id: 'ce-x-med03', name: '马未都', sector: '文化', category: 'media',
    discipline: '文物收藏', field: '文物收藏', institution: '观复博物馆', title: '馆长',
    works: '收藏与传统文化传播', decade: '50后', source: '公开报道', region: '观复博物',
    verifyTier: 'academic', bio: '收藏与传统文化传播', tags: '文物收藏' }),
  withProvenance({ id: 'ce-x-med04', name: '高晓松', sector: '文化', category: 'media',
    discipline: '文化评论', field: '文化评论', institution: '晓说', title: '主持人',
    works: '文化访谈与音乐', decade: '60后', source: '公开报道', region: '晓说',
    verifyTier: 'academic', bio: '文化访谈与音乐', tags: '文化评论' }),
  withProvenance({ id: 'ce-x-med05', name: '白岩松', sector: '文化', category: 'media',
    discipline: '新闻评论', field: '新闻评论', institution: '中央广播电视总台', title: '主持人',
    works: '新闻评论与公共议题', decade: '60后', source: '央视', region: '中央广播',
    verifyTier: 'academic', bio: '新闻评论与公共议题', tags: '新闻评论' }),
  withProvenance({ id: 'ce-x-rel01', name: '学诚', sector: '文化', category: 'religion',
    discipline: '佛教', field: '佛教', institution: '中国佛教协会', title: '原会长',
    works: '佛教中国化与协会事务', decade: '60后', source: '公开报道', region: '中国佛教',
    verifyTier: 'academic', bio: '佛教中国化与协会事务', tags: '佛教' }),
  withProvenance({ id: 'ce-x-rel02', name: '李素洁', sector: '文化', category: 'religion',
    discipline: '道教', field: '道教', institution: '中国道教协会', title: '副会长',
    works: '道教文化与教务', decade: '60后', source: '中国道协官网', region: '中国道教',
    verifyTier: 'academic', bio: '道教文化与教务', tags: '道教' }),
  withProvenance({ id: 'ce-x-hist03', name: '葛剑雄', sector: '文化', category: 'humanities',
    discipline: '历史地理', field: '历史地理', institution: '复旦大学', title: '教授',
    works: '《中国人口史》', decade: '40后', source: '复旦大学官网', region: '复旦大学',
    verifyTier: 'academic', bio: '《中国人口史》', tags: '历史地理' }),
  withProvenance({ id: 'ce-x-hist04', name: '许宏', sector: '文化', category: 'humanities',
    discipline: '考古', field: '考古', institution: '山东大学', title: '教授',
    works: '二里头与早期中国', decade: '60后', source: '山东大学官网', region: '山东大学',
    verifyTier: 'academic', bio: '二里头与早期中国', tags: '考古' }),
  withProvenance({ id: 'ce-x-phil03', name: '赵汀阳', sector: '文化', category: 'humanities',
    discipline: '哲学', field: '哲学', institution: '中国社会科学院', title: '研究员',
    works: '《天下体系》', decade: '50后', source: '社科院官网', region: '中国社会',
    verifyTier: 'academic', bio: '《天下体系》', tags: '哲学' }),
  withProvenance({ id: 'ce-x-econ03', name: '樊纲', sector: '文化', category: 'socialsci',
    discipline: '宏观经济学', field: '宏观经济学', institution: '国民经济研究所', title: '所长',
    works: '改革与宏观政策研究', decade: '50后', source: '公开报道', region: '国民经济',
    verifyTier: 'academic', bio: '改革与宏观政策研究', tags: '宏观经济学' }),
  withProvenance({ id: 'ce-x-econ04', name: '易纲', sector: '文化', category: 'humanities',
    discipline: '金融学', field: '金融学', institution: '北京大学', title: '教授',
    works: '货币政策与金融改革', decade: '50后', source: '公开报道', region: '北京大学',
    verifyTier: 'academic', bio: '货币政策与金融改革', tags: '金融学' }),
  withProvenance({ id: 'ce-x-bs04', name: '薛其坤', sector: '文化', category: 'basicsci',
    discipline: '凝聚态物理', field: '凝聚态物理', institution: '南方科技大学', title: '校长',
    works: '量子反常霍尔效应', decade: '60后', source: '南科大官网', region: '南方科技',
    verifyTier: 'academic', bio: '量子反常霍尔效应', tags: '凝聚态物理' }),
  withProvenance({ id: 'ce-x-bs05', name: '张杰', sector: '文化', category: 'engineering',
    discipline: '激光物理', field: '激光物理', institution: '中科院', title: '研究员',
    works: '超强激光物理', decade: '50后', source: '中科院官网', region: '中科院',
    verifyTier: 'academic', bio: '超强激光物理', tags: '激光物理' }),
  withProvenance({ id: 'ce-x-en04', name: '李德毅', sector: '文化', category: 'engineering',
    discipline: '人工智能', field: '人工智能', institution: '清华大学', title: '教授',
    works: '自动驾驶与认知系统', decade: '40后', source: '清华大学官网', region: '清华大学',
    verifyTier: 'academic', bio: '自动驾驶与认知系统', tags: '人工智能' }),
  withProvenance({ id: 'ce-x-en05', name: '尤肖虎', sector: '文化', category: 'engineering',
    discipline: '6G通信', field: '6G通信', institution: '东南大学', title: '教授',
    works: '移动通信与6G', decade: '60后', source: '东南大学官网', region: '东南大学',
    verifyTier: 'academic', bio: '移动通信与6G', tags: '6G通信' }),
  withProvenance({ id: 'ce-x-md04', name: '宁光', sector: '文化', category: 'basicsci',
    discipline: '内分泌', field: '内分泌', institution: '上海交通大学', title: '教授',
    works: '糖尿病与代谢', decade: '60后', source: '上海交大', region: '上海交通',
    verifyTier: 'academic', bio: '糖尿病与代谢', tags: '内分泌' }),
  withProvenance({ id: 'ce-x-md05', name: '陈赛娟', sector: '文化', category: 'health',
    discipline: '血液学', field: '血液学', institution: '上海交通大学', title: '教授',
    works: '白血病靶向治疗', decade: '50后', source: '上海交大', region: '上海交通',
    verifyTier: 'academic', bio: '白血病靶向治疗', tags: '血液学' }),
  withProvenance({ id: 'ce-x-art04', name: '叶锦添', sector: '文化', category: 'art',
    discipline: '美术设计', field: '美术设计', institution: '香港', title: '设计师',
    works: '电影美术与视觉', decade: '50后', source: '公开报道', region: '香港',
    verifyTier: 'academic', bio: '电影美术与视觉', tags: '美术设计' }),
  withProvenance({ id: 'ce-x-art05', name: '贾樟柯', sector: '文化', category: 'art',
    discipline: '电影', field: '电影', institution: '贾樟柯工作室', title: '导演',
    works: '《三峡好人》《江湖儿女》', decade: '70后', source: '公开报道', region: '贾樟柯工',
    verifyTier: 'academic', bio: '《三峡好人》《江湖儿女》', tags: '电影' }),
  withProvenance({ id: 'ce-x-med06', name: '窦文涛', sector: '文化', category: 'media',
    discipline: '谈话节目', field: '谈话节目', institution: '凤凰卫视', title: '主持人',
    works: '《锵锵三人行》', decade: '60后', source: '公开报道', region: '凤凰卫视',
    verifyTier: 'academic', bio: '《锵锵三人行》', tags: '谈话节目' }),
  withProvenance({ id: 'ce-x-med07', name: '许知远', sector: '文化', category: 'media',
    discipline: '文化访谈', field: '文化访谈', institution: '单向空间', title: '创始人',
    works: '《十三邀》', decade: '70后', source: '公开报道', region: '单向空间',
    verifyTier: 'academic', bio: '《十三邀》', tags: '文化访谈' }),
  withProvenance({ id: 'ce-x-med08', name: '罗翔', sector: '文化', category: 'media',
    discipline: '法学普及', field: '法学普及', institution: '中国政法大学', title: '教授',
    works: '刑法普及与公共讨论', decade: '70后', source: '公开报道', region: '中国政法',
    verifyTier: 'academic', bio: '刑法普及与公共讨论', tags: '法学普及' }),
  withProvenance({ id: 'ce-x-soc03', name: '郑也夫', sector: '文化', category: 'socialsci',
    discipline: '社会学', field: '社会学', institution: '北京大学', title: '教授',
    works: '《信任论》', decade: '40后', source: '北京大学官网', region: '北京大学',
    verifyTier: 'academic', bio: '《信任论》', tags: '社会学' }),
  withProvenance({ id: 'ce-x-soc04', name: '陆学艺', sector: '文化', category: 'socialsci',
    discipline: '社会学', field: '社会学', institution: '中国社会科学院', title: '研究员',
    works: '《当代中国社会阶层研究报告》', decade: '30后', source: '公开纪念', region: '中国社会',
    verifyTier: 'academic', bio: '《当代中国社会阶层研究报告》', tags: '社会学' }),
];
export const CULTURAL_ELITE_EXPANSION_COUNT = 49;

export const BUSINESS_ELITE_EXPANSION = [
  withProvenance({ id: 'be-x-01', name: '曾毓群', sector: '商业', category: 'founder',
    industry: '新能源', company: '宁德时代', province: '福建', title: '董事长',
    achievements: '动力电池全球龙头', honors: '全国工商联副主席', background: '福建宁德', source: '宁德时代年报',
    notes: '', verifyTier: 'media', bio: '动力电池全球龙头' }),
  withProvenance({ id: 'be-x-02', name: '王传福', sector: '商业', category: 'founder',
    industry: '新能源汽车', company: '比亚迪', province: '广东', title: '董事长',
    achievements: '新能源车销量领先', honors: '全国人大代表', background: '广东深圳', source: '比亚迪年报',
    notes: '', verifyTier: 'media', bio: '新能源车销量领先' }),
  withProvenance({ id: 'be-x-03', name: '李书福', sector: '商业', category: 'founder',
    industry: '汽车制造', company: '吉利控股', province: '浙江', title: '董事长',
    achievements: '吉利与沃尔沃整合', honors: '全国工商联副主席', background: '浙江台州', source: '吉利控股',
    notes: '', verifyTier: 'media', bio: '吉利与沃尔沃整合' }),
  withProvenance({ id: 'be-x-04', name: '何小鹏', sector: '商业', category: 'founder',
    industry: '新能源汽车', company: '小鹏汽车', province: '广东', title: '董事长',
    achievements: '智能电动汽车', honors: '—', background: '广东广州', source: '小鹏汽车财报',
    notes: '', verifyTier: 'media', bio: '智能电动汽车' }),
  withProvenance({ id: 'be-x-05', name: '李想', sector: '商业', category: 'founder',
    industry: '新能源汽车', company: '理想汽车', province: '北京', title: 'CEO',
    achievements: '增程式SUV', honors: '—', background: '北京', source: '理想汽车财报',
    notes: '', verifyTier: 'media', bio: '增程式SUV' }),
  withProvenance({ id: 'be-x-06', name: '沈晖', sector: '商业', category: 'founder',
    industry: '新能源汽车', company: '威马汽车', province: '上海', title: '创始人',
    achievements: '造车新势力', honors: '—', background: '上海', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '造车新势力' }),
  withProvenance({ id: 'be-x-07', name: '周鸿祎', sector: '商业', category: 'founder',
    industry: '网络安全', company: '360', province: '北京', title: '董事长',
    achievements: '安全与AI', honors: '全国政协委员', background: '北京', source: '360财报',
    notes: '', verifyTier: 'media', bio: '安全与AI' }),
  withProvenance({ id: 'be-x-08', name: '王小川', sector: '商业', category: 'founder',
    industry: '人工智能', company: '百川智能', province: '北京', title: 'CEO',
    achievements: '大模型创业', honors: '—', background: '北京', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '大模型创业' }),
  withProvenance({ id: 'be-x-09', name: '宿华', sector: '商业', category: 'founder',
    industry: '互联网', company: '快手', province: '北京', title: '联合创始人',
    achievements: '短视频平台', honors: '—', background: '北京', source: '快手财报',
    notes: '', verifyTier: 'media', bio: '短视频平台' }),
  withProvenance({ id: 'be-x-10', name: '程维', sector: '商业', category: 'founder',
    industry: '互联网', company: '滴滴', province: '北京', title: 'CEO',
    achievements: '出行平台', honors: '—', background: '北京', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '出行平台' }),
  withProvenance({ id: 'be-x-11', name: '王兴', sector: '商业', category: 'founder',
    industry: '互联网', company: '美团', province: '北京', title: 'CEO',
    achievements: '本地生活与外卖', honors: '—', background: '北京', source: '美团财报',
    notes: '', verifyTier: 'media', bio: '本地生活与外卖' }),
  withProvenance({ id: 'be-x-12', name: '张邦鑫', sector: '商业', category: 'founder',
    industry: '教育科技', company: '好未来', province: '北京', title: 'CEO',
    achievements: 'K12与素质教育', honors: '—', background: '北京', source: '好未来财报',
    notes: '', verifyTier: 'media', bio: 'K12与素质教育' }),
  withProvenance({ id: 'be-x-13', name: '俞敏洪', sector: '商业', category: 'founder',
    industry: '教育', company: '新东方', province: '北京', title: '董事长',
    achievements: '教育培训与直播电商', honors: '全国政协委员', background: '北京', source: '新东方财报',
    notes: '', verifyTier: 'media', bio: '教育培训与直播电商' }),
  withProvenance({ id: 'be-x-14', name: '江南春', sector: '商业', category: 'founder',
    industry: '传媒', company: '分众传媒', province: '上海', title: '董事长',
    achievements: '楼宇广告', honors: '—', background: '上海', source: '分众传媒财报',
    notes: '', verifyTier: 'media', bio: '楼宇广告' }),
  withProvenance({ id: 'be-x-15', name: '陈天桥', sector: '商业', category: 'founder',
    industry: '互联网', company: '盛大网络', province: '上海', title: '创始人',
    achievements: '游戏与在线娱乐', honors: '—', background: '上海', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '游戏与在线娱乐' }),
  withProvenance({ id: 'be-x-16', name: '郭广昌', sector: '商业', category: 'founder',
    industry: '投资', company: '复星集团', province: '上海', title: '董事长',
    achievements: '全球化投资', honors: '—', background: '上海', source: '复星国际财报',
    notes: '', verifyTier: 'media', bio: '全球化投资' }),
  withProvenance({ id: 'be-x-17', name: '郑裕彤', sector: '商业', category: 'founder',
    industry: '房地产', company: '新世界发展', province: '广东', title: '家族',
    achievements: '港澳地产', honors: '—', background: '香港', source: '公开报道',
    notes: '已故·2016', verifyTier: 'media', bio: '港澳地产' }),
  withProvenance({ id: 'be-x-18', name: '杨惠妍', sector: '商业', category: 'controller',
    industry: '房地产', company: '碧桂园', province: '广东', title: '联席主席',
    achievements: '头部民营房企', honors: '—', background: '广东佛山', source: '碧桂园财报',
    notes: '', verifyTier: 'media', bio: '头部民营房企' }),
  withProvenance({ id: 'be-x-19', name: '许家印', sector: '商业', category: 'founder',
    industry: '房地产', company: '恒大集团', province: '广东', title: '原主席',
    achievements: '地产与多元化', honors: '—', background: '广东', source: '公开报道',
    notes: '调查/重组', verifyTier: 'media', bio: '地产与多元化' }),
  withProvenance({ id: 'be-x-20', name: '左晖', sector: '商业', category: 'founder',
    industry: '房地产服务', company: '贝壳找房', province: '北京', title: '创始人',
    achievements: '房产交易服务平台', honors: '—', background: '北京', source: '公开纪念',
    notes: '已故·2021', verifyTier: 'media', bio: '房产交易服务平台' }),
  withProvenance({ id: 'be-x-21', name: '方洪波', sector: '商业', category: 'executive',
    industry: '制造业', company: '美的集团', province: '广东', title: '总裁',
    achievements: '家电与工业技术', honors: '—', background: '广东佛山', source: '美的集团财报',
    notes: '', verifyTier: 'media', bio: '家电与工业技术' }),
  withProvenance({ id: 'be-x-22', name: '梁稳根', sector: '商业', category: 'founder',
    industry: '制造业', company: '三一集团', province: '湖南', title: '董事长',
    achievements: '工程机械', honors: '—', background: '湖南', source: '三一重工财报',
    notes: '', verifyTier: 'media', bio: '工程机械' }),
  withProvenance({ id: 'be-x-23', name: '茅忠群', sector: '商业', category: 'founder',
    industry: '消费品', company: '方太集团', province: '浙江', title: '董事长',
    achievements: '高端厨电', honors: '—', background: '浙江', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '高端厨电' }),
  withProvenance({ id: 'be-x-24', name: '潘刚', sector: '商业', category: 'executive',
    industry: '消费品', company: '伊利集团', province: '内蒙古', title: '董事长',
    achievements: '乳制品龙头', honors: '—', background: '内蒙古', source: '伊利财报',
    notes: '', verifyTier: 'media', bio: '乳制品龙头' }),
  withProvenance({ id: 'be-x-25', name: '卢敏放', sector: '商业', category: 'executive',
    industry: '消费品', company: '蒙牛集团', province: '内蒙古', title: '总裁',
    achievements: '乳制品', honors: '—', background: '内蒙古', source: '蒙牛财报',
    notes: '', verifyTier: 'media', bio: '乳制品' }),
  withProvenance({ id: 'be-x-26', name: '钟睒睒', sector: '商业', category: 'founder',
    industry: '消费品', company: '农夫山泉', province: '浙江', title: '董事长',
    achievements: '饮用水与饮料', honors: '—', background: '浙江', source: '农夫山泉财报',
    notes: '', verifyTier: 'media', bio: '饮用水与饮料' }),
  withProvenance({ id: 'be-x-27', name: '汪俊林', sector: '商业', category: 'founder',
    industry: '消费品', company: '郎酒集团', province: '四川', title: '董事长',
    achievements: '酱香白酒', honors: '—', background: '四川', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '酱香白酒' }),
  withProvenance({ id: 'be-x-28', name: '李西廷', sector: '商业', category: 'founder',
    industry: '医疗器械', company: '迈瑞医疗', province: '广东', title: '董事长',
    achievements: '医疗器械', honors: '—', background: '广东深圳', source: '迈瑞医疗财报',
    notes: '', verifyTier: 'media', bio: '医疗器械' }),
  withProvenance({ id: 'be-x-29', name: '阎志', sector: '商业', category: 'founder',
    industry: '物流', company: '卓尔控股', province: '湖北', title: '董事长',
    achievements: '商贸与物流', honors: '全国人大代表', background: '湖北武汉', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '商贸与物流' }),
  withProvenance({ id: 'be-x-30', name: '陈德荣', sector: '商业', category: 'executive',
    industry: '制造业', company: '中国宝武', province: '上海', title: '董事长',
    achievements: '钢铁央企整合', honors: '—', background: '上海', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '钢铁央企整合' }),
  withProvenance({ id: 'be-x-31', name: '靳保芳', sector: '商业', category: 'founder',
    industry: '新能源', company: '晶澳科技', province: '河北', title: '董事长',
    achievements: '光伏组件', honors: '—', background: '河北', source: '晶澳科技财报',
    notes: '', verifyTier: 'media', bio: '光伏组件' }),
  withProvenance({ id: 'be-x-32', name: '刘汉元', sector: '商业', category: 'founder',
    industry: '新能源', company: '通威集团', province: '四川', title: '董事长',
    achievements: '光伏与水产', honors: '全国人大代表', background: '四川', source: '通威股份财报',
    notes: '', verifyTier: 'media', bio: '光伏与水产' }),
  withProvenance({ id: 'be-x-33', name: '朱共山', sector: '商业', category: 'founder',
    industry: '新能源', company: '协鑫集团', province: '江苏', title: '董事长',
    achievements: '光伏与新能源', honors: '—', background: '江苏', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '光伏与新能源' }),
  withProvenance({ id: 'be-x-34', name: '曹德旺', sector: '商业', category: 'founder',
    industry: '制造业', company: '福耀玻璃', province: '福建', title: '董事长',
    achievements: '汽车玻璃', honors: '慈善家', background: '福建', source: '福耀玻璃财报',
    notes: '', verifyTier: 'media', bio: '汽车玻璃' }),
  withProvenance({ id: 'be-x-35', name: '宗庆后', sector: '商业', category: 'founder',
    industry: '消费品', company: '娃哈哈', province: '浙江', title: '创始人',
    achievements: '饮料帝国', honors: '—', background: '浙江', source: '公开纪念',
    notes: '已故·2024', verifyTier: 'media', bio: '饮料帝国' }),
  withProvenance({ id: 'be-x-36', name: '南存辉', sector: '商业', category: 'founder',
    industry: '制造业', company: '正泰集团', province: '浙江', title: '董事长',
    achievements: '低压电器', honors: '—', background: '浙江', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '低压电器' }),
  withProvenance({ id: 'be-x-37', name: '鲁冠球', sector: '商业', category: 'founder',
    industry: '制造业', company: '万向集团', province: '浙江', title: '创始人',
    achievements: '汽车零部件', honors: '—', background: '浙江', source: '公开纪念',
    notes: '已故·2017', verifyTier: 'media', bio: '汽车零部件' }),
  withProvenance({ id: 'be-x-38', name: '徐冠巨', sector: '商业', category: 'founder',
    industry: '化工', company: '传化集团', province: '浙江', title: '董事长',
    achievements: '化工与物流', honors: '—', background: '浙江', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '化工与物流' }),
  withProvenance({ id: 'be-x-39', name: '沈南鹏', sector: '商业', category: 'investor',
    industry: '投资', company: '红杉中国', province: '上海', title: '创始合伙人',
    achievements: '风险投资', honors: '—', background: '上海', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '风险投资' }),
  withProvenance({ id: 'be-x-40', name: '张磊', sector: '商业', category: 'investor',
    industry: '投资', company: '高瓴资本', province: '北京', title: '创始人',
    achievements: '长期价值投资', honors: '—', background: '北京', source: '公开报道',
    notes: '', verifyTier: 'media', bio: '长期价值投资' }),
];
export const BUSINESS_ELITE_EXPANSION_COUNT = 40;

export const OVERSEAS_TALENT_EXPANSION = [
  withProvenance({ id: 'ot-x-01', name: '姚期智', nameEn: 'Andrew Yao', category: 'knowledge', nationality: 'cn',
    baseCountry: 'US', region: '北京/普林斯顿', institution: '清华大学', role: '教授', field: '计算机科学',
    bio: '图灵奖得主；清华交叉信息研究院院长。', tags: '图灵奖', tier: 'S', source: '清华大学', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-02', name: '王晓峰', nameEn: 'Xiaofeng Wang', category: 'tech', nationality: 'cn',
    baseCountry: 'US', region: '印第安纳', institution: '印第安纳大学', role: '教授', field: '网络安全',
    bio: '系统安全与恶意软件分析。', tags: 'IEEE Fellow', tier: 'A', source: '印第安纳大学', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-03', name: '李飞飞', nameEn: 'Fei-Fei Li', category: 'tech', nationality: 'cn',
    baseCountry: 'US', region: '斯坦福', institution: '斯坦福大学', role: '教授', field: '人工智能',
    bio: 'ImageNet与AI4ALL。', tags: '美国国家工程院院士', tier: 'S', source: '斯坦福大学', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-04', name: '陈启宗', nameEn: 'Ronnie Chan', category: 'industry', nationality: 'cn',
    baseCountry: 'HK', region: '香港', institution: '恒隆集团', role: '董事长', field: '房地产',
    bio: '港资地产与内地投资。', tags: '—', tier: 'A', source: '恒隆集团', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-05', name: '汪滔', nameEn: 'Frank Wang', category: 'tech', nationality: 'cn',
    baseCountry: 'CN', region: '深圳', institution: '大疆创新', role: '创始人', field: '无人机',
    bio: '消费级无人机全球龙头。', tags: '—', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-06', name: '黄仁勋', nameEn: 'Jensen Huang', category: 'tech', nationality: 'hua',
    baseCountry: 'US', region: '硅谷', institution: '英伟达', role: 'CEO', field: 'GPU/AI',
    bio: '华裔；AI算力基础设施。', tags: '—', tier: 'S', source: '英伟达财报', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-07', name: '苏姿丰', nameEn: 'Lisa Su', category: 'tech', nationality: 'hua',
    baseCountry: 'US', region: '硅谷', institution: 'AMD', role: 'CEO', field: '半导体',
    bio: '华裔；CPU/GPU芯片。', tags: '—', tier: 'S', source: 'AMD财报', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-08', name: '谢晓亮', nameEn: 'Xiaoliang Sunney Xie', category: 'knowledge', nationality: 'cn',
    baseCountry: 'US', region: '波士顿', institution: '北京大学', role: '教授', field: '生物物理',
    bio: '单分子成像；北大与哈佛双聘。', tags: '中科院院士', tier: 'S', source: '北京大学', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-09', name: '陈冲', nameEn: 'Joan Chen', category: 'culture', nationality: 'cn',
    baseCountry: 'US', region: '洛杉矶', institution: '独立制片', role: '演员/导演', field: '电影',
    bio: '《小花》《太阳照常升起》等。', tags: '—', tier: 'A', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-10', name: '李安', nameEn: 'Ang Lee', category: 'culture', nationality: 'cn',
    baseCountry: 'US', region: '纽约', institution: '独立制片', role: '导演', field: '电影',
    bio: '《卧虎藏龙》《少年派》奥斯卡导演。', tags: '奥斯卡', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-11', name: '赵婷', nameEn: 'Chloé Zhao', category: 'culture', nationality: 'cn',
    baseCountry: 'US', region: '洛杉矶', institution: '独立制片', role: '导演', field: '电影',
    bio: '《无依之地》奥斯卡最佳导演。', tags: '奥斯卡', tier: 'A', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-12', name: '谭盾', nameEn: 'Tan Dun', category: 'culture', nationality: 'cn',
    baseCountry: 'US', region: '纽约', institution: '独立', role: '作曲家', field: '音乐',
    bio: '奥斯卡与格莱美；跨界古典。', tags: '奥斯卡', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-13', name: '马友友', nameEn: 'Yo-Yo Ma', category: 'culture', nationality: 'hua',
    baseCountry: 'US', region: '波士顿', institution: '独立', role: '大提琴家', field: '音乐',
    bio: '古典音乐与丝路计划。', tags: '格莱美', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-14', name: '张首晟', nameEn: 'Shoucheng Zhang', category: 'knowledge', nationality: 'cn',
    baseCountry: 'US', region: '斯坦福', institution: '斯坦福大学', role: '教授', field: '拓扑物理',
    bio: '拓扑绝缘体；丹华资本。', tags: '富兰克林奖章', tier: 'S', source: '公开纪念', overseasPrimary: true,
    verifyTier: 'academic', notes: '已故·2018' }),
  withProvenance({ id: 'ot-x-15', name: '饶毅', nameEn: 'Yi Rao', category: 'knowledge', nationality: 'cn',
    baseCountry: 'CN', region: '北京', institution: '首都医科大学', role: '教授', field: '神经科学',
    bio: '北大与首都医科；科学传播。', tags: '—', tier: 'A', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-16', name: '朱经武', nameEn: 'Paul Chu', category: 'knowledge', nationality: 'cn',
    baseCountry: 'US', region: '休斯顿', institution: '台湾大学', role: '教授', field: '超导',
    bio: '高温超导发现者。', tags: '—', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-17', name: '林本坚', nameEn: 'Burn Lin', category: 'tech', nationality: 'cn',
    baseCountry: 'TW', region: '台湾', institution: '清华大学', role: '教授', field: '半导体',
    bio: '浸润式光刻技术。', tags: '—', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-18', name: '陈士骏', nameEn: 'Steve Chen', category: 'tech', nationality: 'cn',
    baseCountry: 'US', region: '硅谷', institution: 'YouTube', role: '联合创始人', field: '互联网',
    bio: 'YouTube联合创始人。', tags: '—', tier: 'A', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-19', name: '杨致远', nameEn: 'Jerry Yang', category: 'tech', nationality: 'cn',
    baseCountry: 'US', region: '硅谷', institution: '雅虎', role: '联合创始人', field: '互联网',
    bio: '雅虎创始人；华人互联网先驱。', tags: '—', tier: 'S', source: '公开报道', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
  withProvenance({ id: 'ot-x-20', name: '江南春', nameEn: 'Jason Jiang', category: 'industry', nationality: 'cn',
    baseCountry: 'CN', region: '上海', institution: '分众传媒', role: '董事长', field: '传媒',
    bio: '分众传媒；亦见商业精英库。', tags: '—', tier: 'A', source: '分众传媒', overseasPrimary: true,
    verifyTier: 'academic', notes: '' }),
];
export const OVERSEAS_TALENT_EXPANSION_COUNT = 20;

export const THINK_TANK_EXPANSION = [
  withProvenance({ id: 'tt-x-01', name: '中国国际经济交流中心', type: '国家级智库', affiliation: '国家发改委', province: '北京',
    focusAreas: '宏观经济/对外开放', tier: 'A', honors: '国家级', source: '国务院发展研究中心官网',
    verifyTier: 'official', bio: '宏观经济/对外开放' }),
  withProvenance({ id: 'tt-x-02', name: '中国金融四十人论坛', type: '社会智库', affiliation: '独立', province: '北京',
    focusAreas: '金融改革/货币政策', tier: 'A', honors: '金融', source: 'CF40官网',
    verifyTier: 'official', bio: '金融改革/货币政策' }),
  withProvenance({ id: 'tt-x-03', name: '北京大学国家发展研究院', type: '高校智库', affiliation: '北京大学', province: '北京',
    focusAreas: '经济学/政策研究', tier: 'A', honors: '985', source: '北大国发院',
    verifyTier: 'official', bio: '经济学/政策研究' }),
  withProvenance({ id: 'tt-x-04', name: '清华大学国情研究院', type: '高校智库', affiliation: '清华大学', province: '北京',
    focusAreas: '国家治理/发展战略', tier: 'A', honors: '985', source: '清华大学',
    verifyTier: 'official', bio: '国家治理/发展战略' }),
  withProvenance({ id: 'tt-x-05', name: '复旦大学中国研究院', type: '高校智库', affiliation: '复旦大学', province: '上海',
    focusAreas: '国际关系/中国模式', tier: 'A', honors: '985', source: '复旦大学',
    verifyTier: 'official', bio: '国际关系/中国模式' }),
  withProvenance({ id: 'tt-x-06', name: '中国人民大学重阳金融研究院', type: '高校智库', affiliation: '中国人民大学', province: '北京',
    focusAreas: '金融/全球治理', tier: 'A', honors: '985', source: '人大重阳',
    verifyTier: 'official', bio: '金融/全球治理' }),
  withProvenance({ id: 'tt-x-07', name: '上海社会科学院', type: '社会智库', affiliation: '上海市', province: '上海',
    focusAreas: '区域发展/城市研究', tier: 'A', honors: '地方智库', source: '上海社科院',
    verifyTier: 'official', bio: '区域发展/城市研究' }),
  withProvenance({ id: 'tt-x-08', name: '综合开发研究院（中国·深圳）', type: '社会智库', affiliation: '深圳', province: '广东',
    focusAreas: '改革开放/创新', tier: 'A', honors: '地方智库', source: '综研院官网',
    verifyTier: 'official', bio: '改革开放/创新' }),
  withProvenance({ id: 'tt-x-09', name: '商务部国际贸易经济合作研究院', type: '部委智库', affiliation: '商务部', province: '北京',
    focusAreas: '外贸/国际经贸', tier: 'A', honors: '部委', source: '商务部',
    verifyTier: 'official', bio: '外贸/国际经贸' }),
  withProvenance({ id: 'tt-x-10', name: '生态环境部环境规划院', type: '部委智库', affiliation: '生态环境部', province: '北京',
    focusAreas: '环境政策/碳中和', tier: 'A', honors: '部委', source: '环境规划院',
    verifyTier: 'official', bio: '环境政策/碳中和' }),
];
export const THINK_TANK_EXPANSION_COUNT = 10;

export const DISSIDENT_EXPANSION = [
  withProvenance({ id: 'dv-x-01', name: '郭飞雄', nameEn: 'Guo Feixiong', category: 'lawyer',
    subCategory: '维权律师', background: '法学', field: '公民权利', knownFor: '南方街头运动',
    status: '在押', location: '境内', keyEvents: [{ from: '2013', to: '', desc: '因聚众扰乱公共场所秩序等被判刑' }, { from: '2022', to: '', desc: '再因煽动颠覆国家政权被起诉' }], tags: '街头运动,律师', tier: 'B',
    source: '公开报道', bio: '本名杨茂吉；南方街头运动参与者。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-02', name: '唐荆陵', nameEn: 'Tang Jingling', category: 'lawyer',
    subCategory: '维权律师', background: '法学', field: '公民权利', knownFor: '非暴力公民不合作',
    status: '在押', location: '境内', keyEvents: [{ from: '2016', to: '', desc: '因煽动颠覆国家政权罪被判五年' }], tags: '公民不合作', tier: 'B',
    source: '公开判决', bio: '广州律师。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-03', name: '卢思哲', nameEn: 'Lu Sizhe', category: 'journalist',
    subCategory: '记者', background: '新闻', field: '调查报道', knownFor: '独立调查',
    status: '流亡', location: '海外', keyEvents: [], tags: '调查记者', tier: 'C',
    source: '公开报道', bio: '独立调查记者；公开信息有限。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-04', name: '赵楚', nameEn: 'Zhao Chu', category: 'writer',
    subCategory: '作家', background: '军事', field: '战略写作', knownFor: '军事评论',
    status: '流亡', location: '海外', keyEvents: [], tags: '军事评论', tier: 'C',
    source: '公开报道', bio: '军事评论员。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-05', name: '王怡', nameEn: 'Wang Yi', category: 'religion',
    subCategory: '宗教', background: '神学', field: '家庭教会', knownFor: '牧师',
    status: '在押', location: '境内', keyEvents: [{ from: '2019', to: '', desc: '成都秋雨教会案相关' }], tags: '家庭教会', tier: 'A',
    source: '公开报道', bio: '成都家庭教会牧师。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-06', name: '覃德美', nameEn: 'Qin Demei', category: 'labor',
    subCategory: '劳工', background: '工运', field: '劳工维权', knownFor: '工运',
    status: '在押', location: '境内', keyEvents: [], tags: '劳工', tier: 'C',
    source: '公开报道', bio: '劳工维权参与者。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-07', name: '李旺阳', nameEn: 'Li Wangyang', category: 'movement',
    subCategory: '民运', background: '工运', field: '六四后异议', knownFor: '工运领袖',
    status: '已故', location: '境内', keyEvents: [{ from: '1989', to: '', desc: '六四后入狱' }, { from: '2012', to: '', desc: '狱中后死亡引发关注' }], tags: '六四,工运', tier: 'A',
    source: '公开报道', bio: '已故·2012年。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-08', name: '刘贤斌', nameEn: 'Liu Xianbin', category: 'movement',
    subCategory: '民运', background: '写作', field: '民主墙一代', knownFor: '异议写作',
    status: '在押', location: '境内', keyEvents: [{ from: '1999', to: '', desc: '因颠覆国家政权罪判刑' }, { from: '2010', to: '', desc: '再判十年' }], tags: '民主墙', tier: 'A',
    source: '公开判决', bio: '四川异议人士。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-09', name: '陈维', nameEn: 'Chen Wei', category: 'movement',
    subCategory: '民运', background: '写作', field: '1989学运', knownFor: '学运参与者',
    status: '在押', location: '境内', keyEvents: [{ from: '2011', to: '', desc: '因煽动颠覆国家政权罪被判九年' }], tags: '1989', tier: 'A',
    source: '公开判决', bio: '四川遂宁。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
  withProvenance({ id: 'dv-x-10', name: '黄琦', nameEn: 'Huang Qi', category: 'online',
    subCategory: '网络异议', background: '人权', field: '六四天网', knownFor: '网站创办人',
    status: '在押', location: '境内', keyEvents: [{ from: '2019', to: '', desc: '因泄露国家秘密等被判十二年' }], tags: '六四天网', tier: 'A',
    source: '公开判决', bio: '四川人权网站创办人。', notes: '', verifyTier: 'media', confidence: 'medium', dissentPrimary: true }),
];
export const DISSIDENT_EXPANSION_COUNT = 10;

export const TAIWAN_POLITICAL_EXPANSION = [
  withProvenance({ id: 'tw-x-01', name: '韩国瑜', nameEn: 'Han Kuo-yu', region: 'tw', category: 'local',
    party: '中国国民党', role: '立法机构负责人', term: '2024-', status: '在任',
    keyEvents: [{ from: '2024', to: '', desc: '任立法院长' }, { from: '2018', to: '2020', desc: '任高雄市长' }, { from: '2020', to: '', desc: '参选总统' }], tags: '国民党,地方', bio: '2024年立法院长；曾任高雄市长。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-02', name: '江启臣', nameEn: 'Johnny Chiang', region: 'tw', category: 'party',
    party: '中国国民党', role: '立委', term: '2024-', status: '在任',
    keyEvents: [{ from: '2020', to: '2021', desc: '任国民党主席' }], tags: '国民党', bio: '国民党籍立委；曾任党主席。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-03', name: '朱立伦', nameEn: 'Eric Chu', region: 'tw', category: 'party',
    party: '中国国民党', role: '党主席', term: '2021-', status: '在任',
    keyEvents: [{ from: '2021', to: '', desc: '再次任国民党主席' }, { from: '2016', to: '', desc: '参选总统' }], tags: '国民党', bio: '国民党主席；曾任新北市长、行政院长。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-04', name: '柯文哲', nameEn: 'Ko Wen-je', region: 'tw', category: 'party',
    party: '台湾民众党', role: '党主席', term: '2024-', status: '在押/司法程序',
    keyEvents: [{ from: '2014', to: '2022', desc: '任台北市长' }, { from: '2024', to: '', desc: '参选总统' }], tags: '民众党', bio: '台湾民众党创立者；2024涉司法调查。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-05', name: '黄国昌', nameEn: 'Huang Kuo-chang', region: 'tw', category: 'legislature',
    party: '台湾民众党', role: '立委', term: '2024-', status: '在任',
    keyEvents: [], tags: '民众党', bio: '民众党籍立委；法学背景。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-06', name: '吴钊燮', nameEn: 'Joseph Wu', region: 'tw', category: 'diplomacy',
    party: '民主进步党', role: '前外交部长', term: '2024-', status: '卸任',
    keyEvents: [{ from: '2018', to: '2024', desc: '任外交部长' }], tags: '外交', bio: '曾任台湾外交部长。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-07', name: '顾立雄', nameEn: 'Gu Lih-hsiung', region: 'tw', category: 'executive',
    party: '民主进步党', role: '国防部长', term: '2024-', status: '在任',
    keyEvents: [], tags: '国防', bio: '2024任台湾防务部门负责人。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-08', name: '卓荣泰', nameEn: 'Cho Jung-tai', region: 'tw', category: 'premier',
    party: '民主进步党', role: '行政院长', term: '2024-', status: '在任',
    keyEvents: [{ from: '2024', to: '', desc: '任行政院长' }], tags: '行政院', bio: '2024任台湾行政院长。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-09', name: '郑文灿', nameEn: 'Cheng Wen-tsan', region: 'tw', category: 'local',
    party: '民主进步党', role: '前桃园市长', term: '—', status: '司法程序',
    keyEvents: [{ from: '2014', to: '2022', desc: '任桃园市长' }], tags: '桃园', bio: '曾任桃园市长；2024涉司法调查。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
  withProvenance({ id: 'tw-x-10', name: '林佳龙', nameEn: 'Lin Chia-lung', region: 'tw', category: 'diplomacy',
    party: '民主进步党', role: '外交部长', term: '2024-', status: '在任',
    keyEvents: [{ from: '2024', to: '', desc: '任外交部长' }], tags: '外交', bio: '2024任台湾外交部长。', notes: '',
    verifyTier: 'official', taiwanPoliticalPrimary: true }),
];
export const TAIWAN_POLITICAL_EXPANSION_COUNT = 10;