#!/usr/bin/env python3
"""一键刷新信号灯「数据事实观察」快照。

用法（项目根目录）：
  npm run fetch:signals
  # 或
  python3 scripts/fetch_signal_observations.py

数据源：
  · 主源：data/signal_observations_seed.json（可手工维护最新公开读数）
  · 辅源：data/nbs_reference.json（按指标名模糊匹配，仅填充缺失/旧值）

输出：
  · app/src/modules/signalDashboard/observationData.js  （Vite 打包导入）
  · app/public/data/signal_observations.json             （UI「刷新观测」可选拉取）

说明：浏览器端无法直连 NBS（CORS），生产环境以本脚本为唯一刷新路径。
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone

ROOT = os.path.join(os.path.dirname(__file__), "..")
SEED_PATH = os.path.join(ROOT, "data", "signal_observations_seed.json")
NBS_REF_PATH = os.path.join(ROOT, "data", "nbs_reference.json")
OUT_JS = os.path.join(ROOT, "app", "src", "modules", "signalDashboard", "observationData.js")
OUT_JSON = os.path.join(ROOT, "app", "public", "data", "signal_observations.json")

# seed id -> nbs_reference name 关键词
NBS_ALIASES = {
    "pmi_mfg": "制造业采购经理",
    "cpi": "居民消费价格",
    "ppi": "工业生产者出厂",
    "urban_unemp": "城镇调查失业",
}


def load_json(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def merge_nbs(observations: list, nbs: dict) -> list:
    indicators = nbs.get("indicators") or []
    by_kw: dict[str, dict] = {}
    for ind in indicators:
        name = ind.get("name") or ""
        by_kw[name] = ind

    out = []
    for obs in observations:
        o = dict(obs)
        kw = NBS_ALIASES.get(o["id"])
        if not kw:
            out.append(o)
            continue
        match = next((ind for name, ind in by_kw.items() if kw in name), None)
        if match and match.get("latestValue") is not None:
            # 仅当 seed 无 value 或 nbs 年份更新时覆盖（示意）
            nbs_period = str(match.get("latestYear", ""))
            if o.get("value") is None:
                o["value"] = match["latestValue"]
                o["period"] = nbs_period
                o["source"] = (o.get("source") or "") + " · NBS 参考合并"
        out.append(o)
    return out


def js_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit_js(payload: dict) -> str:
    fetched = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    obs_json = json.dumps(payload["observations"], ensure_ascii=False, indent=2)
    lines = [
        "// AUTO-GENERATED by scripts/fetch_signal_observations.py — DO NOT EDIT BY HAND",
        f"// Fetched: {fetched}",
        f"// Source: {payload.get('source', '')}",
        "",
        f"export const OBS_AS_OF = {js_string(payload.get('asOf', ''))};",
        f"export const OBS_FETCHED_AT = {js_string(fetched)};",
        f"export const OBS_SOURCE_NOTE = {js_string(payload.get('note', ''))};",
        "",
        "/** @typedef {Object} Observation",
        " * @property {string} id",
        " * @property {string} label",
        " * @property {string} group",
        " * @property {number} value",
        " * @property {string} unit",
        " * @property {number|null} yoy",
        " * @property {number|null} mom",
        " * @property {string} period",
        " * @property {string[]} linkedSignals",
        " * @property {string} source",
        " */",
        "",
        "/** @type {Observation[]} */",
        f"export const OBSERVATIONS = {obs_json};",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if not os.path.exists(SEED_PATH):
        raise SystemExit(f"Missing seed: {SEED_PATH}")

    payload = load_json(SEED_PATH)
    observations = payload.get("observations") or []

    if os.path.exists(NBS_REF_PATH):
        try:
            nbs = load_json(NBS_REF_PATH)
            observations = merge_nbs(observations, nbs)
            payload["observations"] = observations
        except (json.JSONDecodeError, OSError) as e:
            print(f"warn: nbs_reference merge skipped: {e}")

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)

    js_body = emit_js(payload)
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js_body)

    public_payload = {
        "asOf": payload.get("asOf"),
        "fetchedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": payload.get("source"),
        "note": payload.get("note"),
        "observations": observations,
    }
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(public_payload, f, ensure_ascii=False, indent=2)

    print(f"✓ wrote {OUT_JS} ({len(observations)} indicators)")
    print(f"✓ wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
