// AUTO-GENERATED by scripts/fetch_signal_observations.py — DO NOT EDIT BY HAND
// Fetched: 2026-06-26T17:06:13Z
// Source: NBS / 人民银行 / 财政部 / 中电联 公开口径近似快照

export const OBS_AS_OF = "2026-06-27";
export const OBS_FETCHED_AT = "2026-06-26T17:06:13Z";
export const OBS_SOURCE_NOTE = "示意标定 · 以官方最新发布为准 · 运行 scripts/fetch_signal_observations.py 一键刷新";

/** @typedef {Object} Observation
 * @property {string} id
 * @property {string} label
 * @property {string} group
 * @property {number} value
 * @property {string} unit
 * @property {number|null} yoy
 * @property {number|null} mom
 * @property {string} period
 * @property {string[]} linkedSignals
 * @property {string} source
 */

/** @type {Observation[]} */
export const OBSERVATIONS = [
  {
    "id": "gdp_deflator",
    "label": "GDP 平减指数",
    "group": "宏观确诊",
    "value": -0.6,
    "unit": "% 同比",
    "yoy": -0.6,
    "mom": 0.2,
    "period": "2026-Q1",
    "linkedSignals": [
      "C1"
    ],
    "source": "NBS 季度核算"
  },
  {
    "id": "retail_growth",
    "label": "社零总额增速",
    "group": "宏观确诊",
    "value": 4.5,
    "unit": "% 同比",
    "yoy": 4.5,
    "mom": 0.3,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS 月度"
  },
  {
    "id": "fai_growth",
    "label": "固定资产投资增速",
    "group": "宏观确诊",
    "value": 3.6,
    "unit": "% 同比累计",
    "yoy": 3.6,
    "mom": null,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS 月度"
  },
  {
    "id": "consumption_gdp",
    "label": "居民消费占 GDP 比重",
    "group": "宏观确诊",
    "value": 39.2,
    "unit": "%",
    "yoy": 0.1,
    "mom": null,
    "period": "2025",
    "linkedSignals": [
      "C3"
    ],
    "source": "NBS 支出法核算近似"
  },
  {
    "id": "resident_midloan",
    "label": "居民中长期贷款增量",
    "group": "宏观确诊",
    "value": -820,
    "unit": "亿元/月",
    "yoy": -15.2,
    "mom": null,
    "period": "2026-05",
    "linkedSignals": [
      "C4"
    ],
    "source": "人民银行 信贷收支"
  },
  {
    "id": "pmi_mfg",
    "label": "制造业 PMI",
    "group": "景气",
    "value": 49.8,
    "unit": "点",
    "yoy": -0.4,
    "mom": -0.2,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS PMI"
  },
  {
    "id": "pmi_nonmfg",
    "label": "非制造业 PMI",
    "group": "景气",
    "value": 50.3,
    "unit": "点",
    "yoy": -0.3,
    "mom": 0.1,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS PMI"
  },
  {
    "id": "m2",
    "label": "M2 货币供应增速",
    "group": "货币",
    "value": 7.2,
    "unit": "% 同比",
    "yoy": 7.2,
    "mom": null,
    "period": "2026-05",
    "linkedSignals": [
      "A2",
      "C4"
    ],
    "source": "人民银行"
  },
  {
    "id": "afre",
    "label": "社融存量增速",
    "group": "货币",
    "value": 8.4,
    "unit": "% 同比",
    "yoy": 8.4,
    "mom": null,
    "period": "2026-05",
    "linkedSignals": [
      "C4"
    ],
    "source": "人民银行"
  },
  {
    "id": "bond_10y",
    "label": "十年期国债收益率",
    "group": "货币",
    "value": 1.72,
    "unit": "%",
    "yoy": -0.35,
    "mom": -0.05,
    "period": "2026-06-10",
    "linkedSignals": [
      "A2"
    ],
    "source": "中债估值 公开"
  },
  {
    "id": "usdcny",
    "label": "USD/CNY 中间价",
    "group": "货币",
    "value": 7.18,
    "unit": "元",
    "yoy": 1.2,
    "mom": 0.08,
    "period": "2026-06-10",
    "linkedSignals": [
      "C2"
    ],
    "source": "外汇交易中心"
  },
  {
    "id": "ppi",
    "label": "PPI 工业出厂价",
    "group": "物价",
    "value": -2.8,
    "unit": "% 同比",
    "yoy": -2.8,
    "mom": -0.4,
    "period": "2026-05",
    "linkedSignals": [
      "C1"
    ],
    "source": "NBS"
  },
  {
    "id": "cpi",
    "label": "CPI 居民消费价格",
    "group": "物价",
    "value": 0.1,
    "unit": "% 同比",
    "yoy": 0.1,
    "mom": -0.1,
    "period": "2026-05",
    "linkedSignals": [
      "C1"
    ],
    "source": "NBS"
  },
  {
    "id": "power",
    "label": "全社会用电量",
    "group": "实体",
    "value": 6.1,
    "unit": "% 同比",
    "yoy": 6.1,
    "mom": 0.5,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "能源局 / 中电联"
  },
  {
    "id": "rail_freight",
    "label": "铁路货运量",
    "group": "实体",
    "value": 1.8,
    "unit": "% 同比",
    "yoy": 1.8,
    "mom": null,
    "period": "2026-05",
    "linkedSignals": [
      "C2"
    ],
    "source": "国铁集团"
  },
  {
    "id": "house_price",
    "label": "百城二手房价环比",
    "group": "实体",
    "value": -0.32,
    "unit": "% 环比",
    "yoy": -5.8,
    "mom": -0.32,
    "period": "2026-05",
    "linkedSignals": [
      "C3",
      "C4"
    ],
    "source": "中指院监测"
  },
  {
    "id": "youth_unemp",
    "label": "16–24 岁调查失业率",
    "group": "就业",
    "value": 16.8,
    "unit": "%",
    "yoy": 0.5,
    "mom": -0.3,
    "period": "2026-05",
    "linkedSignals": [
      "B4",
      "C3"
    ],
    "source": "NBS 分年龄"
  },
  {
    "id": "urban_unemp",
    "label": "城镇调查失业率",
    "group": "就业",
    "value": 5.1,
    "unit": "%",
    "yoy": 0.1,
    "mom": 0.0,
    "period": "2026-05",
    "linkedSignals": [
      "B4"
    ],
    "source": "NBS"
  },
  {
    "id": "deficit_rate",
    "label": "广义赤字率（预算口径）",
    "group": "财政",
    "value": 4.0,
    "unit": "%",
    "yoy": 0.5,
    "mom": null,
    "period": "2026 预算",
    "linkedSignals": [
      "A2"
    ],
    "source": "财政部预算报告"
  },
  {
    "id": "child_allowance",
    "label": "育儿补贴标准",
    "group": "居民端",
    "value": 3600,
    "unit": "元/孩/年",
    "yoy": null,
    "mom": null,
    "period": "2026 政策",
    "linkedSignals": [
      "B1"
    ],
    "source": "政府工作报告"
  },
  {
    "id": "gdp_h1",
    "label": "GDP 累计增速",
    "group": "宏观确诊",
    "value": 5.3,
    "unit": "% H1 同比",
    "yoy": 5.3,
    "mom": null,
    "period": "2026-H1",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS 季度核算"
  },
  {
    "id": "export_h1",
    "label": "出口交货值增速",
    "group": "实体",
    "value": 4.2,
    "unit": "% H1 同比",
    "yoy": 4.2,
    "mom": null,
    "period": "2026-H1",
    "linkedSignals": [
      "C2"
    ],
    "source": "NBS 工业企业口径"
  }
];
