import { lazy } from 'react';

// ============================================================================
// 模块注册表 · China OS 单一数据源
// ----------------------------------------------------------------------------
// 新增一个模块 = 在 MODULES 里加一项（含 group / 路由 / 懒加载组件）。
// Shell 的导航、路由、面包屑全部由此生成，新模块「即插即用」、无需改框架。
// 分组对应框架图四层：cognition 认知内核 / lens 内容透镜 / sim 推演训练 / foundation 底座
//
// 命名约定（统一取名规范）：
//   · 主名(title)：优先 4 字；不可压缩的固定术语/榜单名按原义保留（如修昔底德陷阱、新质生产力）。
//   · 副题(subtitle)：三段式「A · B · C」，每段 2–5 字，密度一致，沿用调研系列术语。
// ============================================================================

export const GROUPS = [
  { id: 'home', label: '看板', desc: '总揽 · 实时大屏', accent: '#22d3ee' },
  { id: 'cognition', label: '认知内核', desc: '思想工具 · 理论模型', accent: '#c41e3a' },
  { id: 'lens', label: '内容透镜', desc: '四大支柱', accent: '#22d3ee' },
  { id: 'institutions', label: '制度与改革', desc: '权力 · 治理 · 法治', accent: '#e8a317' },
  { id: 'depthtopics', label: '深度专题', desc: '已迁移', accent: '#10b981' },
  { id: 'techtopics', label: '科技专题', desc: '科技树 · 深挖', accent: '#22d3ee' },
  { id: 'society', label: '社会与民生', desc: '人口 · 医保 · 住房', accent: '#f0abfc' },
  { id: 'industry', label: '产业与制造', desc: '能源 · 算力 · 链', accent: '#fb923c' },
  { id: 'finance', label: '货币金融', desc: '人民币 · 债务', accent: '#d4af37' },
  { id: 'region', label: '区域与全球化', desc: '板块 · 海洋 · 资源', accent: '#8b5cf6' },
  { id: 'security', label: '安全与国防', desc: '军事 · 台海 · 大安全', accent: '#c41e3a' },
  { id: 'population', label: '中国人群分析', desc: '人群画像总图谱 · 世代 · 阶层', accent: '#ec4899' },
  { id: 'sim', label: '推演与训练', desc: '沙盒 · 内参', accent: '#d4af37' },
  { id: 'foundation', label: '数据与系统', desc: '底座', accent: '#64748b' },
];

export const MODULES = [
  {
    id: 'dashboard', path: '/dashboard', group: 'home',
    title: '中枢看板', subtitle: '全局总揽 · 模块直达 · 实时大屏', icon: 'LayoutDashboard',
    component: lazy(() => import('../modules/dashboard/Page.jsx')),
  },
  {
    id: 'live-feeds', path: '/live-feeds', group: 'home',
    title: '神州实况', subtitle: '公开慢直播 · 熊猫 · 景区 · 枢纽', icon: 'Radio',
    component: lazy(() => import('../modules/dashboard/LiveFeedsPage.jsx')),
  },
  {
    id: 'shenzhou-live', path: '/shenzhou-live', group: 'home',
    title: '神州活图', subtitle: '省级分层 · 时间轴 · 对比研判', icon: 'Map',
    component: lazy(() => import('../modules/dashboard/LiveChinaMapPage.jsx')),
  },
  {
    id: 'cognition', path: '/cognition', group: 'cognition',
    title: '康波周期', subtitle: '康德拉季耶夫 · 长波 · 创新潮', icon: 'Waves',
    component: lazy(() => import('../modules/cognition/Page.jsx')),
  },
  {
    id: 'powerphysics', path: '/powerphysics', group: 'cognition',
    title: '权力物理', subtitle: '力场强制 · 合法成本 · 信息穿透', icon: 'Magnet',
    component: lazy(() => import('../modules/powerphysics/Page.jsx')),
  },
  {
    id: 'dissipative', path: '/dissipative', group: 'cognition',
    title: '耗散结构', subtitle: '普里高津 · 负熵流 · 自组织', icon: 'Wind',
    component: lazy(() => import('../modules/dissipative/Page.jsx')),
  },
  {
    id: 'pathdependence', path: '/pathdependence', group: 'cognition',
    title: '路径依赖', subtitle: '报酬递增 · 锁定效应 · 路径换道', icon: 'GitFork',
    component: lazy(() => import('../modules/pathdependence/Page.jsx')),
  },
  {
    id: 'realism', path: '/realism', group: 'cognition',
    title: '现实主义', subtitle: '米尔斯海默 · 大国政治 · 权力制衡', icon: 'Swords',
    component: lazy(() => import('../modules/realism/Page.jsx')),
  },
  {
    id: 'middleincometrap', path: '/middleincometrap', group: 'cognition',
    title: '中等收入陷阱', subtitle: '韩国跨越 · 拉美停滞 · 中国窗口', icon: 'TrendingUp',
    component: lazy(() => import('../modules/middleincometrap/Page.jsx')),
  },
  {
    id: 'thucydides', path: '/thucydides', group: 'cognition',
    title: '修昔底德陷阱', subtitle: '艾利森 · 守成崛起 · 权力转移', icon: 'GitFork',
    component: lazy(() => import('../modules/thucydides/Page.jsx')),
  },
  {
    id: 'gametheory', path: '/gametheory', group: 'cognition',
    title: '博弈理论', subtitle: '纳什均衡 · 重复博弈 · 以牙还牙', icon: 'Dices',
    component: lazy(() => import('../modules/gametheory/Page.jsx')),
  },
  {
    id: 'antifragile', path: '/antifragile', group: 'cognition',
    title: '反脆弱性', subtitle: '塔勒布 · 凸性效应 · 波动获益', icon: 'TrendingUp',
    component: lazy(() => import('../modules/antifragile/Page.jsx')),
  },
  {
    id: 'constructivism', path: '/constructivism', group: 'cognition',
    title: '建构主义', subtitle: '温特 · 观念建构 · 无政府文化', icon: 'Network',
    component: lazy(() => import('../modules/constructivism/Page.jsx')),
  },
  {
    id: 'ideology', path: '/ideology', group: 'cognition',
    title: '意识形态', subtitle: '自由主义 · 马克思 · 社会达尔文', icon: 'Scale3d',
    component: lazy(() => import('../modules/ideology/Page.jsx')),
  },
  {
    id: 'deterrence', path: '/deterrence', group: 'cognition',
    title: '威慑战略', subtitle: '谢林 · 可信承诺 · 边缘政策', icon: 'ShieldAlert',
    component: lazy(() => import('../modules/deterrence/Page.jsx')),
  },
  {
    id: 'principalagent', path: '/principalagent', group: 'cognition',
    title: '委托代理', subtitle: '信息不对称 · 激励相容 · 道德风险', icon: 'GitBranchPlus',
    component: lazy(() => import('../modules/principalagent/Page.jsx')),
  },
  {
    id: 'commons', path: '/commons', group: 'cognition',
    title: '公地悲剧', subtitle: '集体行动 · 搭便车 · 自主治理', icon: 'Trees',
    component: lazy(() => import('../modules/commons/Page.jsx')),
  },
  {
    id: 'contradictions', path: '/contradictions', group: 'cognition',
    title: '矛盾论', subtitle: '主次矛盾 · 对立统一 · 社会矛盾体', icon: 'ArrowLeftRight',
    component: lazy(() => import('../modules/contradictions/Page.jsx')),
  },
  {
    id: 'depth',
    path: '/depth',
    group: 'lens',
    title: '深度透视',
    subtitle: '七维框架 · 多重专题 · 全景扫描',
    icon: 'Layers',
    component: lazy(() => import('../modules/depth/Page.jsx')),
  },
  {
    id: 'foodSecurity', path: '/food-security', group: 'depthtopics',
    title: '粮食安全', subtitle: '耕地红线 · 种业自主 · 大国粮仓', icon: 'Wheat',
    component: lazy(() => import('../modules/foodSecurity/Page.jsx')),
  },
  {
    id: 'urban', path: '/urban', group: 'depthtopics',
    title: '新型城镇化', subtitle: '市民化 · 城市群 · 都市圈', icon: 'Building2',
    component: lazy(() => import('../modules/urban/Page.jsx')),
  },
  {
    id: 'ecology', path: '/ecology', group: 'depthtopics',
    title: '生态文明', subtitle: '双碳目标 · 碳汇市场 · 绿水青山', icon: 'Leaf',
    component: lazy(() => import('../modules/ecology/Page.jsx')),
  },
  {
    id: 'automotive', path: '/automotive', group: 'depthtopics',
    title: '汽车主权', subtitle: '电动智能 · 换道超车 · 全球出海', icon: 'Car',
    component: lazy(() => import('../modules/automotive/Page.jsx')),
  },
  {
    id: 'dataElement', path: '/data-element', group: 'depthtopics',
    title: '数据要素', subtitle: '产权确权 · 数据入表 · 东数西算', icon: 'Binary',
    component: lazy(() => import('../modules/dataElement/Page.jsx')),
  },
  {
    id: 'digital', path: '/digital', group: 'depthtopics',
    title: '数字经济', subtitle: '数实融合 · 平台经济 · 数字治理', icon: 'Cpu',
    component: lazy(() => import('../modules/digital/Page.jsx')),
  },
  {
    id: 'digitalGiantWeb', path: '/digital-giant-web', group: 'depthtopics',
    title: '数字巨网', subtitle: '网络经济 · 赛博反馈 · 语义防火墙', icon: 'Globe2',
    component: lazy(() => import('../modules/digitalGiantWeb/Page.jsx')),
  },
  {
    id: 'bri', path: '/bri', group: 'depthtopics',
    title: '一带一路', subtitle: '六廊六路 · 中欧班列 · 互联互通', icon: 'Route',
    component: lazy(() => import('../modules/bri/Page.jsx')),
  },
  {
    id: 'foreignTrade', path: '/foreign-trade', group: 'depthtopics',
    title: '对外贸易', subtitle: '新三样 · RCEP · 跨境电商', icon: 'Ship',
    component: lazy(() => import('../modules/foreignTrade/Page.jsx')),
  },
  {
    id: 'serviceTrade', path: '/service-trade', group: 'depthtopics',
    title: '服务贸易', subtitle: '数字贸易 · 服贸创新 · 知识密集', icon: 'Globe',
    component: lazy(() => import('../modules/serviceTrade/Page.jsx')),
  },
  {
    id: 'instOpen', path: '/inst-open', group: 'depthtopics',
    title: '制度开放', subtitle: '自贸试验 · 负面清单 · 规则对接', icon: 'DoorOpen',
    component: lazy(() => import('../modules/instOpen/Page.jsx')),
  },
  {
    id: 'civilAviation', path: '/civil-aviation', group: 'depthtopics',
    title: '民用航空', subtitle: 'C919 · 适航取证 · 低空经济', icon: 'Plane',
    component: lazy(() => import('../modules/civilAviation/Page.jsx')),
  },
  {
    id: 'culture',
    path: '/culture',
    group: 'depthtopics',
    title: '文化软实力',
    subtitle: '国潮崛起 · 短剧出海 · 文化贸易',
    icon: 'Sparkles',
    component: lazy(() => import('../modules/culture/Page.jsx')),
  },
  {
    id: 'private', path: '/private', group: 'depthtopics',
    title: '民营经济', subtitle: '56789 · 公平竞争 · 产权保护', icon: 'Briefcase',
    component: lazy(() => import('../modules/private/Page.jsx')),
  },
  {
    id: 'quantum', path: '/quantum', group: 'techtopics',
    title: '量子信息', subtitle: '量子计算 · 量子通信 · 量子测量', icon: 'Atom',
    component: lazy(() => import('../modules/quantum/Page.jsx')),
  },
  {
    id: 'semiconductor', path: '/semiconductor', group: 'techtopics',
    title: '集成电路', subtitle: '芯片主权 · 大基金 · 先进制程', icon: 'CircuitBoard',
    component: lazy(() => import('../modules/semiconductor/Page.jsx')),
  },
  {
    id: 'aiplus', path: '/aiplus', group: 'techtopics',
    title: '人工智能+', subtitle: '智算底座 · 行业模型 · 赋能百业', icon: 'BrainCog',
    component: lazy(() => import('../modules/aiplus/Page.jsx')),
  },
  {
    id: 'basicResearch', path: '/basic-research', group: 'techtopics',
    title: '基础研究', subtitle: '国家实验室 · 评价改革 · 原始创新', icon: 'FlaskConical',
    component: lazy(() => import('../modules/basicResearch/Page.jsx')),
  },
  {
    id: 'powerlogic', path: '/powerlogic', group: 'institutions',
    title: '权力逻辑', subtitle: '儒表法里 · 数字利维坦 · 统治成本', icon: 'Cpu',
    component: lazy(() => import('../modules/powerlogic/Page.jsx')),
  },
  {
    id: 'reform', path: '/reform', group: 'institutions',
    title: '改革开放', subtitle: '现实主义 · 算法演进 · 摸石过河', icon: 'GitFork',
    component: lazy(() => import('../modules/reform/Page.jsx')),
  },
  {
    id: 'governance', path: '/governance', group: 'institutions',
    title: '治理现代化', subtitle: '网格管理 · 数字政府 · 多元共治', icon: 'Network',
    component: lazy(() => import('../modules/governance/Page.jsx')),
  },
  {
    id: 'govsystem', path: '/govsystem', group: 'institutions',
    title: '政府体系', subtitle: '压力体制 · 执行算法 · 央地关系', icon: 'Workflow',
    component: lazy(() => import('../modules/govsystem/Page.jsx')),
  },
  {
    id: 'soe', path: '/soe', group: 'institutions',
    title: '国有资本', subtitle: '战略底座 · 链主企业 · 国资改革', icon: 'Building',
    component: lazy(() => import('../modules/soe/Page.jsx')),
  },
  {
    id: 'enterprise500', path: '/enterprise500', group: 'industry',
    title: '民企500强', subtitle: '工商联榜 · 治理透视 · 行业分布', icon: 'Building2',
    component: lazy(() => import('../modules/enterprise500/Page.jsx')),
  },
  {
    id: 'ruleoflaw', path: '/ruleoflaw', group: 'institutions',
    title: '法治建设', subtitle: '智慧法院 · 涉外法治 · 营商环境', icon: 'Scale',
    component: lazy(() => import('../modules/ruleoflaw/Page.jsx')),
  },
  {
    id: 'unifiedMarket', path: '/unified-market', group: 'institutions',
    title: '统一大市场', subtitle: '五个统一 · 破除壁垒 · 要素流通', icon: 'Store', accent: '#e8a317',
    component: lazy(() => import('../modules/unifiedMarket/Page.jsx')),
  },
  { id: 'demographic', path: '/demographic', group: 'society', title: '人口结构', subtitle: '负增长 · 抚养比 · 老龄化', icon: 'Users', component: lazy(() => import('../modules/demographic/Page.jsx')) },
  { id: 'gig', path: '/gig', group: 'society', title: '零工经济', subtitle: '蓄水池 · 算法治理 · 新业态', icon: 'Bike', component: lazy(() => import('../modules/gig/Page.jsx')) },
  { id: 'healthcare', path: '/healthcare', group: 'society', title: '医疗医保', subtitle: 'DRG · 药品集采 · 分级诊疗', icon: 'Stethoscope', component: lazy(() => import('../modules/healthcare/Page.jsx')) },
  { id: 'socialgov', path: '/socialgov', group: 'society', title: '基层治理', subtitle: '网格管理 · 综治中心 · 枫桥经验', icon: 'LayoutGrid', component: lazy(() => import('../modules/socialgov/Page.jsx')) },
  { id: 'housing', path: '/housing', group: 'society', title: '住房地产', subtitle: '行业周期 · 保障房 · 三大工程', icon: 'Home', component: lazy(() => import('../modules/housing/Page.jsx')) },
  { id: 'education', path: '/education', group: 'society', title: '教育体系', subtitle: '普职分流 · 高考改革 · 人才培养', icon: 'GraduationCap', component: lazy(() => import('../modules/education/Page.jsx')) },
  { id: 'consumption', path: '/consumption', group: 'society', title: '扩大内需', subtitle: '消费率 · 服务化 · 以旧换新', icon: 'ShoppingCart', accent: '#c41e3a', component: lazy(() => import('../modules/consumption/Page.jsx')) },
  { id: 'silverEconomy', path: '/silver-economy', group: 'society', title: '银发经济', subtitle: '9073 · 养老服务 · 适老改造', icon: 'HeartHandshake', accent: '#8b5cf6', component: lazy(() => import('../modules/silverEconomy/Page.jsx')) },
  { id: 'fertilitySupport', path: '/fertility-support', group: 'society', title: '生育支持', subtitle: '生育补贴 · 普惠托育 · 友好社会', icon: 'Baby', accent: '#ec4899', component: lazy(() => import('../modules/fertilitySupport/Page.jsx')) },
  { id: 'tcmHealth', path: '/tcm-health', group: 'society', title: '中医药', subtitle: '重大工程 · 传承创新 · 治未病', icon: 'Flower2', component: lazy(() => import('../modules/tcmHealth/Page.jsx')) },
  {
    id: 'renqunTupu',
    path: '/modules/renqun-tupu',
    group: 'population',
    title: '人群画像总图谱',
    subtitle: '26 片切片 · 八轴全光谱 · 母索引',
    icon: 'Network',
    component: lazy(() => import('../modules/renqun-tupu/Page.jsx')),
  },
  {
    id: 'qingnian',
    path: '/modules/qingnian',
    group: 'population',
    title: '青年',
    subtitle: '机器的盲区 · 概率的暗物质',
    icon: 'UserRound',
    component: lazy(() => import('../modules/qingnian/Page.jsx')),
  },
  {
    id: 'xingshaoshu',
    path: '/modules/xingshaoshu',
    group: 'population',
    title: '性少数',
    subtitle: '挤压性存在',
    icon: 'UsersRound',
    component: lazy(() => import('../modules/xingshaoshu/Page.jsx')),
  },
  {
    id: 'linggong',
    path: '/modules/linggong',
    group: 'population',
    title: '零工经济',
    subtitle: '悬空的基础设施',
    icon: 'Bike',
    component: lazy(() => import('../modules/linggong/Page.jsx')),
  },
  {
    id: 'nongmingong',
    path: '/modules/nongmingong',
    group: 'population',
    title: '农民工',
    subtitle: '未完成的迁徙 · 换页内存',
    icon: 'HardHat',
    component: lazy(() => import('../modules/nongmingong/Page.jsx')),
  },
  {
    id: 'tizhinei',
    path: '/modules/tizhinei',
    group: 'population',
    title: '体制内',
    subtitle: '常驻内存 · 刚兑的最后分区',
    icon: 'Landmark',
    component: lazy(() => import('../modules/tizhinei/Page.jsx')),
  },
  {
    id: 'zhongchan',
    path: '/modules/zhongchan',
    group: 'population',
    title: '中产',
    subtitle: '质押态进程 · 三张折价的凭证',
    icon: 'Briefcase',
    component: lazy(() => import('../modules/zhongchan/Page.jsx')),
  },
  {
    id: 'laonian',
    path: '/modules/laonian',
    group: 'population',
    title: '老年',
    subtitle: '应计负债 · 账期已至',
    icon: 'PersonStanding',
    component: lazy(() => import('../modules/laonian/Page.jsx')),
  },
  {
    id: 'tajian',
    path: '/modules/tajian',
    group: 'population',
    title: '塔尖阶层',
    subtitle: '可迁移进程 · 要钱不要人的塔尖',
    icon: 'Crown',
    component: lazy(() => import('../modules/tajian/Page.jsx')),
  },
  {
    id: 'zhixiao',
    path: '/modules/zhixiao',
    group: 'population',
    title: '职校生',
    subtitle: '编译期定价 · 十五岁的一次性判决',
    icon: 'Wrench',
    component: lazy(() => import('../modules/zhixiao/Page.jsx')),
  },
  {
    id: 'tuiyi',
    path: '/modules/tuiyi',
    group: 'population',
    title: '退役军人',
    subtitle: '预装组织力 · 被定向赎买的人群',
    icon: 'Medal',
    component: lazy(() => import('../modules/tuiyi/Page.jsx')),
  },
  {
    id: 'yiyi',
    path: '/modules/yiyi',
    group: 'population',
    title: '信仰人群',
    subtitle: '无主端口 · 被许可的玄学',
    icon: 'Flame',
    component: lazy(() => import('../modules/yiyi/Page.jsx')),
  },
  {
    id: 'liupiao',
    path: '/modules/liupiao',
    group: 'population',
    title: '创作者',
    subtitle: '彩票调度 · 用中奖伪装的职业',
    icon: 'Clapperboard',
    component: lazy(() => import('../modules/liupiao/Page.jsx')),
  },
  {
    id: 'yibao',
    path: '/modules/yibao',
    group: 'population',
    title: '医保群体',
    subtitle: '全员接口 · 单方面改版的契约',
    icon: 'Cross',
    component: lazy(() => import('../modules/yibao/Page.jsx')),
  },
  {
    id: 'lian',
    path: '/modules/lian',
    group: 'population',
    title: '离岸华人',
    subtitle: '境外节点 · 未结清的账户',
    icon: 'Plane',
    component: lazy(() => import('../modules/lian/Page.jsx')),
  },
  {
    id: 'zhongnv',
    path: '/modules/zhongnv',
    group: 'population',
    title: '中年女性',
    subtitle: '后台守护进程 · 被折叠的一代 · GY-17',
    icon: 'HeartHandshake',
    component: lazy(() => import('../modules/zhongnv/Page.jsx')),
  },
  {
    id: 'canzhang',
    path: '/modules/canzhang',
    group: 'population',
    title: '残障人群',
    subtitle: '未挂载设备 · 可见性的零点 · GY-18',
    icon: 'Accessibility',
    component: lazy(() => import('../modules/canzhang/Page.jsx')),
  },
  {
    id: 'danshen',
    path: '/modules/danshen',
    group: 'population',
    title: '单身女性与不婚者',
    subtitle: '独立运行实例 · 退出常态化 · GY-19',
    icon: 'UserRound',
    component: lazy(() => import('../modules/danshen/Page.jsx')),
  },
  {
    id: 'xianyu',
    path: '/modules/xianyu',
    group: 'population',
    title: '县域青年',
    subtitle: '未被监控的中间件 · 留下的人 · GY-20',
    icon: 'MapPin',
    component: lazy(() => import('../modules/xianyu/Page.jsx')),
  },
  {
    id: 'xinyimin',
    path: '/modules/xinyimin',
    group: 'population',
    title: '城市新移民',
    subtitle: '访客会话 · 有城无籍 · GY-21',
    icon: 'DoorClosed',
    component: lazy(() => import('../modules/xinyimin/Page.jsx')),
  },
  {
    id: 'jigong',
    path: '/modules/jigong',
    group: 'population',
    title: '制造业技术工人',
    subtitle: '关键依赖 · 被需要却不被向往 · GY-22',
    icon: 'Wrench',
    component: lazy(() => import('../modules/jigong/Page.jsx')),
  },
  {
    id: 'manbing',
    path: '/modules/manbing',
    group: 'population',
    title: '带病青年',
    subtitle: '提前折旧的电池 · 健康阶层化 · GY-23',
    icon: 'HeartPulse',
    component: lazy(() => import('../modules/manbing/Page.jsx')),
  },
  {
    id: 'moshao',
    path: '/modules/moshao',
    group: 'population',
    title: '基层治理末梢',
    subtitle: '借权代理进程 · 编外治理者 · GY-24',
    icon: 'LayoutGrid',
    component: lazy(() => import('../modules/moshao/Page.jsx')),
  },
  {
    id: 'shidu',
    path: '/modules/shidu',
    group: 'population',
    title: '失独与计生后遗',
    subtitle: '已废弃契约 · 政策账单活体 · GY-25',
    icon: 'Hourglass',
    component: lazy(() => import('../modules/shidu/Page.jsx')),
  },
  {
    id: 'shuzi',
    path: '/modules/shuzi',
    group: 'population',
    title: '数字原住民',
    subtitle: '被改写的引导程序 · 屏幕养大的一代 · GY-26',
    icon: 'Smartphone',
    component: lazy(() => import('../modules/shuzi/Page.jsx')),
  },
  {
    id: 'huoche',
    path: '/modules/huoche',
    group: 'population',
    title: '货车司机',
    subtitle: '轮子上的实时进程 · 北斗即调度器 · GY-27',
    icon: 'Truck',
    component: lazy(() => import('../modules/huoche/Page.jsx')),
  },
  {
    id: 'chengxu',
    path: '/modules/chengxu',
    group: 'population',
    title: '程序员',
    subtitle: '自我弃用的进程 · 35岁折旧 · GY-28',
    icon: 'Code2',
    component: lazy(() => import('../modules/chengxu/Page.jsx')),
  },
  { id: 'manufacturing', path: '/manufacturing', group: 'industry', title: '制造强国', subtitle: '规模优势 · GVC位势 · 转型升级', icon: 'Factory', component: lazy(() => import('../modules/manufacturing/Page.jsx')) },
  { id: 'robotics', path: '/robotics', group: 'industry', title: '机器人', subtitle: '装机密度 · 人形整机 · 核心部件', icon: 'Bot', component: lazy(() => import('../modules/robotics/Page.jsx')) },
  { id: 'materials', path: '/materials', group: 'industry', title: '关键材料', subtitle: '卡脖子 · 国产替代 · 前沿材料', icon: 'Gem', component: lazy(() => import('../modules/materials/Page.jsx')) },
  { id: 'energy', path: '/energy', group: 'industry', title: '能源安全', subtitle: '压舱石 · 绿色转型 · 油气保供', icon: 'Zap', component: lazy(() => import('../modules/energy/Page.jsx')) },
  { id: 'nuclear', path: '/nuclear', group: 'industry', title: '核能电力', subtitle: '华龙一号 · 四代堆 · 核燃料', icon: 'Radiation', component: lazy(() => import('../modules/nuclear/Page.jsx')) },
  { id: 'hydrogen', path: '/hydrogen', group: 'industry', title: '氢能产业', subtitle: '绿氢制取 · 储运加注 · 燃料电池', icon: 'Droplets', component: lazy(() => import('../modules/hydrogen/Page.jsx')) },
  { id: 'smartgrid', path: '/smartgrid', group: 'industry', title: '智能电网', subtitle: '特高压 · 新型储能 · 源网荷储', icon: 'PlugZap', component: lazy(() => import('../modules/smartgrid/Page.jsx')) },
  { id: 'computing', path: '/computing', group: 'industry', title: '算力设施', subtitle: '东数西算 · 智算中心 · 算力主权', icon: 'Server', component: lazy(() => import('../modules/computing/Page.jsx')) },
  { id: 'logistics', path: '/logistics', group: 'industry', title: '现代物流', subtitle: '多式联运 · 降本增效 · 冷链网络', icon: 'Truck', component: lazy(() => import('../modules/logistics/Page.jsx')) },
  { id: 'supplychain', path: '/supplychain', group: 'industry', title: '供应链', subtitle: '冗余备份 · 韧性安全 · 自主可控', icon: 'Link2', component: lazy(() => import('../modules/supplychain/Page.jsx')) },
  { id: 'infrastructure', path: '/infrastructure', group: 'industry', title: '基础设施', subtitle: '新老基建 · 专项债 · 有效投资', icon: 'Construction', component: lazy(() => import('../modules/infrastructure/Page.jsx')) },
  { id: 'megaprojects', path: '/megaprojects', group: 'industry', title: '超级工程', subtitle: '多维ROI · 国家账本 · 战略投资', icon: 'Hammer', component: lazy(() => import('../modules/megaprojects/Page.jsx')) },
  { id: 'space', path: '/space', group: 'industry', title: '航天产业', subtitle: '北斗组网 · 商业航天 · 深空探测', icon: 'Satellite', component: lazy(() => import('../modules/space/Page.jsx')) },
  { id: 'lowAltitude', path: '/low-altitude', group: 'industry', title: '低空经济', subtitle: 'eVTOL · 无人机 · 通用航空', icon: 'PlaneTakeoff', accent: '#22d3ee', component: lazy(() => import('../modules/lowAltitude/Page.jsx')) },
  { id: 'medequipment', path: '/medequipment', group: 'industry', title: '医疗装备', subtitle: '高端影像 · 进口替代 · 自主器械', icon: 'HeartPulse', component: lazy(() => import('../modules/medequipment/Page.jsx')) },
  { id: 'tourism', path: '/tourism', group: 'industry', title: '文旅消费', subtitle: '入境旅游 · 区域品牌 · 消费升级', icon: 'Luggage', component: lazy(() => import('../modules/tourism/Page.jsx')) },
  { id: 'finance', path: '/finance-system', group: 'finance', title: '金融系统', subtitle: '系统风险 · 宏观审慎 · 金融安全', icon: 'Landmark', component: lazy(() => import('../modules/finance/Page.jsx')) },
  { id: 'marketPulse', path: '/market-pulse', group: 'finance', title: '全球资产脉搏', subtitle: '股市 · 债市 · 汇市 · 大宗', icon: 'Activity', accent: '#22d3ee', component: lazy(() => import('../modules/marketPulse/Page.jsx')) },
  { id: 'capitalMarket', path: '/capital-market', group: 'finance', title: '资本市场', subtitle: '耐心资本 · 注册制 · 创投', icon: 'TrendingUp', component: lazy(() => import('../modules/capitalMarket/Page.jsx')) },
  { id: 'financeRmb', path: '/rmb', group: 'finance', title: '人民币国际化', subtitle: 'CIPS · e-CNY · 跨境结算', icon: 'CircleDollarSign', component: lazy(() => import('../modules/financeRmb/Page.jsx')) },
  { id: 'fdi', path: '/fdi', group: 'finance', title: '跨境投资', subtitle: '负面清单 · 双向流动 · 外资准入', icon: 'ArrowLeftRight', component: lazy(() => import('../modules/fdi/Page.jsx')) },
  { id: 'greenfinance', path: '/green-finance', group: 'finance', title: '绿色金融', subtitle: '绿色债券 · 碳定价 · 转型金融', icon: 'Leaf', component: lazy(() => import('../modules/greenfinance/Page.jsx')) },
  { id: 'debtHeatmap', path: '/debt', group: 'finance', title: '地方债务', subtitle: '省际热力 · 隐性债务 · 化债方案', icon: 'Flame', component: lazy(() => import('../modules/debtHeatmap/Page.jsx')) },
  { id: 'benchmark', path: '/benchmark', group: 'region', title: '国际对标', subtitle: '中美日德 · 多维对标 · 全球坐标', icon: 'BarChart3', component: lazy(() => import('../modules/benchmark/Page.jsx')) },
  { id: 'rural', path: '/rural', group: 'region', title: '乡村振兴', subtitle: '县域经济 · 土地制度 · 城乡融合', icon: 'Tractor', component: lazy(() => import('../modules/rural/Page.jsx')) },
  { id: 'frontierGov', path: '/frontier-gov', group: 'region', title: '边疆治理', subtitle: '兴边富民 · 对口支援 · 共同体', icon: 'Mountain', component: lazy(() => import('../modules/frontierGov/Page.jsx')) },
  { id: 'regional', path: '/regional', group: 'region', title: '区域协调', subtitle: '四大板块 · 转移支付 · 城市群', icon: 'Map', component: lazy(() => import('../modules/regional/Page.jsx')) },
  { id: 'northeastRevival', path: '/northeast', group: 'region', title: '东北振兴', subtitle: '老工业基地 · 全面振兴 · 十五五', icon: 'Factory', component: lazy(() => import('../modules/northeastRevival/Page.jsx')) },
  { id: 'marine', path: '/marine', group: 'region', title: '海洋经济', subtitle: '海洋权益 · 船舶制造 · 深海开发', icon: 'Anchor', component: lazy(() => import('../modules/marine/Page.jsx')) },
  { id: 'polar', path: '/polar', group: 'region', title: '极地战略', subtitle: '北极航道 · 极地科考 · 资源博弈', icon: 'Snowflake', component: lazy(() => import('../modules/polar/Page.jsx')) },
  { id: 'resources', path: '/resources', group: 'region', title: '海外资源', subtitle: '权益矿山 · 航道安全 · 资源主权', icon: 'Pickaxe', component: lazy(() => import('../modules/resources/Page.jsx')) },
  { id: 'offshore', path: '/offshore', group: 'region', title: '港澳离岸', subtitle: '普通法窗 · 离岸RMB · 资本通道', icon: 'Banknote', component: lazy(() => import('../modules/offshore/Page.jsx')) },
  { id: 'industrysoftware', path: '/industry-software', group: 'techtopics', title: '工业软件', subtitle: 'CAD/CAE · 自主信创 · 国产替代', icon: 'Code2', component: lazy(() => import('../modules/industrysoftware/Page.jsx')) },
  { id: 'tech', path: '/tech-policy', group: 'techtopics', title: '创新体系', subtitle: '研发投入 · 高新企业 · 成果转化', icon: 'Lightbulb', component: lazy(() => import('../modules/tech/Page.jsx')) },
  { id: 'npf', path: '/npf', group: 'techtopics', title: '新质生产力', subtitle: '未来产业 · 全要素率 · 技术跃迁', icon: 'Rocket', component: lazy(() => import('../modules/npf/Page.jsx')) },
  { id: 'bio', path: '/bio', group: 'techtopics', title: '生物医药', subtitle: '创新药械 · 生物安全 · 出海授权', icon: 'Dna', component: lazy(() => import('../modules/bio/Page.jsx')) },
  { id: 'neural', path: '/neural', group: 'techtopics', title: '脑机接口', subtitle: '神经接口 · 数据主权 · 人机融合', icon: 'Brain', component: lazy(() => import('../modules/neural/Page.jsx')) },
  { id: 'futureIndustry', path: '/future-industry', group: 'techtopics', title: '未来产业', subtitle: '具身智能 · 可控聚变 · 生物制造', icon: 'Telescope', accent: '#22d3ee', component: lazy(() => import('../modules/futureIndustry/Page.jsx')) },
  { id: 'eduSciTalent', path: '/edu-sci-talent', group: 'techtopics', title: '教科人才', subtitle: '教育链 · 科技链 · 人才链', icon: 'BookOpenCheck', accent: '#10b981', component: lazy(() => import('../modules/eduSciTalent/Page.jsx')) },
  {
    id: 'military', path: '/military', group: 'security',
    title: '军事力量', subtitle: '战区联合 · 主战装备 · 全球基地', icon: 'Shield',
    component: lazy(() => import('../modules/military/Page.jsx')),
  },
  {
    id: 'straits', path: '/straits', group: 'security',
    title: '台海局势', subtitle: '地缘重力 · 硅盾屏障 · 统一进程', icon: 'Crosshair',
    component: lazy(() => import('../modules/straits/Page.jsx')),
  },
  {
    id: 'omnisecurity', path: '/omnisecurity', group: 'security',
    title: '大安全观', subtitle: '粮食安全 · 能源安全 · 网络安全', icon: 'ShieldCheck',
    component: lazy(() => import('../modules/omnisecurity/Page.jsx')),
  },
  {
    id: 'redweb', path: '/redweb', group: 'security',
    title: '红色巨网', subtitle: '权贵网络 · 结构分析 · 利益图谱', icon: 'Network',
    component: lazy(() => import('../modules/redweb/Page.jsx')),
  },
  {
    id: 'publicSafety', path: '/public-safety', group: 'security',
    title: '公共安全', subtitle: '防灾减灾 · 应急管理 · 韧性城市', icon: 'Siren', accent: '#c41e3a',
    component: lazy(() => import('../modules/publicSafety/Page.jsx')),
  },
  {
    id: 'defenseMobilization', path: '/defense-mobilization', group: 'security',
    title: '国防动员', subtitle: '后备力量 · 平战结合 · 新域新质', icon: 'ShieldHalf',
    component: lazy(() => import('../modules/defenseMobilization/Page.jsx')),
  },
  {
    id: 'civilization',
    path: '/civilization',
    group: 'lens',
    title: '文明透视',
    subtitle: '十二卷源码 · 文明基因 · 历史底片',
    icon: 'ScrollText',
    wildcard: true,
    component: lazy(() => import('../modules/civilization/index.jsx')),
  },
  {
    id: 'diplomacy',
    path: '/diplomacy',
    group: 'lens',
    title: '外交博弈',
    subtitle: '中美博弈 · 区域纵横 · 能源航道',
    icon: 'Globe2',
    component: lazy(() => import('../modules/diplomacy/Page.jsx')),
  },
  {
    id: 'techtree',
    path: '/techtree',
    group: 'lens',
    title: '科技图谱',
    subtitle: '智能算力 · 可控聚变 · 深空军备',
    icon: 'GitBranch',
    component: lazy(() => import('../modules/techtree/Page.jsx')),
  },
  {
    id: 'sandbox',
    path: '/sandbox',
    group: 'sim',
    title: '治国沙盒',
    subtitle: '人才配置 · 情景推演 · 政策模拟',
    icon: 'Boxes',
    component: lazy(() => import('../modules/sandbox/Page.jsx')),
  },
  {
    id: 'guoyun',
    path: '/modules/guoyun',
    group: 'sim',
    title: '国运模拟器',
    subtitle: '七时代轴 · 情景推演 · 观测哨',
    icon: 'Compass',
    component: lazy(() => import('../modules/guoyun/Page.jsx')),
  },
  {
    id: 'yishixingtai',
    path: '/modules/yishixingtai',
    group: 'sim',
    title: '合法性机器',
    subtitle: '意识形态架构 · 五组件 · GY-02',
    icon: 'Layers',
    component: lazy(() => import('../modules/yishixingtai/Page.jsx')),
  },
  {
    id: 'leadership', path: '/leadership', group: 'sim',
    title: '领袖统治', subtitle: '权力结构 · 决策机制 · 12 图可视化 · 四区交互', icon: 'Crown',
    component: lazy(() => import('../modules/leadership/Page.jsx')),
  },
  {
    id: 'talent', path: '/talent', group: 'sim',
    title: '人才精英库', subtitle: '结构化人力资本图谱 · 中国政要 / 反腐透视 / 知识生产 / 资本逻辑 / 外交与海外', icon: 'UsersRound',
    component: lazy(() => import('../modules/talent/Page.jsx')),
  },
  {
    id: 'policydocs', path: '/policydocs', group: 'sim',
    title: '政令文库', subtitle: '政策文件 · 法律条文 · 文本挖掘', icon: 'FileText',
    component: lazy(() => import('../modules/policydocs/Page.jsx')),
  },
  {
    id: 'foundation',
    path: '/foundation',
    group: 'foundation',
    title: '数据底座',
    subtitle: '世界银行 · 国家统计局 · IMF',
    icon: 'Database',
    component: lazy(() => import('../modules/foundation/Page.jsx')),
  },
  {
    id: 'glossary', path: '/glossary', group: 'foundation',
    title: '术语词典', subtitle: '专有名词 · 调研术语 · 模块交叉链接', icon: 'BookOpen',
    component: lazy(() => import('../modules/glossary/Page.jsx')),
  },
  {
    id: 'watchtower', path: '/watchtower', group: 'foundation',
    title: '全局监测台', subtitle: '六域先行指标 · 三档阈值 · 越线告警', icon: 'Siren',
    component: lazy(() => import('../modules/watchtower/Page.jsx')),
  },
];

export const modulesByGroup = (groupId) => MODULES.filter((m) => m.group === groupId);
export const moduleById = (id) => MODULES.find((m) => m.id === id);
export const DEFAULT_MODULE = MODULES[0];
