import { lazy } from 'react';
import { POPULATION_SLICE_COUNT } from '../lib/gy/registry.js';
import { populationNavCompare } from '../lib/gy/navOrder.js';
import { shijianNavCompare, shijianWorldNavCompare } from '../lib/shijian/navOrder.js';

// ============================================================================
// 模块注册表 · China OS 单一数据源
// ----------------------------------------------------------------------------
// 新增一个模块 = 在 MODULES 里加一项（含 group / 路由 / 懒加载组件）。
// Shell 的导航、路由、面包屑全部由此生成，新模块「即插即用」、无需改框架。
// 分组对应框架图四层：cognition 认知内核 / lens 内容透镜 / sim 推演训练 / foundation 底座
//
// 命名约定（统一取名规范）：
//   · 主名(title)：优先 4 字；不可压缩的固定术语/榜单名按原义保留（如修昔底德陷阱、新质生产力）。
//   · 副题(subtitle)：三段式「A · B · C」，每段 2–5 字，密度一致，沿用调研系列术语。
// ============================================================================

export const GROUPS = [
  { id: 'home', label: '看板', desc: '总揽 · 实时大屏', accent: '#22d3ee' },
  { id: 'cognition', label: '认知内核', desc: '思想工具 · 理论模型', accent: '#c41e3a' },
  { id: 'lens', label: '内容透镜', desc: '四大支柱', accent: '#22d3ee' },
  { id: 'institutions', label: '制度与改革', desc: '权力 · 治理 · 法治', accent: '#e8a317' },
  { id: 'depthtopics', label: '深度专题', desc: '已迁移', accent: '#10b981' },
  { id: 'techtopics', label: '科技专题', desc: '科技树 · 深挖', accent: '#22d3ee' },
  { id: 'society', label: '社会与民生', desc: '人口 · 医保 · 住房', accent: '#f0abfc' },
  { id: 'industry', label: '产业与制造', desc: '能源 · 算力 · 链', accent: '#fb923c' },
  { id: 'finance', label: '货币金融', desc: '人民币 · 债务', accent: '#d4af37' },
  { id: 'region', label: '区域与全球化', desc: '板块 · 海洋 · 资源', accent: '#8b5cf6' },
  { id: 'heshan', label: '重构河山', desc: '区划 · 财政 · 建省', accent: '#9e2b25' },
  { id: 'security', label: '安全与国防', desc: '军事 · 台海 · 大安全', accent: '#c41e3a' },
  { id: 'population', label: '中国人群分析', desc: '人群画像总图谱 · 世代 · 阶层', accent: '#ec4899' },
  { id: 'shijian', label: '史鉴·中华', desc: '五柱 · 治乱 · 古今对照', accent: '#a83b2c' },
  { id: 'shijianWorld', label: '史鉴·世界', desc: '比较历史 · 主题带 · 中西映射', accent: '#4a6d7c' },
  { id: 'sim', label: '推演与训练', desc: '沙盒 · 内参', accent: '#d4af37' },
  { id: 'governance', label: '治理结构', desc: '观象台 · 归因 · 信号 · 三力', accent: '#79a496' },
  { id: 'huangfeizhai', label: '荒废斋', desc: '私人信息总入口 · 朱砂封印', accent: '#b18a52' },
  { id: 'foundation', label: '数据与系统', desc: '底座', accent: '#64748b' },
];

export const MODULES = [
  {
    id: 'dashboard', path: '/dashboard', group: 'home',
    title: '中枢看板', subtitle: '十五五开局 · 全局总揽 · H1 读数', icon: 'LayoutDashboard',
    component: lazy(() => import('../modules/dashboard/Page.jsx')),
  },
  {
    id: 'live-feeds', path: '/live-feeds', group: 'home',
    title: '神州实况', subtitle: '公开慢直播 · 熊猫 · 景区 · 枢纽', icon: 'Radio',
    component: lazy(() => import('../modules/dashboard/LiveFeedsPage.jsx')),
  },
  {
    id: 'shenzhou-live', path: '/shenzhou-live', group: 'home',
    title: '神州活图', subtitle: '省级分层 · 时间轴 · 对比研判', icon: 'Map',
    component: lazy(() => import('../modules/dashboard/LiveChinaMapPage.jsx')),
  },
  {
    id: 'econdash', path: '/econ-dashboard', group: 'home',
    title: '经济大盘', subtitle: '三次产业 · 金丝雀 · 2026 H1', icon: 'LineChart',
    component: lazy(() => import('../modules/econdash/Page.jsx')),
  },
  {
    // 全文并入经济大盘二级 Tab（?tab=h1review）；保留路由作深链别名并重定向
    id: 'econH1Review', path: '/econ-h1-review', group: 'home',
    title: '半年经济解读', subtitle: '三驾马车 · 结构信号 · 2026 H1', icon: 'BookOpenText',
    navHidden: true,
    component: lazy(() => import('../modules/econH1Review/Page.jsx')),
  },
  {
    // 全文并入经济大盘二级 Tab（?tab=consume15）；保留路由作深链别名并重定向
    id: 'econConsume15', path: '/econ-consume-15th', group: 'home',
    title: '十五五促消费', subtitle: '扩大消费规划 · 国函66号 · 2026-07', icon: 'ShoppingBag',
    navHidden: true,
    component: lazy(() => import('../modules/econConsume15/Page.jsx')),
  },
  {
    id: 'cognition', path: '/cognition', group: 'cognition',
    title: '康波周期', subtitle: '康德拉季耶夫 · 长波 · 创新潮', icon: 'Waves',
    component: lazy(() => import('../modules/cognition/Page.jsx')),
  },
  {
    id: 'powerphysics', path: '/powerphysics', group: 'cognition',
    title: '权力物理', subtitle: '力场强制 · 合法成本 · 信息穿透', icon: 'Magnet',
    component: lazy(() => import('../modules/powerphysics/Page.jsx')),
  },
  {
    id: 'dissipative', path: '/dissipative', group: 'cognition',
    title: '耗散结构', subtitle: '普里高津 · 负熵流 · 自组织', icon: 'Wind',
    component: lazy(() => import('../modules/dissipative/Page.jsx')),
  },
  {
    id: 'pathdependence', path: '/pathdependence', group: 'cognition',
    title: '路径依赖', subtitle: '报酬递增 · 锁定效应 · 路径换道', icon: 'GitFork',
    component: lazy(() => import('../modules/pathdependence/Page.jsx')),
  },
  {
    id: 'realism', path: '/realism', group: 'cognition',
    title: '现实主义', subtitle: '米尔斯海默 · 大国政治 · 权力制衡', icon: 'Swords',
    component: lazy(() => import('../modules/realism/Page.jsx')),
  },
  {
    id: 'middleincometrap', path: '/middleincometrap', group: 'cognition',
    title: '中等收入陷阱', subtitle: '韩国跨越 · 拉美停滞 · 中国窗口', icon: 'TrendingUp',
    component: lazy(() => import('../modules/middleincometrap/Page.jsx')),
  },
  {
    id: 'thucydides', path: '/thucydides', group: 'cognition',
    title: '修昔底德陷阱', subtitle: '艾利森 · 守成崛起 · 权力转移', icon: 'GitFork',
    component: lazy(() => import('../modules/thucydides/Page.jsx')),
  },
  {
    id: 'gametheory', path: '/gametheory', group: 'cognition',
    title: '博弈理论', subtitle: '纳什均衡 · 重复博弈 · 以牙还牙', icon: 'Dices',
    component: lazy(() => import('../modules/gametheory/Page.jsx')),
  },
  {
    id: 'antifragile', path: '/antifragile', group: 'cognition',
    title: '反脆弱性', subtitle: '塔勒布 · 凸性效应 · 波动获益', icon: 'TrendingUp',
    component: lazy(() => import('../modules/antifragile/Page.jsx')),
  },
  {
    id: 'constructivism', path: '/constructivism', group: 'cognition',
    title: '建构主义', subtitle: '温特 · 观念建构 · 无政府文化', icon: 'Network',
    component: lazy(() => import('../modules/constructivism/Page.jsx')),
  },
  {
    id: 'ideology', path: '/ideology', group: 'cognition',
    title: '意识形态', subtitle: '自由主义 · 马克思 · 社会达尔文', icon: 'Scale3d',
    component: lazy(() => import('../modules/ideology/Page.jsx')),
  },
  {
    id: 'deterrence', path: '/deterrence', group: 'cognition',
    title: '威慑战略', subtitle: '谢林 · 可信承诺 · 边缘政策', icon: 'ShieldAlert',
    component: lazy(() => import('../modules/deterrence/Page.jsx')),
  },
  {
    id: 'principalagent', path: '/principalagent', group: 'cognition',
    title: '委托代理', subtitle: '信息不对称 · 激励相容 · 道德风险', icon: 'GitBranchPlus',
    component: lazy(() => import('../modules/principalagent/Page.jsx')),
  },
  {
    id: 'commons', path: '/commons', group: 'cognition',
    title: '公地悲剧', subtitle: '集体行动 · 搭便车 · 自主治理', icon: 'Trees',
    component: lazy(() => import('../modules/commons/Page.jsx')),
  },
  {
    id: 'contradictions', path: '/contradictions', group: 'cognition',
    title: '矛盾论', subtitle: '主次矛盾 · 对立统一 · 社会矛盾体', icon: 'ArrowLeftRight',
    component: lazy(() => import('../modules/contradictions/Page.jsx')),
  },
  {
    id: 'depth',
    path: '/depth',
    group: 'lens',
    title: '深度透视',
    subtitle: '七维框架 · 多重专题 · 全景扫描',
    icon: 'Layers',
    component: lazy(() => import('../modules/depth/Page.jsx')),
  },
  {
    id: 'foodSecurity', path: '/food-security', group: 'depthtopics',
    title: '粮食安全', subtitle: '耕地红线 · 种业自主 · 大国粮仓', icon: 'Wheat',
    component: lazy(() => import('../modules/foodSecurity/Page.jsx')),
  },
  {
    id: 'urban', path: '/urban', group: 'depthtopics',
    title: '新型城镇化', subtitle: '市民化 · 城市群 · 都市圈', icon: 'Building2',
    component: lazy(() => import('../modules/urban/Page.jsx')),
  },
  {
    id: 'ecology', path: '/ecology', group: 'depthtopics',
    title: '生态文明', subtitle: '双碳目标 · 碳汇市场 · 绿水青山', icon: 'Leaf',
    component: lazy(() => import('../modules/ecology/Page.jsx')),
  },
  {
    id: 'automotive', path: '/automotive', group: 'depthtopics',
    title: '汽车主权', subtitle: '电动智能 · 换道超车 · 全球出海', icon: 'Car',
    component: lazy(() => import('../modules/automotive/Page.jsx')),
  },
  {
    id: 'dataElement', path: '/data-element', group: 'depthtopics',
    title: '数据要素', subtitle: '产权确权 · 数据入表 · 东数西算', icon: 'Binary',
    component: lazy(() => import('../modules/dataElement/Page.jsx')),
  },
  {
    id: 'digital', path: '/digital', group: 'depthtopics',
    title: '数字经济', subtitle: '数实融合 · 平台经济 · 数字治理', icon: 'Cpu',
    component: lazy(() => import('../modules/digital/Page.jsx')),
  },
  {
    id: 'digitalGiantWeb', path: '/digital-giant-web', group: 'depthtopics',
    title: '数字巨网', subtitle: '网络经济 · 赛博反馈 · 语义防火墙', icon: 'Globe2',
    component: lazy(() => import('../modules/digitalGiantWeb/Page.jsx')),
  },
  {
    id: 'bri', path: '/bri', group: 'depthtopics',
    title: '一带一路', subtitle: '六廊六路 · 中欧班列 · 互联互通', icon: 'Route',
    component: lazy(() => import('../modules/bri/Page.jsx')),
  },
  {
    id: 'foreignTrade', path: '/foreign-trade', group: 'depthtopics',
    title: '对外贸易', subtitle: '新三样 · RCEP · 2026 H1', icon: 'Ship',
    component: lazy(() => import('../modules/foreignTrade/Page.jsx')),
  },
  {
    id: 'serviceTrade', path: '/service-trade', group: 'depthtopics',
    title: '服务贸易', subtitle: '数字贸易 · 服贸创新 · 知识密集', icon: 'Globe',
    component: lazy(() => import('../modules/serviceTrade/Page.jsx')),
  },
  {
    id: 'instOpen', path: '/inst-open', group: 'depthtopics',
    title: '制度开放', subtitle: '自贸试验 · 负面清单 · 规则对接', icon: 'DoorOpen',
    component: lazy(() => import('../modules/instOpen/Page.jsx')),
  },
  {
    id: 'civilAviation', path: '/civil-aviation', group: 'depthtopics',
    title: '民用航空', subtitle: 'C919 · 适航取证 · 低空经济', icon: 'Plane',
    component: lazy(() => import('../modules/civilAviation/Page.jsx')),
  },
  {
    id: 'culture',
    path: '/culture',
    group: 'depthtopics',
    title: '文化软实力',
    subtitle: '国潮崛起 · 短剧出海 · 文化贸易',
    icon: 'Sparkles',
    component: lazy(() => import('../modules/culture/Page.jsx')),
  },
  {
    id: 'private', path: '/private', group: 'depthtopics',
    title: '民营经济', subtitle: '56789 · 公平竞争 · 产权保护', icon: 'Briefcase',
    component: lazy(() => import('../modules/private/Page.jsx')),
  },
  {
    id: 'quantum', path: '/quantum', group: 'techtopics',
    title: '量子信息', subtitle: '量子计算 · 量子通信 · 量子测量', icon: 'Atom',
    component: lazy(() => import('../modules/quantum/Page.jsx')),
  },
  {
    id: 'semiconductor', path: '/semiconductor', group: 'techtopics',
    title: '集成电路', subtitle: '芯片主权 · 大基金 · 先进制程', icon: 'CircuitBoard',
    component: lazy(() => import('../modules/semiconductor/Page.jsx')),
  },
  {
    id: 'aiplus', path: '/aiplus', group: 'techtopics',
    title: '人工智能+', subtitle: '智算底座 · 行业模型 · 赋能百业', icon: 'BrainCog',
    component: lazy(() => import('../modules/aiplus/Page.jsx')),
  },
  {
    id: 'basicResearch', path: '/basic-research', group: 'techtopics',
    title: '基础研究', subtitle: '国家实验室 · 评价改革 · 原始创新', icon: 'FlaskConical',
    component: lazy(() => import('../modules/basicResearch/Page.jsx')),
  },
  {
    id: 'powerlogic', path: '/powerlogic', group: 'institutions',
    title: '权力逻辑', subtitle: '儒表法里 · 数字利维坦 · 统治成本', icon: 'Cpu',
    component: lazy(() => import('../modules/powerlogic/Page.jsx')),
  },
  {
    id: 'reform', path: '/reform', group: 'institutions',
    title: '改革开放', subtitle: '现实主义 · 算法演进 · 摸石过河', icon: 'GitFork',
    component: lazy(() => import('../modules/reform/Page.jsx')),
  },
  {
    id: 'governance', path: '/governance', group: 'institutions',
    title: '治理现代化', subtitle: '网格管理 · 数字政府 · 多元共治', icon: 'Network',
    component: lazy(() => import('../modules/governance/Page.jsx')),
  },
  {
    id: 'govsystem', path: '/govsystem', group: 'institutions',
    title: '政府体系', subtitle: '压力体制 · 执行算法 · 央地关系', icon: 'Workflow',
    component: lazy(() => import('../modules/govsystem/Page.jsx')),
  },
  {
    id: 'soe', path: '/soe', group: 'institutions',
    title: '国有资本', subtitle: '战略底座 · 链主企业 · 国资改革', icon: 'Building',
    component: lazy(() => import('../modules/soe/Page.jsx')),
  },
  {
    id: 'enterprise500', path: '/enterprise500', group: 'industry',
    title: '民企500强', subtitle: '工商联榜 · 治理透视 · 行业分布', icon: 'Building2',
    component: lazy(() => import('../modules/enterprise500/Page.jsx')),
  },
  {
    id: 'ruleoflaw', path: '/ruleoflaw', group: 'institutions',
    title: '法治建设', subtitle: '智慧法院 · 涉外法治 · 营商环境', icon: 'Scale',
    component: lazy(() => import('../modules/ruleoflaw/Page.jsx')),
  },
  {
    id: 'unifiedMarket', path: '/unified-market', group: 'institutions',
    title: '统一大市场', subtitle: '五个统一 · 破除壁垒 · 要素流通', icon: 'Store', accent: '#e8a317',
    component: lazy(() => import('../modules/unifiedMarket/Page.jsx')),
  },
  { id: 'demographic', path: '/demographic', group: 'society', title: '人口结构', subtitle: '负增长 · 育儿补贴 · 老龄化', icon: 'Users', component: lazy(() => import('../modules/demographic/Page.jsx')) },
  { id: 'gig', path: '/gig', group: 'society', title: '零工经济', subtitle: '蓄水池 · 算法治理 · 新业态', icon: 'Bike', component: lazy(() => import('../modules/gig/Page.jsx')) },
  { id: 'healthcare', path: '/healthcare', group: 'society', title: '医疗医保', subtitle: 'DRG · 药品集采 · 分级诊疗', icon: 'Stethoscope', component: lazy(() => import('../modules/healthcare/Page.jsx')) },
  { id: 'socialgov', path: '/socialgov', group: 'society', title: '基层治理', subtitle: '网格管理 · 综治中心 · 枫桥经验', icon: 'LayoutGrid', component: lazy(() => import('../modules/socialgov/Page.jsx')) },
  { id: 'housing', path: '/housing', group: 'society', title: '住房地产', subtitle: '行业周期 · 保障房 · 三大工程', icon: 'Home', component: lazy(() => import('../modules/housing/Page.jsx')) },
  { id: 'education', path: '/education', group: 'society', title: '教育体系', subtitle: '普职分流 · 高考改革 · 人才培养', icon: 'GraduationCap', component: lazy(() => import('../modules/education/Page.jsx')) },
  { id: 'consumption', path: '/consumption', group: 'society', title: '扩大内需', subtitle: '消费率 · 服务化 · 以旧换新', icon: 'ShoppingCart', accent: '#c41e3a', component: lazy(() => import('../modules/consumption/Page.jsx')) },
  { id: 'silverEconomy', path: '/silver-economy', group: 'society', title: '银发经济', subtitle: '9073 · 养老服务 · 适老改造', icon: 'HeartHandshake', accent: '#8b5cf6', component: lazy(() => import('../modules/silverEconomy/Page.jsx')) },
  { id: 'fertilitySupport', path: '/fertility-support', group: 'society', title: '生育支持', subtitle: '生育补贴 · 普惠托育 · 友好社会', icon: 'Baby', accent: '#ec4899', component: lazy(() => import('../modules/fertilitySupport/Page.jsx')) },
  { id: 'tcmHealth', path: '/tcm-health', group: 'society', title: '中医药', subtitle: '重大工程 · 传承创新 · 治未病', icon: 'Flower2', component: lazy(() => import('../modules/tcmHealth/Page.jsx')) },
  {
    id: 'renqunTupu',
    path: '/modules/renqun-tupu',
    group: 'population',
    title: '人群画像总图谱',
    subtitle: `${POPULATION_SLICE_COUNT} 片切片 · 八轴全光谱 · 母索引`,
    icon: 'Network',
    component: lazy(() => import('../modules/renqun-tupu/Page.jsx')),
  },
  {
    id: 'huangfeizhaiHub',
    path: '/modules/huangfeizhai',
    group: 'huangfeizhai',
    title: '荒废斋',
    subtitle: '私人信息总入口 · 总览',
    icon: 'Lock',
    accent: '#b18a52',
    component: lazy(() => import('../modules/huangfeizhai/Page.jsx')),
  },
  {
    id: 'personalReview',
    path: '/modules/personal-review',
    group: 'huangfeizhai',
    title: '决策复盘',
    subtitle: '超个体 · 四层垫子 · 信号灯联动',
    icon: 'ClipboardCheck',
    accent: '#b18a52',
    component: lazy(() => import('../modules/personalReview/Page.jsx')),
  },
  {
    id: 'anticorruption',
    path: '/modules/anticorruption',
    group: 'huangfeizhai',
    title: '反腐结构观测',
    subtitle: 'v2.0 · 腐败密度地图 · 2012—2026 回测',
    icon: 'Scale',
    accent: '#cf4a3d',
    component: lazy(() => import('../modules/anticorruption/Page.jsx')),
  },
  {
    id: 'ableOfficialParadox',
    path: '/modules/able-official-paradox',
    group: 'huangfeizhai',
    title: '能吏悖论',
    subtitle: '能办事 = 能寻租 · 同一种能力',
    icon: 'Users',
    accent: '#cf9a32',
    component: lazy(() => import('../modules/ableOfficialParadox/Page.jsx')),
  },
  {
    id: 'haydenSlice',
    path: '/modules/me',
    group: 'huangfeizhai',
    title: '私享切片',
    subtitle: '李贺 / Hayden · 迁移日志 · 自画像',
    icon: 'UserCircle',
    accent: '#79a496',
    component: lazy(() => import('../modules/me/Page.jsx')),
  },
  {
    id: 'qingnian',
    path: '/modules/qingnian',
    group: 'population',
    title: '青年',
    subtitle: '机器的盲区 · 概率的暗物质',
    icon: 'UserRound',
    component: lazy(() => import('../modules/qingnian/Page.jsx')),
  },
  {
    id: 'xingshaoshu',
    path: '/modules/xingshaoshu',
    group: 'population',
    title: '性少数',
    subtitle: '挤压性存在',
    icon: 'UsersRound',
    component: lazy(() => import('../modules/xingshaoshu/Page.jsx')),
  },
  {
    id: 'linggong',
    path: '/modules/linggong',
    group: 'population',
    title: '零工经济',
    subtitle: '悬空的基础设施',
    icon: 'Bike',
    component: lazy(() => import('../modules/linggong/Page.jsx')),
  },
  {
    id: 'nongmingong',
    path: '/modules/nongmingong',
    group: 'population',
    title: '农民工',
    subtitle: '未完成的迁徙 · 换页内存',
    icon: 'HardHat',
    component: lazy(() => import('../modules/nongmingong/Page.jsx')),
  },
  {
    id: 'tizhinei',
    path: '/modules/tizhinei',
    group: 'population',
    title: '体制内',
    subtitle: '常驻内存 · 刚兑的最后分区',
    icon: 'Landmark',
    component: lazy(() => import('../modules/tizhinei/Page.jsx')),
  },
  {
    id: 'zhongchan',
    path: '/modules/zhongchan',
    group: 'population',
    title: '中产',
    subtitle: '质押态进程 · 三张折价的凭证',
    icon: 'Briefcase',
    component: lazy(() => import('../modules/zhongchan/Page.jsx')),
  },
  {
    id: 'laonian',
    path: '/modules/laonian',
    group: 'population',
    title: '老年',
    subtitle: '应计负债 · 账期已至',
    icon: 'PersonStanding',
    component: lazy(() => import('../modules/laonian/Page.jsx')),
  },
  {
    id: 'tajian',
    path: '/modules/tajian',
    group: 'population',
    title: '塔尖阶层',
    subtitle: '可迁移进程 · 要钱不要人的塔尖',
    icon: 'Crown',
    component: lazy(() => import('../modules/tajian/Page.jsx')),
  },
  {
    id: 'zhixiao',
    path: '/modules/zhixiao',
    group: 'population',
    title: '职校生',
    subtitle: '编译期定价 · 十五岁的一次性判决',
    icon: 'Wrench',
    component: lazy(() => import('../modules/zhixiao/Page.jsx')),
  },
  {
    id: 'tuiyi',
    path: '/modules/tuiyi',
    group: 'population',
    title: '退役军人',
    subtitle: '预装组织力 · 被定向赎买的人群',
    icon: 'Medal',
    component: lazy(() => import('../modules/tuiyi/Page.jsx')),
  },
  {
    id: 'yiyi',
    path: '/modules/yiyi',
    group: 'population',
    title: '信仰人群',
    subtitle: '无主端口 · 被许可的玄学',
    icon: 'Flame',
    component: lazy(() => import('../modules/yiyi/Page.jsx')),
  },
  {
    id: 'liupiao',
    path: '/modules/liupiao',
    group: 'population',
    title: '创作者',
    subtitle: '彩票调度 · 用中奖伪装的职业',
    icon: 'Clapperboard',
    component: lazy(() => import('../modules/liupiao/Page.jsx')),
  },
  {
    id: 'yibao',
    path: '/modules/yibao',
    group: 'population',
    title: '医保群体',
    subtitle: '全员接口 · 单方面改版的契约',
    icon: 'Cross',
    component: lazy(() => import('../modules/yibao/Page.jsx')),
  },
  {
    id: 'lian',
    path: '/modules/lian',
    group: 'population',
    title: '离岸华人',
    subtitle: '境外节点 · 未结清的账户',
    icon: 'Plane',
    component: lazy(() => import('../modules/lian/Page.jsx')),
  },
  {
    id: 'zhongnv',
    path: '/modules/zhongnv',
    group: 'population',
    title: '中年女性',
    subtitle: '后台守护进程 · 被折叠的一代 · GY-17',
    icon: 'HeartHandshake',
    component: lazy(() => import('../modules/zhongnv/Page.jsx')),
  },
  {
    id: 'canzhang',
    path: '/modules/canzhang',
    group: 'population',
    title: '残障人群',
    subtitle: '未挂载设备 · 可见性的零点 · GY-18',
    icon: 'Accessibility',
    component: lazy(() => import('../modules/canzhang/Page.jsx')),
  },
  {
    id: 'danshen',
    path: '/modules/danshen',
    group: 'population',
    title: '单身女性与不婚者',
    subtitle: '独立运行实例 · 退出常态化 · GY-19',
    icon: 'UserRound',
    component: lazy(() => import('../modules/danshen/Page.jsx')),
  },
  {
    id: 'xianyu',
    path: '/modules/xianyu',
    group: 'population',
    title: '县域青年',
    subtitle: '未被监控的中间件 · 留下的人 · GY-20',
    icon: 'MapPin',
    component: lazy(() => import('../modules/xianyu/Page.jsx')),
  },
  {
    id: 'xinyimin',
    path: '/modules/xinyimin',
    group: 'population',
    title: '城市新移民',
    subtitle: '访客会话 · 有城无籍 · GY-21',
    icon: 'DoorClosed',
    component: lazy(() => import('../modules/xinyimin/Page.jsx')),
  },
  {
    id: 'jigong',
    path: '/modules/jigong',
    group: 'population',
    title: '制造业技术工人',
    subtitle: '关键依赖 · 被需要却不被向往 · GY-22',
    icon: 'Wrench',
    component: lazy(() => import('../modules/jigong/Page.jsx')),
  },
  {
    id: 'manbing',
    path: '/modules/manbing',
    group: 'population',
    title: '带病青年',
    subtitle: '提前折旧的电池 · 健康阶层化 · GY-23',
    icon: 'HeartPulse',
    component: lazy(() => import('../modules/manbing/Page.jsx')),
  },
  {
    id: 'moshao',
    path: '/modules/moshao',
    group: 'population',
    title: '基层治理末梢',
    subtitle: '借权代理进程 · 编外治理者 · GY-24',
    icon: 'LayoutGrid',
    component: lazy(() => import('../modules/moshao/Page.jsx')),
  },
  {
    id: 'shidu',
    path: '/modules/shidu',
    group: 'population',
    title: '失独与计生后遗',
    subtitle: '已废弃契约 · 政策账单活体 · GY-25',
    icon: 'Hourglass',
    component: lazy(() => import('../modules/shidu/Page.jsx')),
  },
  {
    id: 'shuzi',
    path: '/modules/shuzi',
    group: 'population',
    title: '数字原住民',
    subtitle: '被改写的引导程序 · 屏幕养大的一代 · GY-26',
    icon: 'Smartphone',
    component: lazy(() => import('../modules/shuzi/Page.jsx')),
  },
  {
    id: 'huoche',
    path: '/modules/huoche',
    group: 'population',
    title: '货车司机',
    subtitle: '轮子上的实时进程 · 北斗即调度器 · GY-27',
    icon: 'Truck',
    component: lazy(() => import('../modules/huoche/Page.jsx')),
  },
  {
    id: 'chengxu',
    path: '/modules/chengxu',
    group: 'population',
    title: '程序员',
    subtitle: '自我弃用的进程 · 35岁折旧 · GY-28',
    icon: 'Code2',
    component: lazy(() => import('../modules/chengxu/Page.jsx')),
  },
  {
    id: 'getihu',
    path: '/modules/getihu',
    group: 'population',
    title: '个体工商户',
    subtitle: '裸跑进程 · 自负盈亏到底 · GY-29',
    icon: 'Store',
    component: lazy(() => import('../modules/getihu/Page.jsx')),
  },
  {
    id: 'liushou',
    path: '/modules/liushou',
    group: 'population',
    title: '农村留守老人',
    subtitle: '断电的边缘节点 · 城乡断层最底端 · GY-30',
    icon: 'Tractor',
    component: lazy(() => import('../modules/liushou/Page.jsx')),
  },
  {
    id: 'jiazheng',
    path: '/modules/jiazheng',
    group: 'population',
    title: '家政与照护工人',
    subtitle: '出借的守护进程 · 照护别家自家停摆 · GY-31',
    icon: 'HandHeart',
    component: lazy(() => import('../modules/jiazheng/Page.jsx')),
  },
  {
    id: 'zhaiwu',
    path: '/modules/zhaiwu',
    group: 'population',
    title: '失信与债务人群',
    subtitle: '被标记的账户 · 信用即权限 · GY-32',
    icon: 'CreditCard',
    component: lazy(() => import('../modules/zhaiwu/Page.jsx')),
  },
  {
    id: 'qingjiao',
    path: '/modules/qingjiao',
    group: 'population',
    title: '高校青椒',
    subtitle: '非升即走 · 学术临时工 · GY-33',
    icon: 'GraduationCap',
    component: lazy(() => import('../modules/qingjiao/Page.jsx')),
  },
  {
    id: 'manjiu',
    path: '/modules/manjiu',
    group: 'population',
    title: '慢就业青年',
    subtitle: '主动挂起的进程 · 全职儿女NEET · GY-34',
    icon: 'Armchair',
    component: lazy(() => import('../modules/manjiu/Page.jsx')),
  },
  {
    id: 'xinnong',
    path: '/modules/xinnong',
    group: 'population',
    title: '职业农民与新农人',
    subtitle: '不可关闭的根服务 · 谁来种地 · GY-35',
    icon: 'Wheat',
    component: lazy(() => import('../modules/xinnong/Page.jsx')),
  },
  {
    id: 'yulun',
    path: '/modules/yulun',
    group: 'population',
    title: '网络舆论场',
    subtitle: '情绪中断风暴 · 受众即弹药 · GY-36',
    icon: 'MessagesSquare',
    component: lazy(() => import('../modules/yulun/Page.jsx')),
  },
  {
    id: 'yihu',
    path: '/modules/yihu',
    group: 'population',
    title: '医护人员',
    subtitle: '满载的服务进程 · 医患同困 · GY-37',
    icon: 'Stethoscope',
    component: lazy(() => import('../modules/yihu/Page.jsx')),
  },
  {
    id: 'jiaoshi',
    path: '/modules/jiaoshi',
    group: 'population',
    title: '中小学教师',
    subtitle: '优先级反转 · 教学排在最后 · GY-38',
    icon: 'BookOpen',
    component: lazy(() => import('../modules/jiaoshi/Page.jsx')),
  },
  {
    id: 'baoan',
    path: '/modules/baoan',
    group: 'population',
    title: '保安群体',
    subtitle: '空闲轮询的待命进程 · 在场即服务 · GY-39',
    icon: 'ShieldCheck',
    component: lazy(() => import('../modules/baoan/Page.jsx')),
  },
  {
    id: 'wangyue',
    path: '/modules/wangyue',
    group: 'population',
    title: '网约车司机',
    subtitle: '竞价实例 · 一口价的运力 · GY-40',
    icon: 'CarTaxiFront',
    component: lazy(() => import('../modules/wangyue/Page.jsx')),
  },
  {
    id: 'baoxian',
    path: '/modules/baoxian',
    group: 'population',
    title: '保险代理',
    subtitle: '增员制进程树 · 大进大出 · GY-41',
    icon: 'Umbrella',
    component: lazy(() => import('../modules/baoxian/Page.jsx')),
  },
  {
    id: 'minqi',
    path: '/modules/minqi',
    group: 'population',
    title: '中小民营企业主',
    subtitle: '夹心资本 · 账期与融资两头挤 · GY-42',
    icon: 'Building',
    component: lazy(() => import('../modules/minqi/Page.jsx')),
  },
  {
    id: 'jipin',
    path: '/modules/jipin',
    group: 'population',
    title: '城市极贫与救助对象',
    subtitle: '最低保活进程 · 社会救助兜底 · GY-43',
    icon: 'LifeBuoy',
    component: lazy(() => import('../modules/jipin/Page.jsx')),
  },
  {
    id: 'jiaozheng',
    path: '/modules/jiaozheng',
    group: 'population',
    title: '社区矫正与刑释人员',
    subtitle: '权限残留 · 回归社会困境 · GY-44',
    icon: 'Unlock',
    component: lazy(() => import('../modules/jiaozheng/Page.jsx')),
  },
  {
    id: 'funv',
    path: '/modules/funv',
    group: 'population',
    title: '农村留守妇女',
    subtitle: '独自维持集群的主节点 · 三留守承重轴 · GY-45',
    icon: 'Home',
    component: lazy(() => import('../modules/funv/Page.jsx')),
  },
  {
    id: 'binzang',
    path: '/modules/binzang',
    group: 'population',
    title: '殡葬与临终关怀',
    subtitle: '进程回收器 · 送最后一程 · GY-46',
    icon: 'Heart',
    component: lazy(() => import('../modules/binzang/Page.jsx')),
  },
  {
    id: 'junren',
    path: '/modules/junren',
    group: 'population',
    title: '现役军人',
    subtitle: '内核态特权进程 · 党指挥枪 · GY-47',
    icon: 'Shield',
    component: lazy(() => import('../modules/junren/Page.jsx')),
  },
  {
    id: 'bianjiang',
    path: '/modules/bianjiang',
    group: 'population',
    title: '边疆少数民族',
    subtitle: '多框架并置 · 争议中的边疆 · GY-48',
    icon: 'Mountain',
    component: lazy(() => import('../modules/bianjiang/Page.jsx')),
  },
  {
    id: 'jiedu',
    path: '/modules/jiedu',
    group: 'population',
    title: '戒毒与社区康复人员',
    subtitle: '被标记需修复的进程 · 戒断之后 · GY-49',
    icon: 'Pill',
    component: lazy(() => import('../modules/jiedu/Page.jsx')),
  },
  {
    id: 'zhiyebing',
    path: '/modules/zhiyebing',
    group: 'population',
    title: '尘肺与职业病群体',
    subtitle: '延迟显现的硬件损耗 · 吸进去的工龄 · GY-50',
    icon: 'Activity',
    component: lazy(() => import('../modules/zhiyebing/Page.jsx')),
  },
  {
    id: 'zhengdi',
    path: '/modules/zhengdi',
    group: 'population',
    title: '征地拆迁与失地农民',
    subtitle: '存储被征用 · 一次性置换 · GY-51',
    icon: 'MapPinned',
    component: lazy(() => import('../modules/zhengdi/Page.jsx')),
  },
  {
    id: 'fangui',
    path: '/modules/fangui',
    group: 'population',
    title: '被拐卖与反拐救助',
    subtitle: '寻址丢失 · 回家的路 · GY-52',
    icon: 'MapPin',
    component: lazy(() => import('../modules/fangui/Page.jsx')),
  },
  {
    id: 'hanjian',
    path: '/modules/hanjian',
    group: 'population',
    title: '罕见病与大病群体',
    subtitle: '低概率分支 · 个体罕见群体庞大 · GY-53',
    icon: 'Dna',
    component: lazy(() => import('../modules/hanjian/Page.jsx')),
  },
  {
    id: 'ertong',
    path: '/modules/ertong',
    group: 'population',
    title: '流动与留守儿童',
    subtitle: '亲代缺失/迁移的子进程 · 监护链断裂 · GY-54',
    icon: 'Baby',
    component: lazy(() => import('../modules/ertong/Page.jsx')),
  },
  {
    id: 'jingzhang',
    path: '/modules/jingzhang',
    group: 'population',
    title: '精神障碍者与被监护人',
    subtitle: '执行权限被代理 · 替他做主之前 · GY-55',
    icon: 'Brain',
    component: lazy(() => import('../modules/jingzhang/Page.jsx')),
  },
  {
    id: 'gongyi',
    path: '/modules/gongyi',
    group: 'population',
    title: '工程移民与生态移民',
    subtitle: '被整体迁移的进程集群 · 搬得出之后 · GY-56',
    icon: 'Waves',
    component: lazy(() => import('../modules/gongyi/Page.jsx')),
  },
  {
    id: 'ganran',
    path: '/modules/ganran',
    group: 'population',
    title: '受污名疾病与感染者群体',
    subtitle: '被反复误报的良性进程 · 测不到即不传染 · GY-57',
    icon: 'ShieldAlert',
    component: lazy(() => import('../modules/ganran/Page.jsx')),
  },
  {
    id: 'xinfang',
    path: '/modules/xinfang',
    group: 'population',
    title: '信访群体',
    subtitle: '系统的例外上报通道 · 下情上达 · GY-58',
    icon: 'Inbox',
    component: lazy(() => import('../modules/xinfang/Page.jsx')),
  },
  { id: 'manufacturing', path: '/manufacturing', group: 'industry', title: '制造强国', subtitle: '规模优势 · GVC位势 · 转型升级', icon: 'Factory', component: lazy(() => import('../modules/manufacturing/Page.jsx')) },
  { id: 'robotics', path: '/robotics', group: 'industry', title: '机器人', subtitle: '装机密度 · 人形整机 · 核心部件', icon: 'Bot', component: lazy(() => import('../modules/robotics/Page.jsx')) },
  { id: 'materials', path: '/materials', group: 'industry', title: '关键材料', subtitle: '卡脖子 · 国产替代 · 前沿材料', icon: 'Gem', component: lazy(() => import('../modules/materials/Page.jsx')) },
  { id: 'energy', path: '/energy', group: 'industry', title: '能源安全', subtitle: '压舱石 · 绿色转型 · 油气保供', icon: 'Zap', component: lazy(() => import('../modules/energy/Page.jsx')) },
  { id: 'nuclear', path: '/nuclear', group: 'industry', title: '核能电力', subtitle: '华龙一号 · 四代堆 · 核燃料', icon: 'Radiation', component: lazy(() => import('../modules/nuclear/Page.jsx')) },
  { id: 'hydrogen', path: '/hydrogen', group: 'industry', title: '氢能产业', subtitle: '绿氢制取 · 储运加注 · 燃料电池', icon: 'Droplets', component: lazy(() => import('../modules/hydrogen/Page.jsx')) },
  { id: 'smartgrid', path: '/smartgrid', group: 'industry', title: '智能电网', subtitle: '特高压 · 新型储能 · 源网荷储', icon: 'PlugZap', component: lazy(() => import('../modules/smartgrid/Page.jsx')) },
  { id: 'computing', path: '/computing', group: 'industry', title: '算力设施', subtitle: '东数西算 · 智算中心 · 算力主权', icon: 'Server', component: lazy(() => import('../modules/computing/Page.jsx')) },
  { id: 'logistics', path: '/logistics', group: 'industry', title: '现代物流', subtitle: '多式联运 · 降本增效 · 冷链网络', icon: 'Truck', component: lazy(() => import('../modules/logistics/Page.jsx')) },
  { id: 'supplychain', path: '/supplychain', group: 'industry', title: '供应链', subtitle: '冗余备份 · 韧性安全 · 自主可控', icon: 'Link2', component: lazy(() => import('../modules/supplychain/Page.jsx')) },
  { id: 'infrastructure', path: '/infrastructure', group: 'industry', title: '基础设施', subtitle: '新老基建 · 算力 · 十五五', icon: 'Construction', component: lazy(() => import('../modules/infrastructure/Page.jsx')) },
  { id: 'megaprojects', path: '/megaprojects', group: 'industry', title: '超级工程', subtitle: '多维ROI · 国家账本 · 战略投资', icon: 'Hammer', component: lazy(() => import('../modules/megaprojects/Page.jsx')) },
  { id: 'space', path: '/space', group: 'industry', title: '航天产业', subtitle: '北斗组网 · 商业航天 · 深空探测', icon: 'Satellite', component: lazy(() => import('../modules/space/Page.jsx')) },
  { id: 'lowAltitude', path: '/low-altitude', group: 'industry', title: '低空经济', subtitle: 'eVTOL · 无人机 · 通用航空', icon: 'PlaneTakeoff', accent: '#22d3ee', component: lazy(() => import('../modules/lowAltitude/Page.jsx')) },
  { id: 'medequipment', path: '/medequipment', group: 'industry', title: '医疗装备', subtitle: '高端影像 · 进口替代 · 自主器械', icon: 'HeartPulse', component: lazy(() => import('../modules/medequipment/Page.jsx')) },
  { id: 'tourism', path: '/tourism', group: 'industry', title: '文旅消费', subtitle: '入境旅游 · 区域品牌 · 消费升级', icon: 'Luggage', component: lazy(() => import('../modules/tourism/Page.jsx')) },
  { id: 'finance', path: '/finance-system', group: 'finance', title: '金融系统', subtitle: '系统风险 · 宏观审慎 · 金融安全', icon: 'Landmark', component: lazy(() => import('../modules/finance/Page.jsx')) },
  { id: 'marketPulse', path: '/market-pulse', group: 'finance', title: '全球资产脉搏', subtitle: '股市 · 债市 · 汇市 · 大宗', icon: 'Activity', accent: '#22d3ee', component: lazy(() => import('../modules/marketPulse/Page.jsx')) },
  { id: 'capitalMarket', path: '/capital-market', group: 'finance', title: '资本市场', subtitle: '耐心资本 · 注册制 · 创投', icon: 'TrendingUp', component: lazy(() => import('../modules/capitalMarket/Page.jsx')) },
  { id: 'financeRmb', path: '/rmb', group: 'finance', title: '人民币国际化', subtitle: 'CIPS · e-CNY · 跨境结算', icon: 'CircleDollarSign', component: lazy(() => import('../modules/financeRmb/Page.jsx')) },
  { id: 'fdi', path: '/fdi', group: 'finance', title: '跨境投资', subtitle: '负面清单 · 双向流动 · 外资准入', icon: 'ArrowLeftRight', component: lazy(() => import('../modules/fdi/Page.jsx')) },
  { id: 'greenfinance', path: '/green-finance', group: 'finance', title: '绿色金融', subtitle: '绿色债券 · 碳定价 · 转型金融', icon: 'Leaf', component: lazy(() => import('../modules/greenfinance/Page.jsx')) },
  { id: 'debtHeatmap', path: '/debt', group: 'finance', title: '地方债务', subtitle: '省际热力 · 隐性债务 · 化债方案', icon: 'Flame', component: lazy(() => import('../modules/debtHeatmap/Page.jsx')) },
  { id: 'benchmark', path: '/benchmark', group: 'region', title: '国际对标', subtitle: '中美日德 · 多维对标 · 全球坐标', icon: 'BarChart3', component: lazy(() => import('../modules/benchmark/Page.jsx')) },
  { id: 'rural', path: '/rural', group: 'region', title: '乡村振兴', subtitle: '县域经济 · 土地制度 · 城乡融合', icon: 'Tractor', component: lazy(() => import('../modules/rural/Page.jsx')) },
  { id: 'frontierGov', path: '/frontier-gov', group: 'region', title: '边疆治理', subtitle: '兴边富民 · 对口支援 · 共同体', icon: 'Mountain', component: lazy(() => import('../modules/frontierGov/Page.jsx')) },
  { id: 'regional', path: '/regional', group: 'region', title: '区域协调', subtitle: '四大板块 · 十五五 · 转移支付', icon: 'Map', component: lazy(() => import('../modules/regional/Page.jsx')) },
  { id: 'northeastRevival', path: '/northeast', group: 'region', title: '东北振兴', subtitle: '老工业基地 · 全面振兴 · 十五五', icon: 'Factory', component: lazy(() => import('../modules/northeastRevival/Page.jsx')) },
  { id: 'marine', path: '/marine', group: 'region', title: '海洋经济', subtitle: '海洋权益 · 船舶制造 · 深海开发', icon: 'Anchor', component: lazy(() => import('../modules/marine/Page.jsx')) },
  { id: 'polar', path: '/polar', group: 'region', title: '极地战略', subtitle: '北极航道 · 极地科考 · 资源博弈', icon: 'Snowflake', component: lazy(() => import('../modules/polar/Page.jsx')) },
  { id: 'resources', path: '/resources', group: 'region', title: '海外资源', subtitle: '权益矿山 · 航道安全 · 资源主权', icon: 'Pickaxe', component: lazy(() => import('../modules/resources/Page.jsx')) },
  { id: 'offshore', path: '/offshore', group: 'region', title: '港澳离岸', subtitle: '普通法窗 · 离岸RMB · 资本通道', icon: 'Banknote', component: lazy(() => import('../modules/offshore/Page.jsx')) },
  {
    id: 'heshanReform', path: '/modules/heshan/reform', group: 'heshan',
    title: '重构山河', subtitle: '区划诊断 · 收支倒挂 · 建省沙盘', icon: 'MapPinned', accent: '#9e2b25',
    component: lazy(() => import('../modules/heshanReform/Page.jsx')),
  },
  {
    id: 'heshanFactsheets', path: '/modules/heshan/factsheets', group: 'heshan',
    title: '新省图册', subtitle: '三十四份建省档案 · 人口 GDP', icon: 'BookMarked', accent: '#9e2b25',
    component: lazy(() => import('../modules/heshanFactsheets/Page.jsx')),
  },
  {
    id: 'heshanFiscal', path: '/modules/heshan/fiscal', group: 'heshan',
    title: '财政沙盘', subtitle: '转移支付 · 减层节支 · 债务过渡', icon: 'Calculator', accent: '#9e2b25',
    component: lazy(() => import('../modules/heshanFiscal/Page.jsx')),
  },
  {
    id: 'heshanCalibration', path: '/modules/heshan/calibration', group: 'heshan',
    title: '数据校准', subtitle: '建省口径 · 逐市加总 · 可审计', icon: 'TableProperties', accent: '#9e2b25',
    component: lazy(() => import('../modules/heshanCalibration/Page.jsx')),
  },
  { id: 'industrysoftware', path: '/industry-software', group: 'techtopics', title: '工业软件', subtitle: 'CAD/CAE · 自主信创 · 国产替代', icon: 'Code2', component: lazy(() => import('../modules/industrysoftware/Page.jsx')) },
  { id: 'tech', path: '/tech-policy', group: 'techtopics', title: '创新体系', subtitle: '研发投入 · 高新企业 · 成果转化', icon: 'Lightbulb', component: lazy(() => import('../modules/tech/Page.jsx')) },
  { id: 'npf', path: '/npf', group: 'techtopics', title: '新质生产力', subtitle: '未来产业 · 全要素率 · 技术跃迁', icon: 'Rocket', component: lazy(() => import('../modules/npf/Page.jsx')) },
  { id: 'bio', path: '/bio', group: 'techtopics', title: '生物医药', subtitle: '创新药械 · 生物安全 · 出海授权', icon: 'Dna', component: lazy(() => import('../modules/bio/Page.jsx')) },
  { id: 'neural', path: '/neural', group: 'techtopics', title: '脑机接口', subtitle: '神经接口 · 数据主权 · 人机融合', icon: 'Brain', component: lazy(() => import('../modules/neural/Page.jsx')) },
  { id: 'futureIndustry', path: '/future-industry', group: 'techtopics', title: '未来产业', subtitle: '具身智能 · 可控聚变 · 生物制造', icon: 'Telescope', accent: '#22d3ee', component: lazy(() => import('../modules/futureIndustry/Page.jsx')) },
  { id: 'eduSciTalent', path: '/edu-sci-talent', group: 'techtopics', title: '教科人才', subtitle: '教育链 · 科技链 · 人才链', icon: 'BookOpenCheck', accent: '#10b981', component: lazy(() => import('../modules/eduSciTalent/Page.jsx')) },
  {
    id: 'military', path: '/military', group: 'security',
    title: '军事力量', subtitle: '战区联合 · 主战装备 · 全球基地', icon: 'Shield',
    component: lazy(() => import('../modules/military/Page.jsx')),
  },
  {
    id: 'straits', path: '/straits', group: 'security',
    title: '台海局势', subtitle: '地缘重力 · 硅盾屏障 · 统一进程', icon: 'Crosshair',
    component: lazy(() => import('../modules/straits/Page.jsx')),
  },
  {
    id: 'omnisecurity', path: '/omnisecurity', group: 'security',
    title: '大安全观', subtitle: '粮食安全 · 能源安全 · 网络安全', icon: 'ShieldCheck',
    component: lazy(() => import('../modules/omnisecurity/Page.jsx')),
  },
  {
    id: 'redweb', path: '/redweb', group: 'security',
    title: '红色巨网', subtitle: '权贵网络 · 结构分析 · 利益图谱', icon: 'Network',
    component: lazy(() => import('../modules/redweb/Page.jsx')),
  },
  {
    id: 'publicSafety', path: '/public-safety', group: 'security',
    title: '公共安全', subtitle: '防灾减灾 · 应急管理 · 韧性城市', icon: 'Siren', accent: '#c41e3a',
    component: lazy(() => import('../modules/publicSafety/Page.jsx')),
  },
  {
    id: 'defenseMobilization', path: '/defense-mobilization', group: 'security',
    title: '国防动员', subtitle: '后备力量 · 平战结合 · 新域新质', icon: 'ShieldHalf',
    component: lazy(() => import('../modules/defenseMobilization/Page.jsx')),
  },
  {
    id: 'civilization',
    path: '/civilization',
    group: 'lens',
    title: '文明透视',
    subtitle: '十二卷源码 · 文明基因 · 历史底片',
    icon: 'ScrollText',
    wildcard: true,
    component: lazy(() => import('../modules/civilization/index.jsx')),
  },
  {
    id: 'diplomacy',
    path: '/diplomacy',
    group: 'lens',
    title: '外交博弈',
    subtitle: '中美博弈 · 区域纵横 · 能源航道',
    icon: 'Globe2',
    component: lazy(() => import('../modules/diplomacy/Page.jsx')),
  },
  {
    id: 'techtree',
    path: '/techtree',
    group: 'lens',
    title: '科技图谱',
    subtitle: '智能算力 · 可控聚变 · 深空军备',
    icon: 'GitBranch',
    component: lazy(() => import('../modules/techtree/Page.jsx')),
  },
  {
    id: 'sandbox',
    path: '/sandbox',
    group: 'sim',
    title: '治国沙盒',
    subtitle: '人才配置 · 情景推演 · 政策模拟',
    icon: 'Boxes',
    component: lazy(() => import('../modules/sandbox/Page.jsx')),
  },
  {
    id: 'santi',
    path: '/modules/santi',
    group: 'sim',
    title: '三体总论',
    subtitle: '文明透镜 · 机制映射 · 思想实验',
    icon: 'Orbit',
    accent: '#6b8cae',
    component: lazy(() => import('../modules/santi/Page.jsx')),
  },
  {
    id: 'shijianSJ00',
    path: '/modules/shijian',
    group: 'shijian',
    subgroup: 'overview',
    navOrder: 0,
    title: '史鉴·中华总索引',
    subtitle: '五柱枢纽 · 治乱螺旋 · GY 交叉',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Page.jsx')),
  },
  {
    id: 'shijianSJ01',
    path: '/modules/shijian/sj-01',
    group: 'shijian',
    subgroup: 'method',
    navOrder: 1,
    title: '史家方法对比矩阵',
    subtitle: '八家光谱 · 四栏矩阵 · 镜头指南',
    icon: 'Library',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj01Page.jsx')),
  },
  {
    id: 'shijianSJ02',
    path: '/modules/shijian/sj-02',
    group: 'shijian',
    subgroup: 'method',
    navOrder: 2,
    title: '史鉴引擎 · 四步法',
    subtitle: '结构 → 周期 → 机制 → 映射 · 台账产物',
    icon: 'Workflow',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj02Page.jsx')),
  },
  {
    id: 'shijianSJ03',
    path: '/modules/shijian/sj-03',
    group: 'shijian',
    subgroup: 'cycle',
    navOrder: 3,
    title: '五力衰变模型',
    subtitle: '财政枢纽 · 慢变量基座 · 有向耦合',
    icon: 'GitBranch',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj03Page.jsx')),
  },
  {
    id: 'shijianSJ04',
    path: '/modules/shijian/sj-04',
    group: 'shijian',
    subgroup: 'cycle',
    navOrder: 4,
    title: '治乱循环相位盘',
    subtitle: '五相位罗盘 · 修复力诊断 · 双视图',
    icon: 'Compass',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj04Page.jsx')),
  },
  {
    id: 'shijianSJ05',
    path: '/modules/shijian/sj-05',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 5,
    title: '王安石变法',
    subtitle: '变法卷首案 · 史鉴台账七字段验证',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj05Page.jsx')),
  },
  {
    id: 'shijianSJ06',
    path: '/modules/shijian/sj-06',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 6,
    title: '开元盛世 → 天宝之乱',
    subtitle: '盛衰拐点 · 内轻外重 · 强化单力反降稳定',
    icon: 'TrendingDown',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj06Page.jsx')),
  },
  {
    id: 'shijianSJ07',
    path: '/modules/shijian/sj-07',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 7,
    title: '秦汉唐明清 · 崩解对比',
    subtitle: '崩解归因矩阵 · 主链同构 · 反单因论',
    icon: 'GitCompare',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj07Page.jsx')),
  },
  {
    id: 'shijianSJ08',
    path: '/modules/shijian/sj-08',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 8,
    title: '五代十国 · 分裂与重整',
    subtitle: '军事力畸大 · 合法性归零 · 过度矫正=下一病灶',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj08Page.jsx')),
  },
  {
    id: 'shijianSJ09',
    path: '/modules/shijian/sj-09',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 9,
    title: '张居正一条鞭法',
    subtitle: '明中后期变法 · 税基重整 · 人亡政息',
    icon: 'Scale',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj09Page.jsx')),
  },
  {
    id: 'shijianSJ10',
    path: '/modules/shijian/sj-10',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 10,
    title: '明末衰变 · 崇祯易代',
    subtitle: '小冰期共振 · 三饷越阈 · 多力崩解单案',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj10Page.jsx')),
  },
  {
    id: 'shijianSJ11',
    path: '/modules/shijian/sj-11',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 11,
    title: '商鞅变法',
    subtitle: '先秦变法 · 军功爵制 · 汲取力重建',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj11Page.jsx')),
  },
  {
    id: 'shijianSJ12',
    path: '/modules/shijian/sj-12',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 12,
    title: '秦末崩解',
    subtitle: '大一统速亡 · 汲取过载 · 合法性耗尽',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj12Page.jsx')),
  },
  {
    id: 'shijianSJ13',
    path: '/modules/shijian/sj-13',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 13,
    title: '王莽改制',
    subtitle: '复古理想 vs 现实结构 · 僵化期试错',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj13Page.jsx')),
  },

  {
    id: 'shijianSJ25',
    path: '/modules/shijian/sj-25',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 25,
    eventYear: -221,
    title: '秦统一六国',
    subtitle: '制度升级 vs 战争机器',
    icon: 'Crown',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj25Page.jsx')),
  },
  {
    id: 'shijianSJ26',
    path: '/modules/shijian/sj-26',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 26,
    eventYear: -213,
    title: '焚书坑儒',
    subtitle: '合法性叙事力自毁',
    icon: 'BookX',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj26Page.jsx')),
  },  {
    id: 'shijianSJ14',
    path: '/modules/shijian/sj-14',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 14,
    title: '洋务运动',
    subtitle: '中体西用 · 局部现代化 · 体制锁定',
    icon: 'Factory',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj14Page.jsx')),
  },
  {
    id: 'shijianSJ15',
    path: '/modules/shijian/sj-15',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 15,
    title: '辛亥革命',
    subtitle: '帝制终结 · 合法性破产 · 重建未竟',
    icon: 'Landmark',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj15Page.jsx')),
  },
  {
    id: 'shijianSJ16',
    path: '/modules/shijian/sj-16',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 16,
    title: '变法谱系矩阵',
    subtitle: '综合层 · 五变法跨案对比 · 改革的两难',
    icon: 'GitMerge',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj16Page.jsx')),
  },
  {
    id: 'shijianSJ17',
    path: '/modules/shijian/sj-17',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 17,
    title: '上升奠基矩阵',
    subtitle: '综合层 · 四上升奠基跨案 · 盛世埋隐患同源',
    icon: 'TrendingUp',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj17Page.jsx')),
  },
  {
    id: 'shijianSJ18',
    path: '/modules/shijian/sj-18',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 18,
    title: '拐点谱系矩阵',
    subtitle: '综合层 · 三拐点跨案 · 鼎盛隐性危机',
    icon: 'TrendingDown',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj18Page.jsx')),
  },
  {
    id: 'shijianSJ19',
    path: '/modules/shijian/sj-19',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 19,
    title: '分裂—重整矩阵',
    subtitle: '综合层 · 四分裂期跨案 · 军事定正统',
    icon: 'GitMerge',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj19Page.jsx')),
  },
  {
    id: 'shijianSJ31',
    path: '/modules/shijian/sj-31',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 31,
    title: '官渡之战',
    subtitle: '区域军事力决胜 · 以少胜多 · 北方格局锁定',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj31Page.jsx')),
  },
  {
    id: 'shijianSJ32',
    path: '/modules/shijian/sj-32',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 32,
    title: '九品中正制',
    subtitle: '精英循环制度化 · 门阀通道 · 上品无寒门',
    icon: 'Users',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj32Page.jsx')),
  },
  {
    id: 'shijianSJ33',
    path: '/modules/shijian/sj-33',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 33,
    title: '淝水之战',
    subtitle: '军事力误判 · 士气链崩溃 · 南北分界',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj33Page.jsx')),
  },
  {
    id: 'shijianSJ34',
    path: '/modules/shijian/sj-34',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 34,
    title: '孝文帝改革',
    subtitle: '合法性叙事重建 · 汉化改制 · 分裂期整合',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj34Page.jsx')),
  },
  {
    id: 'shijianSJ27',
    path: '/modules/shijian/sj-27',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 27,
    title: '文景之治',
    subtitle: '休养生息 · 基座修复 · 汲取力降阈',
    icon: 'TrendingUp',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj27Page.jsx')),
  },

  {
    id: 'shijianSJ28',
    path: '/modules/shijian/sj-28',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 28,
    eventYear: -119,
    title: '汉武帝扩张',
    subtitle: '军事力强化 vs 财政越阈',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj28Page.jsx')),
  }, 
  {
    id: 'shijianSJ29',
    path: '/modules/shijian/sj-29',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 29,
    eventYear: 166,
    title: '东汉党锢',
    subtitle: '精英循环堵塞',
    icon: 'Users',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj29Page.jsx')),
  },
  {
    id: 'shijianSJ30',
    path: '/modules/shijian/sj-30',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 30,
    eventYear: 184,
    title: '黄巾起义',
    subtitle: '基座承载越阈',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj30Page.jsx')),
  }, {
    id: 'shijianSJ35',
    path: '/modules/shijian/sj-35',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 35,
    title: '隋文帝改革',
    subtitle: '均田—租庸调 · 三省六部 · 重整奠基',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj35Page.jsx')),
  },

  {
    id: 'shijianSJ36',
    path: '/modules/shijian/sj-36',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 36,
    eventYear: 605,
    title: '大运河',
    subtitle: '基座—财政耦合 · 工程过载',
    icon: 'Route',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj36Page.jsx')),
  }, 
  {
    id: 'shijianSJ37',
    path: '/modules/shijian/sj-37',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 37,
    eventYear: 618,
    title: '隋末崩解',
    subtitle: '工程过载+军事透支',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj37Page.jsx')),
  }, {
    id: 'shijianSJ38',
    path: '/modules/shijian/sj-38',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 38,
    title: '贞观之治',
    subtitle: '上升期制度奠基 · 五力协同 · 天可汗',
    icon: 'Crown',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj38Page.jsx')),
  },
  {
    id: 'shijianSJ39',
    path: '/modules/shijian/sj-39',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 39,
    title: '两税法',
    subtitle: '按资产征调 · 税基重整 · 汲取力修复',
    icon: 'Scale',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj39Page.jsx')),
  },

  {
    id: 'shijianSJ40',
    path: '/modules/shijian/sj-40',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 40,
    eventYear: 875,
    title: '黄巢起义',
    subtitle: '崩解期基座引燃',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj40Page.jsx')),
  },  {
    id: 'shijianSJ41',
    path: '/modules/shijian/sj-41',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 41,
    title: '靖康之耻',
    subtitle: '军事力不足 · 外交误判 · 积弱总清算',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj41Page.jsx')),
  },

  {
    id: 'shijianSJ42',
    path: '/modules/shijian/sj-42',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 42,
    eventYear: 1138,
    title: '南宋偏安',
    subtitle: '区域再配置 · 守江必守淮',
    icon: 'Map',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj42Page.jsx')),
  },
  {
    id: 'shijianSJ43',
    path: '/modules/shijian/sj-43',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 43,
    eventYear: 1005,
    title: '澶渊之盟',
    subtitle: '边疆—财政交易 · 岁币换和平',
    icon: 'Globe2',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj43Page.jsx')),
  },
  {
    id: 'shijianSJ44',
    path: '/modules/shijian/sj-44',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 44,
    eventYear: 1219,
    title: '蒙古西征',
    subtitle: '军事力扩张极限 · 花剌子模',
    icon: 'Globe2',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj44Page.jsx')),
  },  {
    id: 'shijianSJ49',
    path: '/modules/shijian/sj-49',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 49,
    title: '康乾拐点',
    subtitle: '鼎盛隐性拐点 · 人口峰值 · 僵化预埋',
    icon: 'TrendingDown',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj49Page.jsx')),
  },
  {
    id: 'shijianSJ45',
    path: '/modules/shijian/sj-45',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 45,
    title: '行省制度',
    subtitle: '央地分权创新 · 行中书省 · 省制奠基',
    icon: 'Landmark',
    accent: '#b8894a',
    component: lazy(() => import('../modules/shijian/Sj45Page.jsx')),
  },
  {
    id: 'shijianSJ46',
    path: '/modules/shijian/sj-46',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 46,
    title: '红巾起义',
    subtitle: '崩解期多力共振 · 黄河民变 · 元亡明兴',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj46Page.jsx')),
  },

  {
    id: 'shijianSJ47',
    path: '/modules/shijian/sj-47',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 47,
    eventYear: 1449,
    title: '土木之变',
    subtitle: '军事决策失败',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj47Page.jsx')),
  },
  {
    id: 'shijianSJ48',
    path: '/modules/shijian/sj-48',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 48,
    eventYear: 1405,
    title: '郑和下西洋',
    subtitle: '合法性象征投入',
    icon: 'Ship',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj48Page.jsx')),
  },  {
    id: 'shijianSJ50',
    path: '/modules/shijian/sj-50',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 50,
    title: '太平天国',
    subtitle: '基座承载越阈 · 军事消耗 · 清帝国震荡',
    icon: 'Flame',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj50Page.jsx')),
  },
  {
    id: 'shijianSJ51',
    path: '/modules/shijian/sj-51',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 51,
    title: '戊戌变法',
    subtitle: '体制突破失败 · 百日维新 · 守旧反扑',
    icon: 'Scale',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj51Page.jsx')),
  },
  {
    id: 'shijianSJ52',
    path: '/modules/shijian/sj-52',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 52,
    title: '五四运动',
    subtitle: '合法性叙事断裂 · 拒签和约',
    icon: 'Radio',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj52Page.jsx')),
  },
  {
    id: 'shijianSJ53',
    path: '/modules/shijian/sj-53',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 53,
    title: '北伐战争',
    subtitle: '军事力定正统 · 国共合作',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj53Page.jsx')),
  },
  {
    id: 'shijianSJ54',
    path: '/modules/shijian/sj-54',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 54,
    title: '吴起变法',
    subtitle: '触动贵族 · 强兵抚战 · 人亡政废',
    icon: 'Scale',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj54Page.jsx')),
  },
  {
    id: 'shijianSJ55',
    path: '/modules/shijian/sj-55',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 55,
    title: '合纵连横',
    subtitle: '外交—军事博弈 · 纵横家',
    icon: 'Globe2',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj55Page.jsx')),
  },
  {
    id: 'shijianSJ56',
    path: '/modules/shijian/sj-56',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 56,
    title: '长平之战',
    subtitle: '军事消耗 · 基座承载越阈',
    icon: 'Swords',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj56Page.jsx')),
  },
  {
    id: 'shijianSJ57',
    path: '/modules/shijian/sj-57',
    group: 'shijian',
    subgroup: 'cases',
    navOrder: 57,
    title: '百家争鸣',
    subtitle: '合法性叙事竞争 · 诸子百家',
    icon: 'ScrollText',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj57Page.jsx')),
  },
  {
    id: 'shijianSJ20',
    path: '/modules/shijian/sj-20',
    group: 'shijian',
    subgroup: 'mirror',
    navOrder: 20,
    title: '政治映射 · 古今对照',
    subtitle: '精英循环 · 合法性叙事 · 央地钟摆',
    icon: 'Landmark',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj20Page.jsx')),
  },
  {
    id: 'shijianSJ21',
    path: '/modules/shijian/sj-21',
    group: 'shijian',
    subgroup: 'mirror',
    navOrder: 21,
    title: '经济映射 · 古今对照',
    subtitle: '盐铁→国资 · 税制→土地财政 · 常平仓→调控',
    icon: 'Coins',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj21Page.jsx')),
  },
  {
    id: 'shijianSJ22',
    path: '/modules/shijian/sj-22',
    group: 'shijian',
    subgroup: 'mirror',
    navOrder: 22,
    title: '文化映射 · 古今对照',
    subtitle: '象征通胀 · 文教投入 · 思想边界 · 意识形态再生产',
    icon: 'Sparkles',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj22Page.jsx')),
  },
  {
    id: 'shijianSJ23',
    path: '/modules/shijian/sj-23',
    group: 'shijian',
    subgroup: 'mirror',
    navOrder: 23,
    title: '社会映射 · 古今对照',
    subtitle: '承载上限 · 流民变体 · 人口结构容错',
    icon: 'Users',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj23Page.jsx')),
  },
  {
    id: 'shijianSJ24',
    path: '/modules/shijian/sj-24',
    group: 'shijian',
    subgroup: 'mirror',
    navOrder: 24,
    title: '外交映射 · 古今对照',
    subtitle: '边疆周期 · 朝贡秩序 · 军费财政 · 秩序话语',
    icon: 'Globe2',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian/Sj24Page.jsx')),
  },
  {
    id: 'shijianWorldSJW00',
    path: '/modules/shijian-world',
    group: 'shijianWorld',
    subgroup: 'world-hub',
    navOrder: 0,
    title: '史鉴·世界总索引',
    subtitle: '比较历史 · 五轴可配置 · 中华交叉',
    icon: 'Globe',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Page.jsx')),
  },
  {
    id: 'shijianWorldSJW01',
    path: '/modules/shijian-world/sjw-01',
    group: 'shijianWorld',
    subgroup: 'world-rise',
    navOrder: 10,
    title: '大国崛起谱系',
    subtitle: '海权窗口 · 财政信用 · 制度学习',
    icon: 'TrendingUp',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw01Page.jsx')),
  },
  {
    id: 'shijianWorldSJW02',
    path: '/modules/shijian-world/sjw-02',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 23,
    title: '两次世界大战',
    subtitle: '联盟锁死 · 总体战 · 帝国透支',
    icon: 'Swords',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw02Page.jsx')),
  },
  {
    id: 'shijianWorldSJW03',
    path: '/modules/shijian-world/sjw-03',
    group: 'shijianWorld',
    subgroup: 'world-ideo',
    navOrder: 41,
    title: '苏联崛起与解体',
    subtitle: '动员汲取 · 党国精英 · 意识形态疲劳',
    icon: 'Landmark',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw03Page.jsx')),
  },
  {
    id: 'shijianWorldSJW04',
    path: '/modules/shijian-world/sjw-04',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 30,
    title: '文明兴衰与博弈',
    subtitle: '比较史学 · 历史机制 · 三体边界',
    icon: 'Orbit',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw04Page.jsx')),
  },
  {
    id: 'shijianWorldSJW05',
    path: '/modules/shijian-world/sjw-05',
    group: 'shijianWorld',
    subgroup: 'world-ideo',
    navOrder: 40,
    title: '社会主义运动谱系',
    subtitle: '公社 · 第二国际 · 列宁主义/社民',
    icon: 'Network',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw05Page.jsx')),
  },
  {
    id: 'shijianWorldSJW06',
    path: '/modules/shijian-world/sjw-06',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 31,
    title: '地缘政治经典案',
    subtitle: '马汉 · 麦金德 · 斯皮克曼',
    icon: 'Map',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw06Page.jsx')),
  },
  {
    id: 'shijianWorldSJW07',
    path: '/modules/shijian-world/sjw-07',
    group: 'shijianWorld',
    subgroup: 'world-rise',
    navOrder: 12,
    title: '英/美霸权转移深描',
    subtitle: '英镑信用 · 美元秩序 · 海权交接',
    icon: 'ArrowLeftRight',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw07Page.jsx')),
  },
  {
    id: 'shijianWorldSJW08',
    path: '/modules/shijian-world/sjw-08',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 24,
    title: '冷战与核威慑机制史',
    subtitle: '二次打击 · 指挥链 · 危机管控',
    icon: 'Shield',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw08Page.jsx')),
  },
  {
    id: 'shijianWorldSJW09',
    path: '/modules/shijian-world/sjw-09',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 32,
    title: '奥斯曼/波斯/莫卧儿衰变',
    subtitle: '三帝国共振 · 对照 SJ-07',
    icon: 'Layers',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw09Page.jsx')),
  },
  {
    id: 'shijianWorldSJW10',
    path: '/modules/shijian-world/sjw-10',
    group: 'shijianWorld',
    subgroup: 'world-ideo',
    navOrder: 42,
    title: '去殖民化与发展型国家',
    subtitle: '主权浪潮 · 路径分叉 · 陷阱',
    icon: 'GitBranch',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw10Page.jsx')),
  },
  {
    id: 'shijianWorldSJW11',
    path: '/modules/shijian-world/sjw-11',
    group: 'shijianWorld',
    subgroup: 'world-rise',
    navOrder: 11,
    title: '工业革命单案深描',
    subtitle: '煤铁蒸汽 · 信用 · 帝国市场',
    icon: 'Factory',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw11Page.jsx')),
  },
  {
    id: 'shijianWorldSJW12',
    path: '/modules/shijian-world/sjw-12',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 20,
    title: '维也纳体系深描',
    subtitle: '会议外交 · 正统 · 均势',
    icon: 'Users',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw12Page.jsx')),
  },
  {
    id: 'shijianWorldSJW13',
    path: '/modules/shijian-world/sjw-13',
    group: 'shijianWorld',
    subgroup: 'world-rise',
    navOrder: 13,
    title: '霸权交接综合矩阵',
    subtitle: '荷—英—美 · 信用海权制度',
    icon: 'GitCompare',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw13Page.jsx')),
  },
  {
    id: 'shijianWorldSJW14',
    path: '/modules/shijian-world/sjw-14',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 33,
    title: '大分流 / 加州学派对照',
    subtitle: '欧亚并置 · 煤与美洲 · ↔ SJ-21',
    icon: 'Split',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw14Page.jsx')),
  },
  {
    id: 'shijianWorldSJW15',
    path: '/modules/shijian-world/sjw-15',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 50,
    title: '明治—战后日本发展型国家',
    subtitle: '富国强兵 · MITI · 安全伞',
    icon: 'Building2',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw15Page.jsx')),
  },
  {
    id: 'shijianWorldSJW16',
    path: '/modules/shijian-world/sjw-16',
    group: 'shijianWorld',
    subgroup: 'world-tech',
    navOrder: 60,
    title: '布雷顿森林→广场协议',
    subtitle: '美元金锚 · 尼克松冲击 · 广场',
    icon: 'Coins',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw16Page.jsx')),
  },
  {
    id: 'shijianWorldSJW17',
    path: '/modules/shijian-world/sjw-17',
    group: 'shijianWorld',
    subgroup: 'world-ideo',
    navOrder: 43,
    title: '去殖民化非亚/拉美矩阵',
    subtitle: '主权后分叉 · 区域对照',
    icon: 'LayoutGrid',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw17Page.jsx')),
  },
  {
    id: 'shijianWorldSJW18',
    path: '/modules/shijian-world/sjw-18',
    group: 'shijianWorld',
    subgroup: 'world-tech',
    navOrder: 62,
    title: '气候—能源基座',
    subtitle: '碳基上限 · 能源压舱石',
    icon: 'Flame',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw18Page.jsx')),
  },
  {
    id: 'shijianWorldSJW19',
    path: '/modules/shijian-world/sjw-19',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 21,
    title: '法国大革命—拿破仑秩序',
    subtitle: '人民主权 · 动员 · 维也纳回摆',
    icon: 'Landmark',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw19Page.jsx')),
  },
  {
    id: 'shijianWorldSJW20',
    path: '/modules/shijian-world/sjw-20',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 22,
    title: '德国统一与大战前转移',
    subtitle: '工业追赶 · 联盟死结 · ↔ SJW-02',
    icon: 'Swords',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw20Page.jsx')),
  },
  {
    id: 'shijianWorldSJW21',
    path: '/modules/shijian-world/sjw-21',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 34,
    title: '石油时代与中东地缘',
    subtitle: '油井 · 海峡 · 租金政治',
    icon: 'Fuel',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw21Page.jsx')),
  },
  {
    id: 'shijianWorldSJW22',
    path: '/modules/shijian-world/sjw-22',
    group: 'shijianWorld',
    subgroup: 'world-ideo',
    navOrder: 44,
    title: '中国改革开放对照外卷',
    subtitle: '发展型对照 · 关键差异',
    icon: 'GitBranch',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw22Page.jsx')),
  },
  {
    id: 'shijianWorldSJW23',
    path: '/modules/shijian-world/sjw-23',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 56,
    title: '发展型国家谱系矩阵',
    subtitle: '日 · 韩 · 新加坡 · 中国',
    icon: 'LayoutGrid',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw23Page.jsx')),
  },
  {
    id: 'shijianWorldSJW24',
    path: '/modules/shijian-world/sjw-24',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 51,
    title: '韩国发展型国家',
    subtitle: '威权汲取 · 财阀出口 · 冷战前线',
    icon: 'Factory',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw24Page.jsx')),
  },
  {
    id: 'shijianWorldSJW25',
    path: '/modules/shijian-world/sjw-25',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 55,
    title: '拉美 ISI 与债务危机',
    subtitle: '进口替代 · 石油美元 · 失去的十年',
    icon: 'Landmark',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian-world/Sjw25Page.jsx')),
  },
  {
    id: 'shijianWorldSJW26',
    path: '/modules/shijian-world/sjw-26',
    group: 'shijianWorld',
    subgroup: 'world-tech',
    navOrder: 61,
    title: '欧盟货币一体化',
    subtitle: 'EMS · 马约 · 欧元机制史',
    icon: 'Coins',
    accent: '#b8894a',
    component: lazy(() => import('../modules/shijian-world/Sjw26Page.jsx')),
  },
  {
    id: 'shijianWorldSJW27',
    path: '/modules/shijian-world/sjw-27',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 52,
    title: '台湾发展型对照',
    subtitle: '土改 · 出口加工 · 半导体 · ↔ 日韩',
    icon: 'Cpu',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw27Page.jsx')),
  },
  {
    id: 'shijianWorldSJW28',
    path: '/modules/shijian-world/sjw-28',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 54,
    title: '印度独立后发展路径',
    subtitle: '民主 · 计划许可 · 1991 改革',
    icon: 'Landmark',
    accent: '#b8894a',
    component: lazy(() => import('../modules/shijian-world/Sjw28Page.jsx')),
  },
  {
    id: 'shijianWorldSJW29',
    path: '/modules/shijian-world/sjw-29',
    group: 'shijianWorld',
    subgroup: 'world-dev',
    navOrder: 53,
    title: '东南亚四小虎对照',
    subtitle: '新 · 马 · 泰 · 印尼',
    icon: 'Factory',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw29Page.jsx')),
  },
  {
    id: 'shijianWorldSJW30',
    path: '/modules/shijian-world/sjw-30',
    group: 'shijianWorld',
    subgroup: 'world-civ',
    navOrder: 35,
    title: '非洲后殖民资源—主权',
    subtitle: '边界 · 租金 · 国家能力',
    icon: 'Globe2',
    accent: '#a83b2c',
    component: lazy(() => import('../modules/shijian-world/Sjw30Page.jsx')),
  },
  {
    id: 'shijianWorldSJW31',
    path: '/modules/shijian-world/sjw-31',
    group: 'shijianWorld',
    subgroup: 'world-war',
    navOrder: 25,
    title: '联合国体系与国际组织',
    subtitle: '宪章 · 安理会 · 功能机构',
    icon: 'Building2',
    accent: '#4a6d7c',
    component: lazy(() => import('../modules/shijian-world/Sjw31Page.jsx')),
  },
  {
    id: 'shijianWorldSJW32',
    path: '/modules/shijian-world/sjw-32',
    group: 'shijianWorld',
    subgroup: 'world-tech',
    navOrder: 63,
    title: '数字/科技霸权与标准竞争',
    subtitle: '标准 · 算力 · 联盟管制',
    icon: 'Cpu',
    accent: '#b8894a',
    component: lazy(() => import('../modules/shijian-world/Sjw32Page.jsx')),
  },
  {
    id: 'guoyun',
    path: '/modules/guoyun',
    group: 'sim',
    title: '国运模拟器',
    subtitle: '七时代轴 · 情景推演 · 观测哨',
    icon: 'Compass',
    component: lazy(() => import('../modules/guoyun/Page.jsx')),
  },
  {
    id: 'yishixingtai',
    path: '/modules/yishixingtai',
    group: 'sim',
    title: '合法性机器',
    subtitle: '意识形态架构 · 五组件 · GY-02',
    icon: 'Layers',
    component: lazy(() => import('../modules/yishixingtai/Page.jsx')),
  },
  {
    id: 'observatory',
    path: '/modules/observatory',
    group: 'governance',
    title: '观象台',
    subtitle: '世界→中国→同类→我 · 2026 H1 判读',
    icon: 'Telescope',
    accent: '#b18a52',
    component: lazy(() => import('../modules/governanceHub/Page.jsx')),
  },
  {
    id: 'signalPanel',
    path: '/modules/signal-panel',
    group: 'governance',
    title: '宏观再平衡信号灯',
    subtitle: 'A/B/C 信号 · 态势合成 · 2026-07',
    icon: 'Gauge',
    component: lazy(() => import('../modules/signalPanel/Page.jsx')),
  },
  {
    id: 'threeForces',
    path: '/modules/three-forces',
    group: 'governance',
    title: '三力监测仪',
    subtitle: '改革窗口 · H1 压力读数 · 反直觉',
    icon: 'Activity',
    component: lazy(() => import('../modules/threeForces/Page.jsx')),
  },
  {
    id: 'attribution',
    path: '/modules/attribution',
    group: 'governance',
    title: '三层归因分析器',
    subtitle: '路线 · 决策 · 执行 · 误诊预警',
    icon: 'Scale',
    component: lazy(() => import('../modules/attribution/Page.jsx')),
  },
  {
    id: 'premierRadius',
    path: '/modules/premier-radius',
    group: 'governance',
    title: '总理权限半径',
    subtitle: '职权收缩 · 制度轨迹 · 1998—今',
    icon: 'CircleDot',
    component: lazy(() => import('../modules/premierRadius/Page.jsx')),
  },
  {
    id: 'cushionMonitor',
    path: '/modules/cushion-monitor',
    group: 'governance',
    title: '垫子厚度监测',
    subtitle: '未富先躺 · 四国锚点 · 命运矩阵',
    icon: 'Layers',
    component: lazy(() => import('../modules/cushionMonitor/Page.jsx')),
  },
  {
    id: 'leadership', path: '/leadership', group: 'sim',
    title: '领袖统治', subtitle: '权力结构 · 决策机制 · 12 图可视化 · 四区交互', icon: 'Crown',
    component: lazy(() => import('../modules/leadership/Page.jsx')),
  },
  {
    id: 'talent', path: '/talent', group: 'sim',
    title: '人才精英库', subtitle: '结构化人力资本图谱 · 截至 2026-07 · 政要 / 反腐透视 / 知识生产 / 资本逻辑', icon: 'UsersRound',
    component: lazy(() => import('../modules/talent/Page.jsx')),
  },
  {
    id: 'policydocs', path: '/policydocs', group: 'sim',
    title: '政令文库', subtitle: '政策文件 · 法律条文 · 文本挖掘', icon: 'FileText',
    component: lazy(() => import('../modules/policydocs/Page.jsx')),
  },
  {
    id: 'foundation',
    path: '/foundation',
    group: 'foundation',
    title: '数据底座',
    subtitle: '世界银行 · 国家统计局 · IMF',
    icon: 'Database',
    component: lazy(() => import('../modules/foundation/Page.jsx')),
  },
  {
    id: 'glossary', path: '/glossary', group: 'foundation',
    title: '术语词典', subtitle: '专有名词 · 调研术语 · 模块交叉链接', icon: 'BookOpen',
    component: lazy(() => import('../modules/glossary/Page.jsx')),
  },
  {
    id: 'watchtower', path: '/watchtower', group: 'foundation',
    title: '全局监测台', subtitle: '六域先行指标 · 三档阈值 · 越线告警', icon: 'Siren',
    component: lazy(() => import('../modules/watchtower/Page.jsx')),
  },
];

// 分组级排序器（仅 population 组按 语义簇/优先级/相似性/标题长度 重排，见 lib/gy/navOrder）
const GROUP_COMPARATORS = {
  population: populationNavCompare,
  shijian: shijianNavCompare,
  shijianWorld: shijianWorldNavCompare,
};
export { getShijianEventYear, formatEventYear, SHIJIAN_CASE_EVENT_YEARS } from '../lib/shijian/caseYears.js';

/** 案例库模块按事件时间序（单案升序 + 综合矩阵底栏） */
export function shijianCasesByTime(mods) {
  const cmp = GROUP_COMPARATORS.shijian;
  return mods.filter((m) => m.subgroup === 'cases').sort(cmp);
}
export const HUANGFEIZHAI_GROUP_ID = 'huangfeizhai';

export const modulesByGroup = (groupId) => {
  // navHidden：保留路由与深链，但不进侧栏（如促消费全文页 → 经济大盘 Tab）
  const list = MODULES.filter((m) => m.group === groupId && !m.navHidden);
  const cmp = GROUP_COMPARATORS[groupId];
  return cmp ? [...list].sort(cmp) : list;
};
export const moduleById = (id) => MODULES.find((m) => m.id === id);
export const isHuangfeizhaiModule = (mod) => mod?.group === HUANGFEIZHAI_GROUP_ID;
export const DEFAULT_MODULE = MODULES[0];
