// 萧功秦 · 思想光谱条目（取自 data.js 已核验条目；无可核验表态的议题留空）
export const STANCES = {
  reformPath: {
    stance: '保持体制连续性与秩序稳定，经由渐进的经济社会发展最终走向民主',
    type: '原话',
    quote: '它主张在保持现存体制的历史连续性与秩序稳定的条件下，通过渐进的经济与社会发展最终走向民主政治。',
    date: '2012',
    venue: '天大研究院报告 · 从中道立场理解中国转型——关于超越左右激进主义的思考',
    source: '爱思想全文转载',
    url: 'https://www.aisixiang.com/data/57141.html',
    verified: 'primary',
  },
  democracy: {
    stance: '民主化须先经由全能主义向权威主义过渡的阶段，反对一步到位',
    type: '原话',
    quote: '中国民主化必须经由从全能主义向权威主义过渡的这一阶段。',
    date: '2008-01',
    venue: '《从发展政治学看中国转型体制》，《浙江学刊》2008 年第 1 期',
    source: '《浙江学刊》（爱思想全文转载）',
    url: 'https://www.aisixiang.com/data/45063.html',
    verified: 'primary',
  },
  partyState: {
    stance: '把"共产党领导加市场经济"读作后发展国家的新权威主义',
    type: '原话',
    quote: '共产党领导加市场经济的中国模式，实际上就起到后发展国家中的新权威主义。',
    date: '2016',
    venue: '《中国模式的内涵及前途》，《武汉大学学报》（人文科学版）2016 年第 4 期',
    source: '《武汉大学学报》（人民论坛网 2016-09-26 转载）',
    url: 'https://www.rmlt.com.cn/2016/0926/440831.shtml',
    verified: 'primary',
  },
  legitimacy: {
    stance: '稳定的根基在多数民众的心态稳定，警惕转型综合症侵蚀秩序',
    type: '原话',
    quote: '现代化的政治决策者们应充分清醒地认识到，真正的稳定乃是占人口大多数的民众的心态的稳定。',
    date: '1994',
    venue: '《“软政权”与分利集团化：中国现代化的两重陷阱》，《战略与管理》1994 年第 1 期',
    source: '《战略与管理》（爱思想全文转载）',
    url: 'https://www.aisixiang.com/data/6770.html',
    verified: 'primary',
  },
  bureaucracy: {
    stance: '警惕"软政权"：行政贯彻力退化、执行低效、法规被任意破坏',
    type: '原话',
    quote: '这里的软政权，指的是发展中国家在现代化过程中，行政命令贯彻能力的退化、行政实施效率的低下和法律规则被任意破坏而引起的综合现象。',
    date: '1994',
    venue: '《“软政权”与分利集团化：中国现代化的两重陷阱》，《战略与管理》1994 年第 1 期',
    source: '《战略与管理》（爱思想全文转载）',
    url: 'https://www.aisixiang.com/data/6770.html',
    verified: 'primary',
  },
  centralLocal: {
    stance: '放权让利中地方势力可能截留下放权力，形成"地方割据"式分利集团',
    type: '转述',
    date: '1994',
    venue: '《“软政权”与分利集团化：中国现代化的两重陷阱》，《战略与管理》1994 年第 1 期',
    source: '《战略与管理》（爱思想全文转载）',
    url: 'https://www.aisixiang.com/data/6770.html',
    verified: 'primary',
  },
  consumption: {
    stance: '"国富民穷困境"使社会消费严重不足，拖累经济可持续发展',
    type: '原话',
    quote: '其结果直接导致社会消费严重不足。',
    date: '2010-11-09',
    venue: '《中国模式优势背后面临五大困境》',
    source: '爱思想（作者授权发布）',
    url: 'https://www.aisixiang.com/data/37146.html',
    verified: 'primary',
  },
};
